### ISSUE TITLE
Can't install from AUR, neither compile on Arch

### ISSUE THREAD

**Issue by woohgit** [r-darwish/topgrade#100]
```bash
error: failed to parse manifest at `/home/wooh/repos/topgrade/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["rename-dependency"]` to enable this feature
```

**Comment by r-darwish** [comment]
Are you using the most up to date version of Rust? (1.31)?

**Comment by woohgit** [comment]
No, but I just tried to use upgrade `topgrade` via `pacman` but it failed. Probably because the latest `rust` version is `1.30` even in AUR.

**Comment by woohgit** [comment]
Yes my mirrors are up-to-date. I'm not literally using Arch, but Manjaro. It means I get updates in 5-7 days. Although `topgrade` is in `AUR` and it is used by many other distributions than Arch. 

But I get it, I just need to wait a bit more. Wonder if distributing via binary would be a better idea than compiling on the host itself.

**Comment by r-darwish** [comment]
I didn't take into account Manjaro. I myself use the binary for all of my machines. It saves me the trouble of compiling and has a self-update feature.

**Comment by woohgit** [comment]
I missed the binary option. I was using the `AUR` one. What if you change the AUR to provide the binary instead of the compile on host option?

**Comment by woohgit** [comment]
Yeah I changed my `ansible` recipes to use the binary option now. I pretty much missed that option. Thanks. :+1:
