### ISSUE TITLE
Support brew cask mode

### ISSUE THREAD

**Issue by remm** [r-darwish/topgrade#103]
Package manager `brew` supports cask mode, which installs macOS apps, fonts and plugins and other non-open source software.
cask works as separated mode and has separated `update` and `upgrade` commands.
As I see, topgrage doesn't support brew cask mode now.

**Comment by gmerlino** [comment]
Is it possible to include also:

https://github.com/buo/homebrew-cask-upgrade

In my personal workflow, after invoking "brew upgrade" and "brew cask upgrade", I always run "brew cu -a" as well, as it is a more complete way to upgrade casks (e.g., including the ones which are auto-updatable)
