### ISSUE TITLE
Vagrant boxes

### ISSUE THREAD

**Issue by r-darwish** [r-darwish/topgrade#104]

**Comment by nCrazed** [comment]
@r-darwish can you elaborate on the feature?

Is it just a case of running `vagrant box outdated --global` then looping over the output to pass the box name to `vagrant box update --box $ARG` or is there more to it?

**Comment by r-darwish** [comment]
I think that should do. Sadly, Vagrant doesn't provide a single upgrade command.

**Comment by r-darwish** [comment]
I actually implemented this but decided not to commit. Here's why:

1. `vagrant box outdated --global` is somewhat slow, but that's not a deal breaker
2. Upgrading the boxes can take hours because boxes usually weight a few Gigabytes
3. When you download a new box, the old one is still there and is still reported as outdated when you run `vagrant box outdated --global`

I might consider this in the future if Vagrant adds a command to upgrade all boxes

**Comment by nCrazed** [comment]
> I might consider this in the future if Vagrant adds a command to upgrade all boxes

That is unlikely to happen doing that would require destroying and re-provisioning the existing machines. Which is something that should be decided by users on case-by-case basis due to the potential loss of data/state.
