### ISSUE TITLE
Looking for .emacs.d dir in the wrong place on Windows

### ISSUE THREAD

**Issue by drrlvn** [r-darwish/topgrade#112]
https://github.com/r-darwish/topgrade/blob/71558e6bdbaaa47eeb15dd8f19c0ae9a4b360b9d/src/steps/generic.rs#L54

On Windows the config dir is in `%appdata%/Roaming/.emacs.d` (which is `base_dirs.config_dir()`).

**Comment by r-darwish** [comment]
It's not wrong, there are multiple [possible locations](https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Location-of-init-file.html#Location-of-init-file). I think we should look for 1 and 5. The others seems redundant.

**Comment by drrlvn** [comment]
Unless I'm mistaken neither of those is `home_dir()` (which is `C:\<user>`).

**Comment by r-darwish** [comment]
I set the `HOME` variable explicitly so I guess it changed the output of `home_dir()`. I shouldn't rely on it in Windows, but instead just check both the `HOME` environment variable manually, and the appdata dir.

**Comment by r-darwish** [comment]
Reopening because Topgrade doesn't upgrade Emacs if the path is in AppData
