### ISSUE TITLE
Paths are displayed weirdly on Windows

### ISSUE THREAD

**Issue by drrlvn** [r-darwish/topgrade#113]
There's a `//?/` before the path, e.g.:

```
―― Pulling //?/C:/Users/Dror Levin/config-files ―――――――――――――――――――――――――――――――――
```

Also `topgrade` is printing slashes instead of backslashes but that's acceptable.

**Comment by tversteeg** [comment]
This is a proper path in Windows: https://stackoverflow.com/a/21194605/1350184

**Comment by r-darwish** [comment]
@tversteeg I know. It's just not very human friendly as people aren't really used to that
