### ISSUE TITLE
Add flag for unattended upgrade

### ISSUE THREAD

**Issue by camiller** [r-darwish/topgrade#118]
Would be nice to have a flag so that topgrade will skip the "do you want to continue" and just go ahead and do the upgrade without me having to type "Y" two or three time in the process.

**Comment by tversteeg** [comment]
There is the `--no-retry` flag..

**Comment by camiller** [comment]
It's not really failures I'm talking about, it's when topgrade finds
something that needs updating and then asks permission to proceed.
--
Chris Miller
Omaha, NE

My public key
<https://pgp.mit.edu/pks/lookup?op=get&search=0x1B5CA15A612E9C4A>

**Comment by r-darwish** [comment]
I considered that before. Here are my thoughts:

* I don't know if I can guarantee full unattended run. Package managers have `-y` flags, but I don't know if I can make git not to ask you for a prompt if it needs your SSH password.
    * You specifically mentioned permissions, and that's actually the problem. I can't make sudo not to ask your for a password. What I can do is run it in the beginning of the session, but that's what I practically do because the first thing I run is the system package manager. This means that if the session is short enough then other steps requiring sudo will not prompt you for a password because the sudo session is still active. Still, this isn't fully unattended installation. You can't run it from cron. If you want to skip permission prompt then you have to configure sudo not to ask a password for your account, which is something most people advise against.
* It's not my job to change other people's habit, but I don't think fully unattended "upgrade everything" command is a good idea on your personal server or workstation. Package managers usually prompt your for good reasons. I don't think I'd use this feature even if it existed.
* I use Topgrade on 4 operating systems and I think that I run 80% steps, and prompting isn't an issue for me. I usually get the sudo prompt at the beginning, and then the confirmation of `yay` and that's about it. There are retry prompts, but they can be disabled by `--no-retry`.

I'll leave this open for more opinions.

**Comment by camiller** [comment]
regarding point 1. I guess I was still thinking to start it manually, then
go get coffee (or some nights go to bed) and have it be done when I get
back. I've never had it not finish before the sudo timeout as long as I was
there to press Y. I don't actually have it do my git repos, but I can see
that being an issue.

point 2&3 fair enough


--
Chris Miller
Omaha, NE

My public key
<https://pgp.mit.edu/pks/lookup?op=get&search=0x1B5CA15A612E9C4A>

**Comment by Serrvosky** [comment]
Hello. 

I'm trying topgrade and I share @camiller 's opinion. It would be great to have that flag. It will make a huge improve to this project, because that way we can run topgrade in a routine automatically.
