### ISSUE TITLE
Various small questions

### ISSUE THREAD

**Issue by IngwiePhoenix** [r-darwish/topgrade#123]
Hey there!

First off: THANK YOU for this awesome tool! It has saved me a lot of time from tracking all those package managers myself with custom scripts and whatnot. This is one very, very useful package!

Now, I just have a few small questions:
- My Rustup is installed through Homebrew, so selfupdating is actually disabled. Can I disable rustup?
- Mac OS has a Ruby pre-installed - but it's so old, that it is common to be replaced by one installed through Homebrew. How can I tell topgrade to use that one's `gem` instead?
- Why does topgrade only do pipx but not pip, or pip3? I just threw pipx into my system, but I'm still curios about why you can not use pip directly.
- Yarn is used, but is NPM even aknowledged by topgrade? I prefer to use NPM for global installs and yarn for package-local ones. Can I tell topgrade to use NPM instead of Yarn?

Again, thanks for this awesome tool! Kind regards,

Ingwie.

**Comment by r-darwish** [comment]
Thanks for taking the time to write this feedback.

* I encountered that problem a while ago and I'm still not sure what to do about it. Currently, I do not know of a way to determine if rustup has the self upgrade feature before running it. Perhaps I should open an issue for them.

* Topgrade finds gem using the standard `PATH`. What does `which gem` outputs?

* pip wasn't designed a package manager that manages applications. It has the `--user` flag which supposed to do that, but it does not know how to handle upgrades without breaking anything. It installs all tools into the same environment and do not handle conflicts. For example, if you install pgcli which requires `click<7` during the installation, then you'll have click 6 installed. However, if you install a tool that requires `click>6` then pip will not complain and just upgrade click, potentially breaking `pgcli`. pipx and pipsi oversome this by installing each tool in its own environment and providing a command to upgrade the tool themselves.

* I'm not an node expert and I just assume that yarn is superior to NPM, so I use yarn whenever possible. What advantages does NPM have over Yarn?

**Comment by IngwiePhoenix** [comment]
> * I encountered that problem a while ago and I'm still not sure what to do about it. Currently, I do not know of a way to determine if rustup has the self upgrade feature before running it. Perhaps I should open an issue for them.

Opening an issue to them would make sense, I just looked at what the exit code is when the self-updating feature does not work, and it is `1`, just like a regular error had occured, which is not exactly the case. The currently best workaround would be to add an option to the config, stating that trying to update rustup should be disabled.

> * Topgrade finds gem using the standard `PATH`. What does `which gem` outputs?
```
Ingwie@Ingwies-Macbook-Pro.local /tmp $ which -a gem
/usr/local/opt/ruby/bin/gem
/usr/bin/gem
Ingwie@Ingwies-Macbook-Pro.local /tmp $ gem --version
3.0.2
Ingwie@Ingwies-Macbook-Pro.local /tmp $ /usr/bin/gem --version
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /private/tmp/. in PATH, mode 041777
2.5.2.3
Ingwie@Ingwies-Macbook-Pro.local /tmp $ /usr/local/opt/ruby/bin/gem --version
3.0.2
Ingwie@Ingwies-Macbook-Pro.local /tmp $ which -a ruby
/usr/local/opt/ruby/bin/ruby
/usr/bin/ruby
Ingwie@Ingwies-Macbook-Pro.local /tmp $ /usr/local/opt/ruby/bin/ruby --version
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
Ingwie@Ingwies-Macbook-Pro.local /tmp $ /usr/bin/ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```

Now, when I use topgrade to upgrade my gems, it reports that my installed Ruby is 2.3, whilst 2.5 is required for a package. Unfortunately, I already fixed it manually, so I can not replicate the error message. But essentially, `topgrade` was picking from `/usr/bin/gem` instead of the one shown above, which is a much later version than the OS X default one. So being able to either specify the specific binary or to see which one is being picked, would be quite helpful. Maybe add a `--verbose` flag to show which commands are being run?

> * pip wasn't designed a package manager that manages applications. It has the `--user` flag which supposed to do that, but it does not know how to handle upgrades without breaking anything. It installs all tools into the same environment and do not handle conflicts. For example, if you install pgcli which requires `click<7` during the installation, then you'll have click 6 installed. However, if you install a tool that requires `click>6` then pip will not complain and just upgrade click, potentially breaking `pgcli`. pipx and pipsi oversome this by installing each tool in its own environment and providing a command to upgrade the tool themselves.
Ahh, okay. I am not much of a Python guy, so I didn't know that. :)

> * I'm not an node expert and I just assume that yarn is superior to NPM, so I use yarn whenever possible. What advantages does NPM have over Yarn?
Well, yarn itself is a global NPM package, but like NPM itself, it won't selfupdate. Plus, Yarn is meant more to be used for projects rather than globally. Whilst it definitively can be used for global installs too, it does not seem to be recommended. Also, compare this:

```
Ingwie@Ingwies-Macbook-Pro.local /tmp $ yarn global upgrade
yarn global v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Rebuilding all packages...
success Saved lockfile.
success Saved 0 new dependencies.
✨  Done in 0.06s.
Ingwie@Ingwies-Macbook-Pro.local /tmp $ npm -g upgrade
... snip ...
npm ERR! path /usr/local/bin/idea
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/local/bin/idea: is outside /usr/local/lib/node_modules/idea and not a link
npm ERR! File exists: /usr/local/bin/idea
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Ingwie/.npm/_logs/2019-02-12T10_00_36_800Z-debug.log
```

Yarn did NOT report this error, but also updated nothing at all. It just quietly failed instead. The `idea` binary mentioned here is from IntelliJ IDEA, by the way. I moved the binary, and now this happens:
```
Ingwie@Ingwies-Macbook-Pro.local /tmp $ yarn global upgrade
yarn global v1.13.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Rebuilding all packages...
success Saved lockfile.
success Saved 0 new dependencies.
✨  Done in 0.06s.
```

Yup, nothing. NPM though...
```
Ingwie@Ingwies-Macbook-Pro.local /tmp $ npm -g upgrade
... snip ...
+ idea@2.0.10
+ cli-github@1.8.16
+ dotphp@3.5.0
+ @webassemblyjs/cli@1.8.1
+ bower@1.8.8
+ ava@1.2.1
+ serverless@1.37.1
added 13 packages from 12 contributors, removed 61 packages, updated 152 packages and moved 2 packages in 13.009s
```

Much different. :)

So, it might be better to use NPM here. I don't know why Yarn does practically nothing here, actually. But hey, even more the reason to use NPM. Also: `npm -g install npm` is basically an NPM self-update, because it won't update itself when doing `-g upgrade`.

**Comment by r-darwish** [comment]
* I checked again and I actually run the self upgrade only if rustup is installed at your home directory, see [this line](https://github.com/r-darwish/topgrade/blob/f56b1076975e4e153a91d5bd370d313f2a11a699/src/steps/generic.rs#L62). What does `which rustup` shows on your machine? Is that a symlink or the real path?

* You can run `RUST_LOG=topgrade=debug topgrade` to see more verbose output

* Fair point about NPM. I'll just stop using yarn.

**Comment by r-darwish** [comment]
Found the problem with rustup, #124 should fix that.

**Comment by IngwiePhoenix** [comment]
Awesome! Well, Rustup is here:

```
Ingwie@Ingwies-Macbook-Pro.local /tmp $ which -a rustup
/Users/Ingwie/.cargo/bin/rustup
```

But...
```
Ingwie@Ingwies-Macbook-Pro.local /tmp $ ls /usr/local/opt/rustup-init/bin/
./           ../          rustup-init
Ingwie@Ingwies-Macbook-Pro.local /tmp $ brew info rustup-init
rustup-init: stable 1.16.0 (bottled)
The Rust toolchain installer
https://github.com/rust-lang/rustup.rs
/usr/local/Cellar/rustup-init/1.16.0 (6 files, 6.4MB) *
  Poured from bottle on 2018-12-27 at 16:38:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/rustup-init.rb
==> Dependencies
Build: rust ✘
==> Analytics
install: 1,484 (30 days), 7,441 (90 days), 23,640 (365 days)
install_on_request: 1,426 (30 days), 7,138 (90 days), 22,234 (365 days)
build_error: 0 (30 days)
```

This is where it's coming from. `rustup-init` installs Rustup into my home folder, whilst actually coming from Homebrew. Also:
```
Ingwie@Ingwies-Macbook-Pro.local /tmp $ rustup-init --help
rustup-init 1.16.0 ( )
The installer for rustup

USAGE:
    rustup-init [FLAGS] [OPTIONS]

FLAGS:
    -v, --verbose           Enable verbose output
    -y                      Disable confirmation prompt.
        --no-modify-path    Don't configure the PATH environment variable
    -h, --help              Prints help information
    -V, --version           Prints version information

OPTIONS:
        --default-host <default-host>              Choose a default host triple
        --default-toolchain <default-toolchain>    Choose a default toolchain to install
```

So the only way I can upgrade rustup is by waiting untill `rustup-init` is updated, and re-install rustup with it to obtain the newest version. THAT actually sucks... Therefore I might as well go and switch to using a non-tracked (by homebrew) rustup alltogether. But I thought it might be helpful to point this out. :)

**Comment by r-darwish** [comment]
The file in your home directory is a symbolic link `/Users/vagrant/.cargo/bin/rustup -> /usr/local/bin/rustup-init`, so I think it should upgrade itself with brew.


I'm still not sure why isn't Topgrade picking your correct `gem` binary
