### ISSUE TITLE
Distribution checking and adaptation to Linux Mint

### ISSUE THREAD

**Issue by HattDroid** [r-darwish/topgrade#142]
Hi,

Running topgrade since the very early build I wanted to adapt it to Linux Mint, which is Ubuntu based.
On Mint, topgrade has never been able to determine the distribution type, always throwing this error:
	"Error detecting current distribution: Unknown Linux Distribution"

Looking at the source code at "src/steps/os/linux.rs" and the "/etc/os-release" of the Mint distribution, I've found that:
	- Either os-release is wrong and should contain "Ubuntu" with a capital 'U', as currently checked in topgrade (a quick search of os-release seems to show it's not the case)
	- Or topgrade should be checking the distribution in case-insensitive way.

Ideally, for distribution-detection, only one field of the '/etc/os-release/' file should be checked by topgrade, not "grepping" on the full file content.
This is in order to avoid side-effects that could happen with common words like 'mint' or 'void', which could be used in other distribution names.
The most-likely correct field to check seems to be the ID_LIKE field.

Please let me know what you think.
The case insensitive patch could be made very quickly if you decide to go this way.

Thanks.

**Comment by r-darwish** [comment]
Yeah, this linux module was made in the most quick and dirty possible way. It deserves a refactor. However, in the meantime I'll classify Mint as Ubuntu.

**Comment by HattDroid** [comment]
Thanks for the quick answer. Couldn't get the updates through crates.io, but just downloaded the binary and works well. Thanks. 👍

**Comment by HattDroid** [comment]
Hi mate,

Quick info, topgrade self-updated to 1.11.0 here and it broke the compatibility with Mint.
Dirty modifiying the os-release to "Ubuntu" or "ubuntu" as before, doesn't do the trick anymore by the way.

**Comment by r-darwish** [comment]
I just released 1.11.1 which should not have this issue

**Comment by HattDroid** [comment]
Great it works, thanks for the very quick response :+1:
