### ISSUE TITLE
yay not runned on archlinux

### ISSUE THREAD

**Issue by cambid** [r-darwish/topgrade#143]
python on archlinux is /bin/python, because the current package filesystem-2018.12-2 contains a softlink from /bin to /usr/bin and topgrade doesn't run yay because it's checking for /usr/bin/python.
```
% topgrade 

―― System update ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Python detected at "/bin/python", which is probably not the system Python.
It's dangerous to run yay since Python based AUR packages will be installed in the wrong location

Retry? [y/N] % 
```

**Comment by r-darwish** [comment]
Thanks for reporting. 

https://github.com/r-darwish/topgrade/tree/python-arch

Can you check if this branch fixes the issue?

**Comment by cambid** [comment]
Thanks for your quickfeedback.
The branch does change the behaviour:
```
―― System update ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Python detected at "/usr/bin/python3.7", which is probably not the system Python.
It's dangerous to run yay since Python based AUR packages will be installed in the wrong location

Retry? [y/N] %  
```
The softlink is linking /bin/python to /usr/bin/python and from /usr/bin/python to /usr/bin/python3 and from there to /usr/bin/python3.7 finally.
Manually switching line 120 in src/steps/os/linux.rs to python3.7 fixes the problem on arch but feels like a clumsy hack.

**Comment by r-darwish** [comment]
Yeah, it will just break on the next major Python version. I'll need to think of a proper fix.

**Comment by cambid** [comment]
After a hard debug session I've nailed the path /bin down to a default setup of the xdm login manager and after a switch from xdm to lxdm topgrade runs succesfully and without further problems.

Thank you for pointing me in the right direction and please take my apologize for the trouble.
