### ISSUE TITLE
Vundle needs a clearer output

### ISSUE THREAD

**Issue by JasonIamAUnixAdmin** [r-darwish/topgrade#144]
When running I get the following output:

```―― Vim (Vundle) ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
not found in 'runtimepath': "plugin/**/*.vim"
Reading viminfo file "/Users/jasonschuster/.viminfo" info oldfiles
not found in 'runtimepath': "autoload/vimtex.vim"
not found in 'runtimepath': "ftplugin/vundle.vim ftplugin/vundle_*.vim ftplugin/vundle/*.vim"
not found in 'runtimepath': "indent/vundle.vim"
not found in 'runtimepath': "syntax/vundle.vim syntax/vundle/*.vim"P'P'P'P'P'P'P'P'P'P'P'P'P'PhD
not found in 'runtimepath': "Vundle.vim/plugin/*.vim"```

It is unclear if this is an error and if so what it is coming from.

**Comment by r-darwish** [comment]
I agree. I'm not much of a vim wizard. If anyone has a suggestion about how to improve it then I'll be happy to hear.

**Comment by r-darwish** [comment]
@derphilipp - I know that you use Dein but perhaps you can suggest a solution for this?

**Comment by derphilipp** [comment]
@JasonIamAUnixAdmin which verison of vim is this running? do you have also have nvim installed on your system?

**Comment by r-darwish** [comment]
I'm having the same output in both Vim and Neovim

**Comment by derphilipp** [comment]
And also if you run it inside nvim/vim yourself - or only if you trigger it via topgrade?

**Comment by JasonIamAUnixAdmin** [comment]
> @JasonIamAUnixAdmin which version of vim is this running? do you have also have nvim installed on your system?
> And also if you run it inside nvim/vim yourself - or only if you trigger it via topgrade?

no nvim, only current `mvim` from `brew`. 
```VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950```

The messages only show when running from topgrade not from inside via `PluginUpgrade` or the like

**Comment by r-darwish** [comment]
Actually I use Plug and I get this:

```
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
not found in 'runtimepath': "plugin/**/*.vim"
Reading ShaDa file "/home/roey/.local/share/nvim/shada/main.shada" info marks oldfiles
not found in 'runtimepath': "autoload/vimtex.vim"
Downloading the latest version of vim-plugvim-plug is already up-to-date
not found in 'runtimepath': "ftplugin/vim-plug.vim ftplugin/vim-plug_*.vim ftplugin/vim-plug/*.vim"
not found in 'runtimepath': "indent/vim-plug.vim"
not found in 'runtimepath': "syntax/vim-plug.vim syntax/vim-plug/*.vim"Press 'R' to retry. Press 'D' to see the updated changes.
Writing ShaDa file "/home/roey/.local/share/nvim/shada/main.shada"
```

It only happens when Topgrade runs Vim in script mode. I suppose that these plugins use stderr for debug logs and it's not visible when Vim is opened as an interactive process. I could swallow stderr completely but I'm afraid that I'll miss actual errors

**Comment by derphilipp** [comment]
Idea: Only print stderr if an error occurs, otherwise filter it out.
Although then the order of stdout/stderr is mixed up

**Comment by JasonIamAUnixAdmin** [comment]
Thank you :D
