### ISSUE TITLE
upgrading non-default cargo installs

### ISSUE THREAD

**Issue by jasikpark** [r-darwish/topgrade#145]
If I have my default rust toolchain set to stable and I run `rustup run nightly cargo install [crate]` and then run topgrade later, will topgrade update my non-default installs or no?

I'll edit or reply to this with more info if I actually see whether it updates or not.

**Comment by r-darwish** [comment]
I think it should work. I run [cargo-update](https://github.com/nabijaczleweli/cargo-update) which should be able to handle that.
