### ISSUE TITLE
Do not run vim if it is actually nvim

### ISSUE THREAD

**Issue by derphilipp** [r-darwish/topgrade#152]
If running the updates for the vim-familiy (vim, nvim), one should check if:
The command 'vim' is actually running 'nvim'.
As different distributions create links and/or wrappers around it, I would suggest checking for 
`vim --version`. If that contains/starts with `NVIM` (Example: `NVIM v0.3.4`), skip the vim update process and continue with the next one (nvim).

**Comment by r-darwish** [comment]
Could you name a distribution that does that so I'll be able to apply the change and check it on the distribution?

**Comment by derphilipp** [comment]
Oh, I have to abandon: It seems the vim being nvim was a bug on the machines I was working on;
 
Nontheless I often see people aliasing vim for nvim if that counts for anything. But I guess that is not an issue/reason to implement it anymore

**Comment by r-darwish** [comment]
Okay. If you have no more pending pull requests that you want to make at the moment please tell me so, so I can release a version and let everyone enjoy your contribution. Thank you!

**Comment by derphilipp** [comment]
I guess I am done for now, thank you for integrating them so super fast! 👍

**Comment by derphilipp** [comment]
Actually on dietpi distribution (based on raspbian) this is the case:

```
which vim                                                                                                                                                                                                                                                                                                                                                                    
/usr/bin/vim

file /usr/bin/vim                                                                                                                                                                                                                                                                                                                                                                     /usr/bin/vim: symbolic link to /etc/alternatives/vim

file /etc/alternatives/vim                                                                                                                                                                                                                                                                                                                                                            
/etc/alternatives/vim: symbolic link to /usr/bin/nvim
```

**Comment by r-darwish** [comment]
I pushed a side branch called `vim-check`. Can you tell if it's working as expected?

**Comment by derphilipp** [comment]
Looks exactly right!

...
```
―― Neovim (Dein) ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Plugins upgraded
```
...
