### ISSUE TITLE
Rustup

### ISSUE THREAD

**Issue by r-darwish** [r-darwish/topgrade#16]
I'm not sure what to do with Rustup, so I'm opening it up for discussion:

* The stable channel - It's safe to update. However, Rust versions don't release often, and when they do, people are usually aware of that, so maybe it's a bit of a waste to try to update something which doesn't update very often?

* The nightly channel - This actually updates every night, but has the potential for breaking things. I don't use nightly personally so I'm not sure what's the desired workflow for people who actually use nightly. Do such people update nightly every day, or do they only do that whenever they feel ready?

**Comment by jcgruenhage** [comment]
I'd say update stable definitely. For beta and nightly I'm less certain, but I personally would want those to be updated too.

**Comment by tversteeg** [comment]
`rustup update` should update the versions you've got installed, isn't that enough?

**Comment by tversteeg** [comment]
Oh right, sorry for misunderstanding. Personally I think it should, that's one of the scripts I manually run every time I start my computer, so it would be helpful to me.

**Comment by r-darwish** [comment]
I suppose it's okay then. People can always use rustup to install a specific version of the nightly or the stable channel. Implemented.
