### ISSUE TITLE
HTTP SSL errors

### ISSUE THREAD

**Issue by NotAFile** [r-darwish/topgrade#161]
In 2.0.0, some http requests made by topgrade seem to fail

```
info: caused by: failed to make network request
info: caused by: https://static.rust-lang.org/rustup/release-stable.toml: error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1924: (unable to get local issuer certificate)
```

This applies to the `self-upgrade`, `RubyGems` and `RustUp` steps. The latter commands work fine when not executed via `topgrade`

**Comment by r-darwish** [comment]
Could you provide some more details?

1. Which Linux distribution are you using?
2. Is this a new issue for you? Is there any older version of Topgrade which does not cause this?
3. Does it happen even if you run Topgrade with `TOPGRADE_NO_SELF_UPGRADE` environment variable set?
4. Are you using `topgrade-v2.0.0-x86_64-unknown-linux-gnu.tar.gz` or topgrade-v2.0.0-x86_64-unknown-linux-musl.tar.gz` (musl vs gnu). Does switching make any difference?

**Comment by NotAFile** [comment]
1. This is on fedora 29
2. I did not have this issue with topgrade 1.5
3. rustup and rubygems works with TOPGRADE_NO_SELF_UPGRADE
4. I am using the gnu version as this is what my computer uses. I'll try musl and report back.
