### ISSUE TITLE
Make debug option more obvious

### ISSUE THREAD

**Issue by NotAFile** [r-darwish/topgrade#162]
Since #8 you can receive debug logs with `RUST_LOG=debug`. However this isn't apparent until you start looking at the source code. As this option is very useful even for non-developers, it would be nice to have a CLI option or document the fact that this is possible.

**Comment by r-darwish** [comment]
I'll add `-v` for that

**Comment by r-darwish** [comment]
Fixed in 232c886be69146fa1246d87deae907634bb5e43b
