### ISSUE TITLE
Does not handle Void's idiosynctratic upgrade mechanism

### ISSUE THREAD

**Issue by Vaelatern** [r-darwish/topgrade#170]
Similar to topgrade itself, Void's `xbps` will attempt to upgrade itself first. Unlike topgrade, `xbps` will not try running itself again on the new xbps, but instead will proclaim the job done, requiring the user to run the command again.

There is no return code for "I was just upgraded and may not have done what you wanted."

Is there a way for topgrade to run xbps twice, to allow for this behavior? If not, that makes sense too.

**Comment by r-darwish** [comment]
Well, technically all other package managers upgrade themselves during their own run. They just don't do that as a separate step, and we never run any of them twice.

Does `xbps` have command that tells it only to update itself? If so, I can run that command first and then run the generic upgrade command.

**Comment by Vaelatern** [comment]
Not really, but you could conceive of running `xbps-install -Syu xbps` which only updates xbps and its dependencies, then `xbps-install -Syu` for everything else.

**Comment by r-darwish** [comment]
I'm closing this for now. If there's any official recommendation from void regarding the recommended upgrade method, please post it here.

**Comment by Vaelatern** [comment]
At present the best recommendation is run it twice. We are considering doing a re-exec instead, but that is not yet beyond a suggestion.
