### ISSUE TITLE
Add support for apt-fast

### ISSUE THREAD

**Issue by choman** [r-darwish/topgrade#171]
Hopefully this is a easy feature request 

apt-fast is a shellscript wrapper for apt-get and aptitude that can drastically improve apt download times by downloading packages in parallel, with multiple connections per package.

if apt-fast is installed on the system, please use apt-fast to download the system packages

BTW - nice job on topgrade

**Comment by r-darwish** [comment]
Can you check if the`apt-fast` branch that I pushed works?

**Comment by choman** [comment]
Sure, I might have some time this weekend.

**Comment by choman** [comment]
Suddenly I realize I'm not sure how to build this.  do you have some instructions? or can you provide me with a built version?
