### ISSUE TITLE
Flag to automatically use "y" for prompts on updates?

### ISSUE THREAD

**Issue by choman** [r-darwish/topgrade#172]
subject says all 

Again love topgrade

**Comment by Serrvosky** [comment]
Whats the state of this feature? It will be implemented? That would be a great improvement to topgrade.

**Comment by r-darwish** [comment]
It will be. I just don't have as much time as I used to for Topgrade nowadays, but it's in my todo list.

**Comment by Serrvosky** [comment]
I don't know if it helps but on some linux distribuitions like Ubuntu, Mint it works if I run topgrade like this: 
`echo "Y" | topgrade`

**Comment by strangelittlemonkey** [comment]
Can you not just

```yes | topgrade```

**Comment by Serrvosky** [comment]
@strangelittlemonkey it works too
