### ISSUE TITLE
composer update not executing

### ISSUE THREAD

**Issue by DeftNerd** [r-darwish/topgrade#173]
I'm not sure if it's my shell (I've used Zsh and Bash) but when I execute the composer program with the arguments in generic.rs, I receive multiple lines.

```
adam@omen:~$ composer global config --absolute home
Changed current directory to /home/adam/.composer
/home/adam/.composer
```
I believe your function to determine if composer is available is checking for the existence of a composer configuration directory that's a subdirectory of the current users home, but it's not taking into account the first line of the output

What you might want to do is add the `--quiet` parameter. 

```
adam@omen:~$ composer global config --absolute --quiet home
/home/adam/.composer
adam@omen:~$ 
```

That should result in a single line of output that you can more easily parse.

**Comment by DeftNerd** [comment]
Oh, additionally, if you determine where composer is installed and then it's ownership, you can see if the current user has write permission to it. If so, you can also run `composer self-update` to update the binary to the latest version

```
root@omen:~$ which composer
/usr/sbin/composer
root@omen:~$ stat -c %U /usr/sbin/composer
root
root@omen:~$ stat -c %A /usr/sbin/composer
-rwxr-xr-x
root@omen:~$ composer self-update
Updating to version 1.8.6 (stable channel).
   Downloading (100%)         
Use composer self-update --rollback to return to version 1.8.5
```

**Comment by r-darwish** [comment]
I'm okay with running its `self-update` method only if it's installed in `~/.local/bin`.

I'll also add the `--quiet` parameter.

The documentation seems to suggest that when putting `composer` in `PATH` it should be called `composer`. `composer.phar` seems to be only executed when executing `php composer.phar` first.

**Comment by eltonlika** [comment]
I think you should also trim the `composer global config --absolute home ` output because when you map it to a PathBuf and then check if the path exists, it fails.
