### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by DeftNerd** [r-darwish/topgrade#174]
Sadly, youtube-dl is one of those programs that self-updates and isn't often tracked in package managers. If you do decide to add these to the routines, here is a quick way to do it. 

Oh, and take note that you might need to surround the `%U` and `%A` with quotes. Zsh will try to process unquoted strings starting with a `%` because it thinks they're variables or something.  I don't know if Rust's command interpreter uses the current running shell or spawns a more generic `sh`. 

```
root@omen:~# which youtube-dl
/usr/bin/youtube-dl
root@omen:~# stat -c "%U" /usr/bin/youtube-dl
root
root@omen:~# stat -c "%A" /usr/bin/youtube-dl
-rwxrwxr-x
root@omen:~# youtube-dl --version
2019.04.16
root@omen:~# youtube-dl --update
Updating to version 2019.06.21 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
root@omen:~# youtube-dl --version
2019.06.21
root@omen:~#
```

**Comment by r-darwish** [comment]
I use `youtube-dl` on multiple platforms, including Windows, and in each one of them I installed it using either the system package manager or pipx. Running youtube-dl's update method as root is both a security risk and a possible conflict with the package manager that installed it.

**Comment by KlfJoat** [comment]
I handle this by using a custom update line within `topgrade`.  

If you install `youtube-dl` from a package manager or pip, you should update it that way.  

But if you installed it direct from the repo like me, you can have `topgrade` run `sudo youtube-dl --update` for you.

**Comment by MCOfficer** [comment]
Apologies for the bump, but youtube-dl intends for this flag to be used, and even handles "uneducated" people. If you installed youtube-dl via some package manager and run `youtube-dl -U`, it will fail:

```
❯ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
```

So one could reasonably call `youtube-dl -U` every time, and treat every failure *except* this message as an actual failure.

**Comment by r-darwish** [comment]
@MCOfficer is there any command that I can run and check its output to figure out whether youtube-dl was installed using a package manager? I don't want to bother users with the message every time Topgrade runs.

**Comment by MCOfficer** [comment]
> @MCOfficer is there any command that I can run and check its output to figure out whether youtube-dl was installed using a package manager? I don't want to bother users with the message every time Topgrade runs.

I checked the documentation & issues, and it seems like there's no way to determine that without trying it :confused:. So the best you can do is filter that output so the user doesn't see it.

---

Here's an overview over all potential outcomes you might have to handle, tested on linux.

Successful update:
```
❯ ./youtube-dl -U    
Updating to version 2021.04.26 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
```

Already uptodate:
```
❯ ./youtube-dl -U
youtube-dl is up-to-date (2021.04.26)
```

Not installed manually (NOOP):
```
❯ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
```

Insufficient permissions:
```
❯ ./youtube-dl -U
Updating to version 2021.04.26 ...
ERROR: no write permissions on /home/florian-semmler/youtube-dl
```

Note that all of these, even the permission error, produce exit code 0, so the only way to distinguish them is to match the outputs. It also doesn't seem possible to output in a machine readable format.

Bottom line: Yikes.

**Comment by MCOfficer** [comment]
> @MCOfficer is there any command that I can run and check its output to figure out whether youtube-dl was installed using a package manager? I don't want to bother users with the message every time Topgrade runs.

I checked the documentation & issues, and it seems like there's no way to determine that without trying it :confused:. So the best you can do is filter that output so the user doesn't see it.

---

Here's an overview over all potential outcomes you might have to handle, tested on linux.

Successful update:
```
❯ ./youtube-dl -U    
Updating to version 2021.04.26 ...
Updated youtube-dl. Restart youtube-dl to use the new version.
```

Already uptodate:
```
❯ ./youtube-dl -U
youtube-dl is up-to-date (2021.04.26)
```

Not installed manually (NOOP):
```
❯ youtube-dl -U
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
```

Insufficient permissions:
```
❯ ./youtube-dl -U
Updating to version 2021.04.26 ...
ERROR: no write permissions on /home/mco/youtube-dl
```

Note that all of these, even the permission error, produce exit code 0, so the only way to distinguish them is to match the outputs. It also doesn't seem possible to output in a machine readable format.

Bottom line: Yikes.

**Comment by r-darwish** [comment]
Opened https://github.com/ytdl-org/youtube-dl/issues/28892
