### ISSUE TITLE
vim-plug verbosity?

### ISSUE THREAD

**Issue by kflak** [r-darwish/topgrade#178]
Thanks for a wonderful tool! The only thing I'm missing right now is some kind of output from the nvim part of the update process. At the moment all I get is ``Neovim (Plug)``, a blinking cursor for a while and ``Plugins upgraded``. While I'm reasonably certain that stuff is happening under the hood, I'd love to get some input on which plugins are being updatet and which ones aren't. Is this possible in the current configuration? 
Running this on Arch Linux and nvim.

**Comment by r-darwish** [comment]
See #144. We used to print the output but it seemed like when running vim script mode the only output you get is unusable debug strings, so we silenced the output completely.

**Comment by kflak** [comment]
Ah, that makes some kind of sense. I wouldn't dear to mess around too much with the innards of nvim's plugins and their i/o setup, so I can settle for this. Just good to know that there is nothing fishy going on with my topgrade :-)
