### ISSUE TITLE
Running Topgrade On Jubuntu 19.04

### ISSUE THREAD

**Issue by 2635599** [r-darwish/topgrade#181]
i followed the instructions to the letter for installing topgrade from the below linked tutorial and i still cannot run it. when i launch konsole and enter topgrade i get the following. "topgrade: command not found". now i know i'm not running debian, but ubuntu thus kubuntu is based off debian. is there any way to get it to work? thanks

jubuntu 19.04 64 bit, kernel 5.1.16

https://www.maketecheasier.com/topgrade-easily-upgrade-linux-system/

**Comment by r-darwish** [comment]
I did not write this article and I am not responsible for its content. Please stop opening issues about it.

**Comment by 2635599** [comment]
open my thread NOW. you had no business closing a legitimate request for help. now that said do not ever again make it sound like i created multiple threads about this issue when you and i both know i only created this one thread. now as for the article / tutorial i never said nor implied that you wrote.  all i wanted is help getting topgrade up and running on kubuntu.
