### ISSUE TITLE
Allow all command-line options to be configured in config file

### ISSUE THREAD

**Issue by zzamboni** [r-darwish/topgrade#188]
First of all, thank you for your work on topgrade! It's an incredibly useful tool.

I have one request: it would be nice to allow configuring  all command-line options from the config file. As far as I can tell, at the moment `disable` is the only one that can be specified both in the config file or in  the command line. It would be useful  to allow all others as well, this would make it easier to configure the default behavior of  the tool (e.g. with `tmux`, `no-retry`, `keep`, etc.)

Thanks!

**Comment by idanski** [comment]
I'll take a shot adding all command line options to configuration.
let's see that I don't miss any feature:

- [ ] --tmux
- [ ] --yes
- [ ] --only
- [ ] --no-retry
- [ ] --verbose
- [ ] --cleanup

I'll start working on this soon, let me know if I'm missing anything.

**Comment by idanski** [comment]
Also, I imagine the command line get precedent over the config file?

**Comment by r-darwish** [comment]
> Also, I imagine the command line get precedent over the config file?

Yup

**Comment by r-darwish** [comment]
Fixed in 43f0b753977e65a0f59df54d4aa04c584206dab6
