### ISSUE TITLE
Automatic use of git stash for modified repositories & improved private repo handling

### ISSUE THREAD

**Issue by fkarg** [r-darwish/topgrade#193]
Awesome tool!

Does not really fit in with my workflow for two reasons:
- I have a lot of private repositories (from different Servers with different users, ...)
- I tend to have some modified files in my repositories, for which I still wish to pull

This means the following two things: improving the asking for credentials for private repositories would be awesome. Currently it more or less directly fails, since so much output is produced so that it directly takes it as input as a username or password, and second, it fails to upgrade repositories with modified content. I have written myself a small script with the following commands in that order: ` git fetch; git stash; git pull --rebase --all; git stash pop; ...`.

In this case, you could even make it dependent upon the earlier stashing (if it was necessary) if you `pop` the stash or not. (As this would also pop the stash if no changes were stashed, but some changes have been stashed before.) This is why your awesome (!) feature for git repositories was sadly unusable for me. I tried modifying it myself but got confused about tokio and how to exactly fetch or stash now.

Anyways, thanks!

**Comment by r-darwish** [comment]
As for private repositories, I recommend that you configure git to store you credentials. If you use HTTPS then look into [this](https://git-scm.com/docs/git-credential-store). If you're using SSH then configure an SSH agent.

As for auto stashing - we actually did that for a while but decided to revert it in 5e51f94 because we feared it might break people's work, so we went on the save side. I can put a configuration variable that enables autostashing, but it will be false by default.

**Comment by fkarg** [comment]
Hey, thanks for the reply and sorry for the confusion, this was not exactly what I meant. My own repositories are all using ssh. But I have a lot of (private) repositories from different servers, for which I didn't bother setting up ssh at the time. Well, maybe I should just do that. Anyways, I'd rather like to skip them than to try to upgrade them (since I'd have to enter several different credentials, even if it's only once with caching, I set that up some time ago).

The most convenient would probably be an option in the config file. I'm not sure how easy it is on detecting if a repository is private. After detecting, you could then either skip them altogether (I'd be fine with that) or ask me for the private repository credentials at the end, all at once.

Thanks!

(I'm thinking about implementing this, but don't have as much free time as I'd like right now - who could I ask for information when trying to do this?)

**Comment by fkarg** [comment]
Thanks for information regarding auto-stashing! Alright, I see your point. Still, I'd like that option, since this is my current workflow. I'm absolutely fine with it being false by default.

Thank you very much!
