### ISSUE TITLE
don't change window title

### ISSUE THREAD

**Issue by treeshateorcs** [r-darwish/topgrade#194]
or at least let us configure it. or at least set it back to what it was before running topgrade

**Comment by r-darwish** [comment]
I don't know of any API to retrieve the current terminal title, so I cannot restore it. I set my shell to automatically set the title, so the title is restored once Topgrade exists. I suggest that you do the same, but I will add a configuraiton to disable this feature.

**Comment by treeshateorcs** [comment]
thanks! much appreciated
