### ISSUE TITLE
Update system & users from "root"

### ISSUE THREAD

**Issue by igor-petruk** [r-darwish/topgrade#196]
I have an idea of a pretty cool feature. It would be cool to be able to put it under "root" cron, when first it attemps to update a system, unattended. Then it downgrades privileges to the selected number of users and attempts to update package managers in their $HOME (e.g. Vundle).

It is very easy for a user to add a one-liner to write to produce an error file and show it on i3wm/awesome/<other-wm> panel in case update failed at certain level

**Comment by r-darwish** [comment]
As for unattended upgrades, we have #172. I really don't recommend running Topgrade as root as it wasn't designed for that. It may run NPM and all sort of stuff as root, potentially harming your system.

Topgrade was design to be ran as a user with sudo permissions. It only runs sudo when it has to.

Once #172 is implemented you can use the user's crontab (or systemd-timer) to run Topgrade periodically unattended.
