### ISSUE TITLE
Disable rustup

### ISSUE THREAD

**Issue by tage64** [r-darwish/topgrade#200]
Hi,

I've just started to use topgrade and I see that it is a very useful tool which saves much time and helps me to upgrade things which I even didn't know about.

How ever, I've installed nightly rust via rustup, and I don't want to download a new version of nightly rust every day, it just takes too much time. So, I wonder if there is a way to disable the upgrade of rust. I'd rather handle my rust tool chains myself.

Best regards,
Tage

**Comment by r-darwish** [comment]
I feel you. Updating nightly is a pain. I've added flags to disable rustup and cargo, but I think that a more proper solution would be that Topgrade won't upgrade nightly by default

**Comment by tversteeg** [comment]
I can see why it annoys someone but I kind of like Topgrade upgrading nightly every day..

**Comment by r-darwish** [comment]
I'll make it configurable. The question is what is the sensible default

**Comment by tversteeg** [comment]
Maybe when there's a minor or patch version update of Rust instead of daily?
