### ISSUE TITLE
Self-update fails when topgrade installed as root and not run as root

### ISSUE THREAD

**Issue by KlfJoat** [r-darwish/topgrade#203]
```
$ uname -a 
Linux ruatha 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Steps to reproduce**
1) Download pre-compiled `topgrade` 2.7.1 from GitHub releases (needs to be at least one version back for the auto-upgrade to attempt).
```
$ topgrade --version
Topgrade 2.7.1
```
2) Install it to `/usr/local/bin/topgrade` as root, because I am putting it there as a system utility and I don't want any other users to accidentally delete it.
```
$ sudo cp ~/Downloads/topgrade /usr/local/bin/topgrade
Executing sudo -- bash -x -v -c "cp" '/home/klfjoat/Downloads/topgrade' '/usr/local/bin/topgrade'
"cp" '/home/klfjoat/Downloads/topgrade' '/usr/local/bin/topgrade'
+ cp /home/klfjoat/Downloads/topgrade /usr/local/bin/topgrade
$ ll /usr/local/bin/topgrade 
-rwxr-xr-x 1 root root 9.6M Aug 21 11:03 /usr/local/bin/topgrade*
```
3) Run topgrade as a user.
```
$ topgrade

―― 11:04:09 - Self update ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Self update error: Self-update failure
Caused by: IoError: Permission denied (os error 13)
```

**Expected result**
`topgrade` updates itself automatically, elevating its privs with `sudo`/`pkexec` as needed to perform the update.  Like it does with all other commands.  

**Impact**
Obviously, you've said that running `topgrade` as root is bad.  But it also prevents my `git` repo pulls from working.

**Comment by r-darwish** [comment]
The precompiled binaries contain the self upgrade feature and are intended to be placed in a the user's home directory. If you don't wish to have this feature then use `cargo install` to install Topgrade

**Comment by KlfJoat** [comment]
Then might I suggest that you mention in the docs that the self-upgrade use case is for user mode, and that `cargo install` is the preferred systemwide upgrade use case?

**Comment by r-darwish** [comment]
Good idea
