### ISSUE TITLE
Use pretend mode of commands when it exists

### ISSUE THREAD

**Issue by Keruspe** [r-darwish/topgrade#207]
Currently, in dry mode, we would basically run `echo foo` and in wet mode we would run `foo`.

Let's say `foo` supports some `--pretend` which makes it only print stuff and actually execute nothing, we should probably use `foo --pretend` instead of `echo foo`.

If now, `foo` only prints by default, and actually performs something only when `--execute` is present, we should use `foo` in dry mode and `foo --execute` in wet mode.

Maybe, in `RunType`, we could have some `pretendArg` and `executeArg` as `Option<String>`, then:

for dry mode:
- if `pretendArg` is `Some`, use it
- if `executeArg` is `Some`, run the raw command
- otherwise, run `echo command` as we do now

for wet mode:
- if `executeArg` is `Some`, use it
- otherwise, run the raw command

What do you think?
I can work on this if you think it's a good idea. At least the package manager on exherbo is pretend-only by default, and has an `--execute` flag. I'm pretty sure I recall the one from gentoo having a `--pretend` flag. Other might have something like that too.

For this to be really usefull, wrt package-manager, we might want to add some new feature such as "only sync repositories but do not update anything" which would run e.g. `apt-get update` in wet mode but `apt-get dist-upgrade` in dry mode

**Comment by r-darwish** [comment]
Sorry, but the more I think about it I realize that:
1. It wouldn't be consistent because not all commands support dry run
2. It's quite a work and I don't think it's worth it
3. `-n` is very useful for debugging Topgrade because it shows which commant is meant to be run
