### ISSUE TITLE
Support AppGet (package manager for Windows)

### ISSUE THREAD

**Issue by drrlvn** [r-darwish/topgrade#210]
https://appget.net/

**Comment by tuxiqae** [comment]
Please edit the title- "Support aptget" -> "Support AppGet"

**Comment by tuxiqae** [comment]
@drrlvn Bear in mind that the name is AppGet and not AptGet :P

**Comment by drrlvn** [comment]
@tuxiqae Whoops, you're right, they got me confused. Fixed.

**Comment by tuxiqae** [comment]
Well, it is 1AM here :sleepy:

**Comment by r-darwish** [comment]
Is there any Topgrade user who actually uses AppGet?
