### ISSUE TITLE
feature request: pull new docker images

### ISSUE THREAD

**Issue by RatanRSur** [r-darwish/topgrade#214]
Love the idea! I too have a script that intends to do this all for me so it's definitely a itch that needs scratching.

One thing my script does is pull new docker containers:
```
# do docker updates all in separate windows
for image in `docker images | tail -n +2 | cut -d ' ' -f 1 | sort | uniq | rg -v "<none>"`; do
    tmux split-window -d "docker pull $image; $update_layout"
    $update_layout
done
```
with one tmux pane for each update.

Perhaps topgrade could have an option that could pull the new containers? If you'd like me to open a PR, let me know and I'd be happy to.

**Comment by r-darwish** [comment]
Pulling every docker image in the system is probably undesired for many people. If you wish to pull some specific repositories on your system you can add a custom command to the configuration.
