### ISSUE TITLE
Ability to disable yay's --devel flag

### ISSUE THREAD

**Issue by tuxiqae** [r-darwish/topgrade#220]
Hi @r-darwish,
I would love it if it'd be possible to disable yay's --devel flag using both the CLI and the config file.

P.S. why would I even want to use --devel on daily basis as a regular user?

**Comment by tuxiqae** [comment]
I would even advise removing it as a default altogether - I don't see the point in using code that was only committed to my OS.

**Comment by sagis-tikal** [comment]
I've yet to try it, but as I understand the changes from reading the code - it seems like it'll not choose --devel whenever a yay flag is being set, even if the flag wasn't especially --nodevel.

```rust
#[cfg(target_os = "linux")]
    pub fn yay_arguments(&self) -> &str {
        match &self.config_file.yay_arguments {
            Some(args) => args.as_str(),
            None => "--devel",
```

**Comment by sagis-tikal** [comment]
That's my alt account btw, not in front of my personal computer 🤷‍♂️

**Comment by sagis-tikal** [comment]
I'll tell you what - I strongly oppose to how it's implemented.

Firstly, I don't think that the --devel flag should be enabled by default. I Arch but I can't even be assured that those commits were tested properly - they were just pushed to the repositories.

Secondly, if you still think that it should be implemented by default, I think it should be an true/false toggle switch in the config file - I don't think people should use --nodevel or something when they want to disable a feature that (to me) doesn't even make sense.

**Comment by r-darwish** [comment]
We'll keep `--devel` as the default. I don't see any risk in enabling it. All this flag says to yay is to upgrade AUR dependencies that were used to build other dependencies. I don't see a reason not to update these.

As for the flag itself, I prefer to give the users something generic other then dozens of true/false flags to disable every bit of feature. You don't have to set this flag to `--nodevel`. You can use set it as an empty string as `--devel` will be used when this flag isn't specified at all.

**Comment by sagis-tikal** [comment]
I might've misunderstood the purpose of the flag.
Thanks for clarifying, sorry for wasting your time :)
