### ISSUE TITLE
Feature: run tlmgr to update texlive packages

### ISSUE THREAD

**Issue by levbishop** [r-darwish/topgrade#223]
tlmgr is the texlive manager `tlmgr update --self --all` should be the command to update everything. For some configurations (eg, MacTeX) may need to run with sudo.

**Comment by r-darwish** [comment]
Please check the `tlmgr` branch.

**Comment by levbishop** [comment]
Thanks. With the `tlmgr` branch topgrade successfully finds the `tlmgr` utility and runs it, but then tlmgr fails due to not running with admin privilege. My config is homebrew-installed MacTeX, but my understanding based on [texlive docs](https://www.tug.org/texlive/tlmgr.html) is that installed-as-root is typical for all MacTeX installs. If I were running tlmgr manually I would use sudo:
```
./topgrade --only tlmgr                                                                                

―― 15:56:23 - TeX Live package manager ―――――――――――――――――――――――――――――――――――――――――
tlmgr: package repository http://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet (verified)
You don't have permission to change the installation in any way,
specifically, the directory /usr/local/texlive/2019/tlpkg/ is not writable.
Please run this program as administrator, or contact your local admin.
tlmgr: An error has occurred. See above messages. Exiting.

Retry? (y)es/(N)o/(s)hell

―― 15:56:30 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
tlmgr: FAILED
```

**Comment by r-darwish** [comment]
Is there any way to detect whether sudo should be used or not?

**Comment by levbishop** [comment]
Seems like the check `tlmgr` does in order to throw the error is to see if `$(kpsewhich -var-value=SELFAUTOPARENT)/tlpkg` is writable

**Comment by r-darwish** [comment]
@levbishop please check again

**Comment by levbishop** [comment]
It didn't work so I tried to fix it (I don't know any rust) and made a PR #276 against your tlmgr branch. It worked for me with those changes....

**Comment by r-darwish** [comment]
Seems good. I'll just fix it in Windows and merge the original request.
