### ISSUE TITLE
Upgrading oh-my-zsh stopped working

### ISSUE THREAD

**Issue by Osveron** [r-darwish/topgrade#224]
I have upgraded to the topgrade to 3.0 and noticed that oh-my-zsh is no longer automatically upgraded. After some investigation it looks like topgrade is looking for upgrade_oh_my_zsh binary in PATH. I couldn't find that binary on my system, instead I found upgrade_oh_my_zsh function defined here:
https://github.com/robbyrussell/oh-my-zsh/blob/fd4571d1b02ac68833a5b5c166395434723b9128/lib/functions.zsh#L9

Running which upgrade_oh_my_zsh in terminal outputs:
upgrade_oh_my_zsh () {
	env ZSH=$ZSH sh $ZSH/tools/upgrade.sh
}
So probably running $ZSH/tools/upgrade.sh will be the simplest solution.

**Comment by r-darwish** [comment]
Since I don't have oh-my-zsh, would you be able to test the fix once I push it to a side branch?

**Comment by Osveron** [comment]
Yes, no problem. I have already cloned the repro when investigating the issue. If I had more time I would probably just sent PR.

**Comment by r-darwish** [comment]
@Osveron I pushed a branch called `fix-oh-my-zsh`

**Comment by Osveron** [comment]
I have checked it and upgrading works for me.

**Comment by Osveron** [comment]
I have looked at your commit, and I see that you have added zshrc function. I don't know what ```ZDOTDIR``` is for, I don't have it set on my system, but maybe you should be using this function in other places where path to .zshrc is currently hard-coded to:
```base_dirs.home_dir().join(".zshrc")```

**Comment by Osveron** [comment]
You also search for .zshrc [here](https://github.com/r-darwish/topgrade/blob/877e1941d37f3553dce9624335037113f7493e2e/src/main.rs#L227).
