### ISSUE TITLE
`.config` doesn't always exist

### ISSUE THREAD

**Issue by mati865** [r-darwish/topgrade#238]
In fresh WSL `topgrade` fails with:
```
ERROR topgrade::config > Unable to write the example configuration file to /home/mateusz/.config/topgrade.toml: No such file or directory (os error 2)
Error: Error reading the configuration
Caused by: No such file or directory (os error 2)
```
This is caused by non existent `~/.config`, creating this directory fixes the issue but I think `topgrade` could print better error or create directory itself.

**Comment by r-darwish** [comment]
I think that the proper solution would be actually to lower the log severity so that it won't be printed by default. This is just for writing the example file in `~/.config`. I think the user should not be bothered if it doesn't work.

**Comment by mati865** [comment]
I don't have preference here.
