### ISSUE TITLE
`topgrade --edit-config` breaks on broken config

### ISSUE THREAD

**Issue by Walther** [r-darwish/topgrade#241]
Tiny bug report:

```
 topgrade --edit-config
Error: Error reading the configuration
Caused by: unexpected character found: `~` at line 3 column 3
```

1. Use `topgrade --edit-config` command to edit the config file
2. Make a configuration mistake (e.g. not quoting the path strings)
3. After this, `topgrade --edit-config` does not work, forcing the user to manually find and edit the config file

Suggestion: handle `--edit-config`  before validating or parsing the configuration file

**Comment by Walther** [comment]
Forgot to say: what an amazing piece of software <3 Thank you so much  for creating this!

**Comment by r-darwish** [comment]
> 
> 
> Forgot to say: what an amazing piece of software ❤️🦀 Thank you so much for creating this!

Thank you!
