### ISSUE TITLE
Firmware updates report failed status when no updates found

### ISSUE THREAD

**Issue by Cadair** [r-darwish/topgrade#246]
The firmware (fwupd) update step has started failing for me when there are no updates. I run arch linux. If there is any debug info I can provide please let me know.

**Comment by andrei-pavel** [comment]
Fails for me on Arch as well and I think it's because of:
```
No updatable devices
```

**Comment by r-darwish** [comment]
I don't use this tool by myself anymore so I suppose they change the behavior in recent versions. @idanski, @drrlvn - does this happen to any of you?

Can you tell the actual return value of the process by just running it? If they added a special code for "no updatable devices" then I can just treat that as success.

**Comment by andrei-pavel** [comment]
```sh
$ fwupdmgr refresh

$ fwupdmgr get-updates
No updatable devices

$ echo $?
2

$ fwupdmgr --version
client version:	1.3.2
compile-time dependency versions
	gusb:	0.3.0
	efivar:	37
daemon version:	1.3.2
```

**Comment by idanski** [comment]
@r-darwish, sorry, didn't use this tool in a year or so.. so no input from me.

**Comment by r-darwish** [comment]
So I suppose that `2` means that there are no updates. @andrei-pavel Can you check if this is documented in the man page?

**Comment by andrei-pavel** [comment]
It's not, they use code as documentation.

https://github.com/fwupd/fwupd/blob/7cb0592f72c9452d5726d92efae78e3b7e206f5b/src/fu-util.c#L1655#L1662
https://github.com/fwupd/fwupd/blob/7cb0592f72c9452d5726d92efae78e3b7e206f5b/src/fu-util.c#L1852-L1859
```
	/* no devices supported by LVFS or all are filtered */
	if (!supported) {
		g_set_error_literal (error,
				     FWUPD_ERROR,
				     FWUPD_ERROR_NOTHING_TO_DO,
				     "No updatable devices");
		return FALSE;
	}
```

https://github.com/fwupd/fwupd/blob/7cb0592f72c9452d5726d92efae78e3b7e206f5b/src/fu-util.c#L2765-L2766
```
		else if (g_error_matches (error, FWUPD_ERROR, FWUPD_ERROR_NOTHING_TO_DO))
			ret = EXIT_NOTHING_TO_DO;
```

https://github.com/fwupd/fwupd/blob/7cb0592f72c9452d5726d92efae78e3b7e206f5b/src/fu-util.c#L36
```
#define EXIT_NOTHING_TO_DO		2
```

Based on name of return code, it's safe to treat as success.

**Comment by BjoernDaase** [comment]
I am still experiencing this issue on Fedora 31 with topgrade 3.8.1. 
```
―― 20:56:43 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
Firmware metadata last refresh: 1 hour ago. Use --force to refresh again.

Retry? (y)es/(N)o/(s)hell 

―― 20:56:46 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
System update: OK
oh-my-zsh: OK
pipx: OK
tlmgr: OK
NPM: OK
yarn: OK
Flatpak: OK
snap: OK
Firmware upgrades: FAILED
```
Hitting <kbd>N</kbd> on the fwupd question results in a failed status.

**Comment by BjoernDaase** [comment]
@r-darwish What is the exact help you are looking for here?

**Comment by r-darwish** [comment]
I'm not using this fwupd so I'll need someone who can tell what change needs to be done in Topgrade and also test that change

**Comment by BjoernDaase** [comment]
So what I can tell you is, that `fwupd` returns exit status code 2 when there are no updates, see  
```
➜  ~ fwupdmgr refresh
Firmware metadata last refresh: 13 hours ago. Use --force to refresh again.
➜  ~ echo $?
2
```

And if you have a branch that can be tested, I am willing to compile (if you give the how-to instructions) and test it.

**Comment by r-darwish** [comment]
[We already treat 2 as success](https://github.com/r-darwish/topgrade/blob/4000ef39f6d1275fcb741c80e6d5c64e5a915ae1/src/steps/os/linux.rs#L410)

**Comment by BjoernDaase** [comment]
Hmm, that is interesting so it should work but for some reason it does not...

**Comment by andrei-pavel** [comment]
#322 

Return code 2 was treated as success for `get-updates`, but not for `refresh`.

**Comment by r-darwish** [comment]
Thanks @andrei-pavel. @BjoernDaase can you please test this change?

**Comment by BjoernDaase** [comment]
Sure. Can someone provide build instructions?

**Comment by andrei-pavel** [comment]
Tested and it works.
```
―― 11:26:10 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
Firmware metadata last refresh: 47 minutes ago. Use --force to refresh again.
No updatable devices

―― 11:26:10 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Firmware upgrades: OK
```

![arch](https://user-images.githubusercontent.com/6838492/74602394-a8855d00-50b0-11ea-92e3-083715546f5d.png)

`fwupdmgr` version:
```
client version:	1.3.8
compile-time dependency versions
	gusb:	0.3.3
	efivar:	37
daemon version:	1.3.8
```

Instructions:
```
git clone https://github.com/andrei-pavel/togprade
cd topgrade
cargo build
./target/debug/topgrade --only firmware
```

**Comment by BjoernDaase** [comment]
Can also confirm that it works :+1:
