### ISSUE TITLE
Are these amendments possible?

### ISSUE THREAD

**Issue by andrei-pavel** [r-darwish/topgrade#247]
Hello,

Thank you, great utility! :+1: 

I use it everyday alongside a few scripts since it doesn't do everything I want, but I would like to also use it occasionaly in some cases and I explain below. So here is the unfiltered list of things I would like it to do. I can provide pull requests for any of these. Let me know what you think.

- I would like to `git pull` on root directory `/`. This would normally be added to `git_repos` in configuration. However, this always fails on other users other than root, because `/` is under root ownership. So then, add the `/` only to root's `git_repos`, right? But I have all `~/.config/topgrade.toml` under a single git repository which is a rather frequent scenario. And I don't want my topgrade to fail because then I get accustomed to errors and I don't fix them anymore. I don't know what to do here, maybe an extra command is the way to go after all. A couple of solutions here would be letting the user tie the git repo to a user or, my preference - auto-discovering user ownership.
- I run Arch with yay and I run my update my system with `yay -Syyuu`. Would you be willing to change this?
From pacman's manual:
```
Passing two --refresh or -y flags will force a
           refresh of all package databases, even if they appear to be up-to-date.
```
About `-u`:
```
Pass this option twice to enable package downgrades; in this case,
           pacman will select sync packages whose versions do not match with the
           local versions. This can be useful when the user switches from a testing
           repository to a stable one.
```
- Run `PlugUpgrade | PlugClean | PlugUpdate` for vim plug instead of `PlugUpgrade | PlugUpdate`
- Install packages from a list of files or, alternatively place packages that you always want installed in configuration to make sure that they are installed, also be able to take packages that are installed on the system and dump them to a file or to configuration. The idea behind this one is you like how your system is set up and you want to replicate that on other computers that you currently use or will use in the future. So you dump the packages to a file, place that file into git, than install packages from that file. It's advantageous with topgrade because you don't have to wonder what package manager to use for that particular ~packet~package that you liked. The order of tried package managers can be chosen arbitrarily once, but has to be the same every time and if one fails, you can proceed with the next. Also helps in auto-enabling features for topgrade. topgrade might be the first thing you install on your system, but you have to remember this long list of package managers or utilities like `fwupd` and `vim-plug` that updates it the way you want it.
- Support for Golang packages

**Comment by andrei-pavel** [comment]
- Running `topgrade` from a machine that contains itself in `remote_topgrades` continues endlessly. This forces a parent-child relationship between the topgrader machine and the topgraded machines. Concrete example: Having two laptops, one at home, one at work. Both are accessible via tunnels. I cannot upgrade home from work and work from home without ending `topgrade` prematurely. Solution could be comparison to the local hostname or, more acurately - comparison between hardware addresses of network interfaces.

**Comment by r-darwish** [comment]
>     * I would like to `git pull` on root directory `/`.
This is a bit esoteric setup to be generically supported by Topgrade. What I can offer is that you add a custom step in the configuration that does `cd / && sudo git pull /`
>     * I run Arch with yay and I run my update my system with `yay -Syyuu`. Would you be willing to change this?
I doesn't sound like a reasonable default, but you can achieve that using the `yay_arguments` configuration variable.
>     * Run `PlugUpgrade | PlugClean | PlugUpdate` for vim plug instead of `PlugUpgrade | PlugUpdate`
Sure. We'll do that when the `-c` is specified, just like other package managers.

>     * Install packages from a list of files or, alternatively place packages that you always want installed in configuration to make sure that they are installed, also be able to take packages that are installed on the system and dump them to a file or to configuration. The idea behind this one is you like how your system is set up and you want to replicate that on other computers that you currently use or will use in the future. So you dump the packages to a file, place that file into git, than install packages from that file. It's advantageous with topgrade because you don't have to wonder what package manager to use for that particular ~packet~package that you liked. The order of tried package managers can be chosen arbitrarily once, but has to be the same every time and if one fails, you can proceed with the next. Also helps in auto-enabling features for topgrade. topgrade might be the first thing you install on your system, but you have to remember this long list of package managers or utilities like `fwupd` and `vim-plug` that updates it the way you want it.
>
Such things are best to be left to tools like Ansible, Chef or Puppet.
 >     * Support for Golang packages
Sure. Can you tell what should be executed?

>      * Running topgrade from a machine that contains itself in remote_topgrades continues endlessly. 
I'll change it so Topgrade won't run remote upgrades if it was launched by a remote upgrade

**Comment by andrei-pavel** [comment]
> Sure. Can you tell what should be executed?

```sh
go get -u all
```
No cleanup command available

> I'll change it so Topgrade won't run remote upgrades if it was launched by a remote upgrade

Helps, but would still run twice if the local hostname was included in `remote_upgrades`.

**Comment by andrei-pavel** [comment]
- Could support for flutter be added? No clean command available. Upgrade is:
```
flutter upgrade
```

- yay also supports `-Scc`, could you prioritize yay over pacman just like for upgrade

- yay still asks for confirmation when cleaning up with `topgrade -c -y`, could you add `--noconfirm` just like for upgrade
```
Cache directory: /var/cache/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] 

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] 
removing unused sync repositories...
```
One unexpected behavior might be that `no` is automatically chosen for the first question, but user should be aware of this behavior for pacman & yay.

**Comment by r-darwish** [comment]
Aren't flutter packages installed per-repository basis?

**Comment by andrei-pavel** [comment]
Yes, with `flutter pub upgrade` which is a wrapper for `dart pub upgrade`,

`flutter upgrade` upgrades the SDK and has four channels: main, beta, alpha, stable much like rustup installs the rust compilers and tools for a selected channel with `rustup upgrade` or something.

**Comment by andrei-pavel** [comment]
topgrade -n -y
```
Dry running: /usr/bin/sudo /usr/bin/apt update
Dry running: /usr/bin/sudo /usr/bin/apt dist-upgrade
```
Should be `apt dist-upgrade -y`.

The command seems to be run before adding `-y`.
```
        command.arg(&apt).arg("dist-upgrade").check_run()?;

        if yes {
            command.arg("-y");
        }
```

**Comment by andrei-pavel** [comment]
Should I break down this thread into separate issues?

**Comment by r-darwish** [comment]
So your pull requests resolved everything here, right?

**Comment by andrei-pavel** [comment]
Yes, except for that feature which allows to install a package using whatever package manager and then stops at the first one that succeeded. I think there's value in this since you support so many package managers. I still have to research how easy you can do it with Ansible, Chef, Puppet as you say before I might do this for myself. If I do make these changes, I'll create a pull request and if you won't accept it, that's fine, I understand it's not this tool's reasoning. But this won't be happening  anytime soon so closing.

**Comment by r-darwish** [comment]
Again, thank you for all your help
