### ISSUE TITLE
Allow to disable snap

### ISSUE THREAD

**Issue by crisidev** [r-darwish/topgrade#252]
Hello, I can't find a way to disable snap update in topgrade. Is it possible?

If not, this is a feature it would really help me..

**Comment by r-darwish** [comment]
1. You can use `--disable package_manager`. That won't disable your distribution's package manager but 3rd party package managers.
2. The snap step doesn't run if `/var/snapd.socket` nor `/run/snapd.socket` exist, so I think that if you shutdown the snap service then Topgrade won't run it.

**Comment by crisidev** [comment]
Thanks! I tried `packagemanager`, I was missing the underscore!
