### ISSUE TITLE
Feature request: support Haskell stack

### ISSUE THREAD

**Issue by itkovian** [r-darwish/topgrade#254]
- Check if a new LTS is available 
- Check if a new GHC is available
- Update installed Haskell applications

**Comment by itkovian** [comment]
- I have LTS-13.16, but both 13.19 and 14.13 are available

~~~~
➜ topgrade --only stack

―― 11:17:08 - stack ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Current Stack version: 2.1.3, available download version: 2.1.3
Skipping binary upgrade, you are already running the most recent version

―― 11:17:09 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
stack: OK
~~~~

**Comment by r-darwish** [comment]
@czwinzscher can you help with this?

**Comment by czwinzscher** [comment]
> @czwinzscher can you help with this?

tbh i don't know stack very well, so i don't know how to do those things with stack.

**Comment by itkovian** [comment]
Is changing the stack.yaml file allowed in the flow topgrade normally uses, more in particular, can you change configuration files (with or without asking explicitly)?

**Comment by r-darwish** [comment]
Topgrade won't change a configuration file by its own.
