### ISSUE TITLE
Feature request: Upgrade topgrade first

### ISSUE THREAD

**Issue by tuxiqae** [r-darwish/topgrade#255]
I think it would be best to first upgrade topgrade before upgrading anything else.

**Comment by r-darwish** [comment]
[It already does that](https://github.com/r-darwish/topgrade#upgrading-topgrade)

**Comment by tuxiqae** [comment]
Well, how 'bout we make it work for Cargo and AUR (and maybe even other origins)?

**Comment by r-darwish** [comment]
That doesn't make any sense. If you install Topgrade using some package manager, it's that package manager's job to keep it up to date. This is the way Rustup works. If you wish to use the self upgrade feature of Topgrade then you will have use the binaries released in Github.

**Comment by tuxiqae** [comment]
I meant to have topgrade only upgrade itself using Rustup or what not
