### ISSUE TITLE
Support other AUR helpers

### ISSUE THREAD

**Issue by alex-700** [r-darwish/topgrade#271]
There are some other [AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers), not only yay. For example, [trizen](https://github.com/trizen/trizen) is a very popular one.

**Comment by r-darwish** [comment]
Adding support for all of them isn't something that I have the time to do, so I'll do that based on the demand. Which helper are you using?

**Comment by alex-700** [comment]
I use trizen. In fact I added ``"AUR packages upgrade (via trizen)" = "trizen -Suya --noconfirm"`` to ``topgrage.toml`` commands block. 

I think it would be great if support of another AUR helper be simple as much as possible.

**Comment by r-darwish** [comment]
I don't think that all AUR helpers have a unified interface (does trizen support `--pacman` like yay?) so I don't see any generic way to support all of them. I will add support for Trizen, though.

**Comment by alex-700** [comment]
Thanks.

I don't see generic way to support all of them neither. I mean some generic way to push information about which AUR helper topgrade should use. Something like replacing ``yay_arguments`` in config to ``aur_helper: Option<AurHelper>``, where ``AurHelper`` is enum of popular ones (yay and trizen for now) with ``args`` as field of this enum.
