### ISSUE TITLE
tmux stopped working

### ISSUE THREAD

**Issue by ImNtReal** [r-darwish/topgrade#275]
I'm running topgrade 3.5.0 on Arch. If I attempt to run with the -t option, I get an almost instant crash:
couldn't get a window index
thread 'main' panicked at 'Error launching tmux: Error { inner: stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: __libc_start_main
   7: <unknown>

exit code: 1 }', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x5650fc0879ac - <unknown>
   1:     0x5650fc03c37c - <unknown>
   2:     0x5650fc087086 - <unknown>
   3:     0x5650fc086ca0 - <unknown>
   4:     0x5650fc0863ef - <unknown>
   5:     0x5650fc085f1f - <unknown>
   6:     0x5650fc09afb6 - <unknown>
   7:     0x5650fc039819 - <unknown>
   8:     0x5650fc03c8e6 - <unknown>
   9:     0x5650fc1044c7 - <unknown>
  10:     0x5650fc0fa851 - <unknown>
  11:     0x5650fc0de075 - <unknown>
  12:     0x5650fc144f33 - <unknown>
  13:     0x5650fc0ddcd8 - <unknown>
  14:     0x7fb532bd0153 - __libc_start_main
  15:     0x5650fbfd00fe - <unknown>
  16:                0x0 - <unknown>

It does seem to open a tmux session with one window named dummy.

**Comment by ImNtReal** [comment]
tmux 3.0_a

**Comment by r-darwish** [comment]
It seems to work on tmux 3.0a on macOS. I'll try to reproduce it on Arch later today. Does it happen if you temporarily remove your tmux configuration?

**Comment by ImNtReal** [comment]
I actually haven't modified the tmux config on this box. It's vanilla. I did try specifying a tmux socket file in the topgrade config, but that didn't seem to do anything. I didn't have the time to see if that patch made it into 3.5

**Comment by r-darwish** [comment]
I tried that with Arch and it works for me, so I'm putting the "help wanted" label in the meantime.

**Comment by secretfader** [comment]
I'm also experiencing this issue on macOS Catalina (10.15.4) with tmux 3.0a:

```
RUST_BACKTRACE=full topgrade -t
couldn't get a window index
thread 'main' panicked at 'Error running topgrade in tmux: exit code: 1', src/steps/tmux.rs:92:5
stack backtrace:
   0:        0x103a58d92 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
   1:        0x10382fd9d - core::fmt::write::hd42cb3dea57bae40
   2:        0x103a584eb - std::io::Write::write_fmt::ha39f6009af02b1d2
   3:        0x103a5814a - std::panicking::default_hook::{{closure}}::h389f076017b5df43
   4:        0x103a578c6 - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
   5:        0x103a5c18a - rust_begin_unwind
   6:        0x10382da7f - core::panicking::panic_fmt::h272b9afd5b7b725a
   7:        0x103833fe5 - core::option::expect_none_failed::h2ce75daf7660504d
   8:        0x103afe657 - topgrade::steps::tmux::run_in_tmux::hb6a4ddae635aa2e3
   9:        0x103ae4e18 - topgrade::run::h9916c92008edf470
  10:        0x103adb6fe - topgrade::main::ha8f59fce3e19f2de
  11:        0x103af9716 - std::rt::lang_start::{{closure}}::h437656d0413c2d36
  12:        0x103adb517 - main
```

**Comment by r-darwish** [comment]
Can you please run `topgrade -v`?

**Comment by secretfader** [comment]
Absolutely. Thanks for the great tool, @r-darwish!

```
RUST_BACKTRACE=full topgrade -v -t
 2020-04-04T17:59:05.155Z DEBUG topgrade::config > Configuration at /Users/nicholasyoung/.config/topgrade.toml
 2020-04-04T17:59:05.155Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: None, commands: None, git_repos: None, predefined_git_repos: None, disable: None, remote_topgrades: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: None, no_retry: None, run_in_tmux: None, cleanup: None, notify_each_step: None, accept_all_windows_updates: None, only: None, composer: None }
 2020-04-04T17:59:05.155Z DEBUG topgrade         > Version: 4.3.1
 2020-04-04T17:59:05.155Z DEBUG topgrade         > OS: x86_64-apple-darwin
 2020-04-04T17:59:05.155Z DEBUG topgrade         > Args { inner: ["topgrade", "-v", "-t"] }
 2020-04-04T17:59:05.155Z DEBUG topgrade         > Binary path: Ok("/Users/nicholasyoung/.cargo/bin/topgrade")
 2020-04-04T17:59:05.155Z DEBUG topgrade         > Self Update: true
 2020-04-04T17:59:05.155Z DEBUG topgrade::utils  > Detected "/usr/local/bin/tmux" as "tmux"
couldn't get a window index
thread 'main' panicked at 'Error running topgrade in tmux: exit code: 1', src/steps/tmux.rs:92:5
stack backtrace:
   0:        0x107d45d92 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
   1:        0x107b1cd9d - core::fmt::write::hd42cb3dea57bae40
   2:        0x107d454eb - std::io::Write::write_fmt::ha39f6009af02b1d2
   3:        0x107d4514a - std::panicking::default_hook::{{closure}}::h389f076017b5df43
   4:        0x107d448c6 - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
   5:        0x107d4918a - rust_begin_unwind
   6:        0x107b1aa7f - core::panicking::panic_fmt::h272b9afd5b7b725a
   7:        0x107b20fe5 - core::option::expect_none_failed::h2ce75daf7660504d
   8:        0x107deb657 - topgrade::steps::tmux::run_in_tmux::hb6a4ddae635aa2e3
   9:        0x107dd1e18 - topgrade::run::h9916c92008edf470
  10:        0x107dc86fe - topgrade::main::ha8f59fce3e19f2de
  11:        0x107de6716 - std::rt::lang_start::{{closure}}::h437656d0413c2d36
  12:        0x107dc8517 - main
```

The same command succeeds if I omit the `-t`.

**Comment by dinkonin** [comment]
Had the same issue on arch / tmux 3.1_b. Looking at the code, topgrade is trying to create a new window with `tmux new-window -a -t "topgrade:1"` , but tmux `-a` flag auto adds a window index so topgrde tries to create a window `topgrade:1:1`.

Building with this patch fixes it for me.
```diff
--- a/src/steps/tmux.rs
+++ b/src/steps/tmux.rs
@@ -63,7 +63,7 @@ impl Tmux {
 
     fn run_in_session(&self, command: &str) -> Result<()> {
         self.build()
-            .args(&["new-window", "-a", "-t", "topgrade:1", command])
+            .args(&["new-window", "-t", "topgrade:1", command])
             .spawn()?
             .wait()?
             .check()?;
```

**Comment by secretfader** [comment]
@dinkonin That patch seems to work for me as well: [https://github.com/secretfader/topgrade/commit/c21f791d70e03574bb93f7ce240e67f98ea2b52a](https://github.com/secretfader/topgrade/commit/c21f791d70e03574bb93f7ce240e67f98ea2b52a)

**Comment by secretfader** [comment]
After some investigation, I was incorrect about @dinkonin's patch: it *does restore* the original behavior of topgrade under tmux `2.x` (had to boot an old container image and test).
