### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by r-darwish** [r-darwish/topgrade#285]

**Comment by Linux4Life531** [comment]
Has this issue been fixed or not. If bot, I might be able to look into it and try to find a solution.

**Comment by r-darwish** [comment]
It's currently implemented only in macOS

**Comment by Linux4Life531** [comment]
I will have a look into it for linux then.

**Comment by Linux4Life531** [comment]
What is the last program that runs on the Linux version of topgrade?

**Comment by r-darwish** [comment]
We should run [notify-send](https://ss64.com/bash/notify-send.html) in Linux instead of relying `notify-rust`, as the former adds a link with a native library.

**Comment by thomas-merz** [comment]
@r-darwish - Regarding your commit https://github.com/r-darwish/topgrade/commit/b0491519930029aadb1ee2f269120fd059e2b621: is or will be there also a parameter to **disable** Desktop Notifications on MacOS? 🤔
