### ISSUE TITLE
Ubuntu 19.10 cargo compile failure

### ISSUE THREAD

**Issue by denningsrogue** [r-darwish/topgrade#292]
**I have an Ubuntu 19.10 machine running the latest version of Cargo.  Attempting to install Topgrade 3.7.0 results in the following error:**

error[E0008]: cannot bind by-move into a pattern guard
  --> /home/denningsrogue/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-3.7.0/src/main.rs:45:17
   |
45 |             Err(e) if e.downcast_ref::<SkipStep>().is_some() => {
   |                 ^ moves value into pattern guard

error: aborting due to previous error

For more information about this error, try `rustc --explain E0008`.
error: failed to compile `topgrade v3.7.0`, intermediate artifacts can be found at `/tmp/cargo-installbIDZKI`

Caused by:
  Could not compile `topgrade`.

To learn more, run the command again with --verbose

**Comment by r-darwish** [comment]
Are you using the latest version of Rust?

**Comment by denningsrogue** [comment]
My apologies for wasting your time.  I had the latest of cargo but not rust.  Updated and everything works.  Thank you.  Love topgrade
