### ISSUE TITLE
python virtual env : updates possible as well?

### ISSUE THREAD

**Issue by stefangweichinger** [r-darwish/topgrade#295]
At first: thanks for the great tool! Very helpful!

I have a python virtual env at `~/.venv` and wonder if topgrade could also help me with updating my tools in there.

Normally I run something like:

```
$  source ~/.venv/bin/activate
$  pip install --upgrade ansible molecule docker docker-compose pip
```

Is there a way to let topgrade do that? As far as I understand there is no such module there?
Or maybe I just don't understand yet how to configure it.

Thanks for any info, Stefan

**Comment by r-darwish** [comment]
I suggest you use pipx instead of putting everything in a single environment. Topgrade supports pipx as well

**Comment by stefangweichinger** [comment]
Yes, I saw that. I try setting up my venv with pipx now, thanks.
molecule does not install yet ... but that is not your issue ...
