### ISSUE TITLE
TLDR update does not work

### ISSUE THREAD

**Issue by ad-si** [r-darwish/topgrade#297]
I got following log:

```txt
 2020-01-15T15:16:45.635 DEBUG topgrade             > Step "TLDR"
 2020-01-15T15:16:45.635 DEBUG topgrade::utils      > Detected "/usr/local/bin/tldr" as "tldr"

―― 15:16:45 - TLDR ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
tealdeer v1.2.0 (macOS / BSD)
```

but the cache wasn't updated.

When I run it myself the output looks different:

```sh
$ tldr --update
Successfully updated cache.
```

Any idea what's going on? 🤔

**Comment by r-darwish** [comment]
I think this releated to def4c3500c96c7761bf61e61631ae882184a7fb7. Can you please check if the issue still occurs on the master branch of Topgrade?

**Comment by ad-si** [comment]
Oh yeah, this should fix it. Thanks!
When will it be released?

**Comment by r-darwish** [comment]
I'll release a hotfix in a few days
