### ISSUE TITLE
Request: binary for armv6

### ISSUE THREAD

**Issue by Spacewalker2** [r-darwish/topgrade#299]
Hello,

first of all thanks for the great tool! I'm using a Raspberry Pi Model B Rev 2 with Arch Linux ARM (armv6h). I tried to build topgrade from AUR but I get at the end of compiling the error below.

`Could not exec the linker 'cc'`

I'm not really sure what is causing it. I checked cc and it is a symbolic link to gcc which is installed. I used the AUR package on my notebook too and there it worked just fine.

It would be very cool if you would provide a binary for armv6 too.

Thanks.

**Comment by r-darwish** [comment]
Sorry, but that's kind of a niche architecture. Even FreeBSD and Dragonfly BSD users don't have a distributed binary, and there are probably more users in these platforms than ARMv6 Linux users.

I don't even have an ARMv6 device to figure out the compilation problems.
