### ISSUE TITLE
No Man page on linux

### ISSUE THREAD

**Issue by domoaligato** [r-darwish/topgrade#301]
there is no man entry when I type man topgrade.
I would like to know what the args are. I would like to schedule topgrade to automatically run nightly on my arch linux systems and do not know where to start.
Thanks!

**Comment by r-darwish** [comment]
I never wrote an actual man page, so I'm putting the help wanted label. Contributions are welcome.

**Comment by Linux4Life531** [comment]
I am giving it a go however it may not be very good. I have put in a pull request for it. You can do whatever you like with it.

**Comment by Linux4Life531** [comment]
I am struggling to make it public, any ideas on how I could make it that way?

**Comment by Linux4Life531** [comment]
I have put in a pull request.

**Comment by Linux4Life531** [comment]
I have put in a pull request to resolve this issue.

**Comment by Linux4Life531** [comment]
I have changed the pull request to the unzipped file and I have updated the bash script. Please have a look at it. If you want to make changes, feel free to.

**Comment by domoaligato** [comment]
So there are no args? I will open a new issue for what I was looking for. Thanks for working to add a man page to be in line with all the other linux apps.

**Comment by Linux4Life531** [comment]
There are some args, I just did not know about them. I have updated the man script for you so please have a look.  The solution for your problem is to enter 0 0 * * * topgrade. I am trying to make a script to do this. Thank you.

**Comment by r-darwish** [comment]
The man pages was written thanks to @Linux4Life531.

@idanski @filalex77 @chenrui333 - can you please modify the packages that you maintain to install this manual page once the next version is out?

**Comment by domoaligato** [comment]
> 
> 
> There are some args, I just did not know about them. I have updated the man script for you so please have a look. The solution for your problem is to enter 0 0 * * * topgrade. I am trying to make a script to do this. Thank you.

what does "0 0 * * * topgrade" do? :)

**Comment by r-darwish** [comment]
@Linux4Life531 I think you're confusing this with #338

**Comment by Linux4Life531** [comment]
That would run topgrade at midnight every night as you mentioned in your  first commment of this issue. That was how the other issue came about.

**Comment by Linux4Life531** [comment]
Can this be closed please as it has been resolved.
