### ISSUE TITLE
rpi-update should not be included at all

### ISSUE THREAD

**Issue by ingotee** [r-darwish/topgrade#302]
On a Raspberry Pi, rpi-update should never be run without an explicit need and reason, let alone automatically. Thus I do not think it should be included in topgrade at all.

Source. The documentation on raspberrypi.org: https://www.raspberrypi.org/documentation/linux/kernel/updating.md

Thanks for topgrade nevertheless!

**Comment by r-darwish** [comment]
Can't argue with the official documentation. I'll remove it

**Comment by ingotee** [comment]
Thanks!
