### ISSUE TITLE
Why is there a restriction for npm?

### ISSUE THREAD

**Issue by ad-si** [r-darwish/topgrade#303]
The documentation says:

> Run npm update -g if NPM is installed and npm root -g is a path inside your home directory.

Can you maybe explain in the readme why this is necessary? Also when is `npm root -g` a path inside your home directory? Doesn't seem to be standard behavior.

**Comment by schrodincat** [comment]
I agree, for example on macOS global NPM packages are located `/usr/local/lib/node_modules` (if `node` installed via `brew`), and that's a user-writable directory

**Comment by r-darwish** [comment]
I wrote this step with Linux in mind, in which you need to run NPM as `sudo` when the home directory isn't writable by the user, which I won't do.

I understand that permissions works a bit differently in macOS. I'll consider changing the behavior in macOS

**Comment by ad-si** [comment]
Ah, I see. And yes I'm on macOS so a change in behavior would be appreciated! 😁
