### ISSUE TITLE
macOS configuration directory is unusual

### ISSUE THREAD

**Issue by schrodincat** [r-darwish/topgrade#304]
Is there any reason why you choose `~/Library/Preferences` for storing preferences on macOS?

To the best of my knowledge, no CLI tool is using this directory for storing settings, since it's reserved for GUI `.app` applications (or, to be more diligent, `~/Library/Preferences` is used for apps that require Mac-specific frameworks, like Cocoa) that usually store settings in binary plist format which are not supposed to be manipulated by the user directly. Cross-platform apps, especially CLI tools are usually using standard UNIX `~` or `~/.config` paths.

Of course, that's not a huge deal, but would you consider also to allow storing the config in standard `~/.config` folder, so it would be easier to manage it with dotfiles?

P.S.
Thanks for such a wonderful tool🦾

**Comment by r-darwish** [comment]
To be honest, I'm not entirely happy with this decision as well. It's just the behavior of [BaseDir](https://docs.rs/directories/2.0.2/directories/struct.BaseDirs.html). I can add some code to look for the configuration in `~/.config` as well.

**Comment by schrodincat** [comment]
That would be awesome!

**Comment by r-darwish** [comment]
Fixed in 59fc516711cc97f685aff416491480768b9bced8
