### ISSUE TITLE
Default list of Git paths to pull is opinionated

### ISSUE THREAD

**Issue by schrodincat** [r-darwish/topgrade#305]
Default list of Git paths to pull seems arbitrary. Some popular things are missing, some less popular are present...

Since there are thousands of other possible configuration files and it's not feasible to maintain the full list, I propose to make the list either empty by default (so `topgrade` would be more predictable and less opinionated) or, if you wish to maintain some subset of popular paths by default, to allow override it in the user config file (not append, but override).

My reasoning for this, that user can have other tool managing dotfiles while still be interested to pull some Git repos. Currently, there is no way to clear the list from default entries.

**Comment by r-darwish** [comment]
I don't mind adding an option to override this list, but I wonder why does the list bother you. Topgrades only pull files which it detects to be inside a git repository. If you use some other tool to manage your configuration then it should not conflict with Topgrade.

**Comment by schrodincat** [comment]
I’m using the tool which in turn uses Git under the hood, however, it does a lot of other stuff (like merging configuration files, symlinking etc.)
