### ISSUE TITLE
macOS step doesn't actually update Mac App Store apps

### ISSUE THREAD

**Issue by schrodincat** [r-darwish/topgrade#306]
`softwareupdate` utility only updates macOS system packages, so the title "App Store" is quite misleading. I suggest to change it to "Software Update" or even "softwareupdate" so it would be more in line with other titles.

I've opened another issue regarding support for Mac App Store updates: https://github.com/r-darwish/topgrade/issues/307

**Comment by r-darwish** [comment]
Sounds reasonable. I'm closing this as I'll implement both of these suggestions when I do #307
