### ISSUE TITLE
Exclude update when running Windows Update

### ISSUE THREAD

**Issue by graphixillusion** [r-darwish/topgrade#310]
Hi there. Is there any way to ignore an update when running topgrade during Windows Update phase? I already tried to manually hide the update with the powershell module but when i run topgrade again it reinstalls it. In my case i would like to skip the silverlight installation. Thank you.

**Comment by r-darwish** [comment]
You should be able to write
```toml
accept_all_windows_updates = false
```
In your configuration once the next version of Topgrade is out
