### ISSUE TITLE
Composer should uprade itself

### ISSUE THREAD

**Issue by klausi** [r-darwish/topgrade#318]
I just noticed that my composer executable was outdated many months and I got an email about Github API deprecated use. That was fixed in the last composer release https://github.com/composer/composer/releases/tag/1.9.3 , but `topgrade` does not upgrade composer itself. I think it should?

A recommended global installation of composer is in /usr/local/bin on Linux/MacOs/Unix, see https://getcomposer.org/doc/00-intro.md#globally . Composer has a built in slef-update command, so it should be enough to run `sudo composer self-update`.

**Comment by r-darwish** [comment]
I agree to have an opt-in feature in the configuration to run composer as root. However, this won't be the default behavior as it poses a risk to the system
