### ISSUE TITLE
Add MacPorts support

### ISSUE THREAD

**Issue by lhaeger** [r-darwish/topgrade#331]
If you aim for completeness, supporting MacPorts (both as a) an install source for topgrade and b) as a supported package manager) would be great.

I'm happy to create a topgrade port (a) but since my rust knowledge is non existing, someone else would have to make topgrade call something like 
`sudo port selfupdate && sudo port -u upgrade outdated && sudo port -N reclaim`
if macports is installed. This should be easy to detect by checking running 
`which port`

**Comment by r-darwish** [comment]
Aiming for completeness is impossible in this world. I implemented features on demand. Do you actually use MacPorts?

**Comment by lhaeger** [comment]
Yes, I use Macports for all that‘s available through it, also maintain a couple of ports.
