### ISSUE TITLE
Add feature where topgrade runs at a certian time every day.

### ISSUE THREAD

**Issue by Linux4Life531** [r-darwish/topgrade#338]
Add another file that reads a time (hours and days) and will run topgrade every day at that specific time.
This will help users like domoaligato (who wanted to run topgrade every night) do what they like. This also means users do not have to manually type the command every time, they can just set it on automatic to update when they want.
I am going to attempt to make some files to solve this in my branch of topgrade
Linux and Unix users will be able to use this feature
The user will be able to run TopgradeTime and then enter a time of their choice.
I am suggesting a new feature for Linux and Unix topgrade users.
I could test this new feature.

**Comment by andrei-pavel** [comment]
Here's a crazy idea.

```
0 0 * * * ${USER}/.cargo/bin/topgrade
```

This cron script runs at every midnight.

Alternatively: `at`, `openrc`, `systemd`, `sysv-init`

**Comment by andrei-pavel** [comment]
This solutions even log output, run if time was missed due to computer being shut down. Can you imagine?

**Comment by Linux4Life531** [comment]
> Here's a crazy idea.
> 
> ```
> 0 0 * * * ${USER}/.cargo/bin/topgrade
> ```
> 
> This cron script runs at every midnight.
> 
> Alternatively: `at`, `openrc`, `systemd`, `sysv-init`

I was going to make a script that runs cronjobs however some users might not know how to do that so if they just entered the time and the script did the rest for them it would be much easier for them

**Comment by r-darwish** [comment]
As @andrei-pavel said, this is beyond the scope of Topgrade. There are many tools that can run Topgrade periodically for you.
