### ISSUE TITLE
Topgrade is not updating itself

### ISSUE THREAD

**Issue by Linux4Life531** [r-darwish/topgrade#339]
I expected topgrade to upgrade itself when possible

It is now multiple versions out of date

OS: Manjaro
Instillation: AUR

**Comment by r-darwish** [comment]
When you install Topgrade from a package manager, such as AUR, the self update is disabled, as it is the responsibility of the package manager to upgrade Topgrade. 

If you wish the use the self-update features then you have to download one of the binaries in the release page. These are compiled with the self-update feature.

**Comment by Linux4Life531** [comment]
Thank you.
