### ISSUE TITLE
Travis is broken due to cross 0.2

### ISSUE THREAD

**Issue by r-darwish** [r-darwish/topgrade#340]

**Comment by idanski** [comment]
do you think creating custom images and specifying them in Cross.toml is the way to go, or is there a way not to rely on openssl?

**Comment by r-darwish** [comment]
I think that for the moment I should be okay if I explicitly install cross 0.1.

For the long run - the self-update crate supports rustls, but I'll have to bump its version and go through some backward incompatible changes.

**Comment by r-darwish** [comment]
We still depend on openssl due to external dependencies. We'll probably have to live with that until some day it is fixed.
