### ISSUE TITLE
Failed to install on Windows (missing gcc.exe)

### ISSUE THREAD

**Issue by rzikm** [r-darwish/topgrade#343]
**What did you expect to happen?**
I expected to install topgrade using `cargo install topgrade` on Windows 10 machine.

**What actually happened?**
Failed to build a dependency backtrace-sys due to missing gcc.exe.

**Additional details:**
According to https://github.com/alexcrichton/cc-rs#compile-time-requirements linked in error message, it should be possible to compile for MSVC. I consider this a bug because GCC is not listed as a requirement for windows installation on readme page.

I also tried running it in developer command prompt, which has cl.exe and other binaries in PATH, with same result.

I know that I can download binaries from release page, but I prefer package managers to manage programs in my PATH.

**Comment by r-darwish** [comment]
Please show the output of `rustup show`

**Comment by rzikm** [comment]
I did not have the `rustup` command.

After digging in a bit, it turns out that `choco install rust` installs gnu toolchain of rust, after more digging I installed rustup and installed correct toolchain, and it works flawlessly now.

Me being a rust noob, I somehow thought that rust detects the toolchain on the fly (like CMake). The issue can be closed now I suppose.
