### ISSUE TITLE
Update Microsoft Office on MacOS

### ISSUE THREAD

**Issue by andunix** [r-darwish/topgrade#344]
**I want to suggest a new step**
***Which tool is this about? Where is its repository?***
Microsoft Office can be updated by running
/Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS/msupdate --install
***Which operating systems are supported by this tool?***
MacOS
***What should Topgrade do to figure out if the tool needs to be invoked?***
/Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS/msupdate --list
***Which exact commands should Topgrade run?***
/Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS/msupdate --list
/Library/Application\ Support/Microsoft/MAU2.0/Microsoft\ AutoUpdate.app/Contents/MacOS/msupdate --install

**More information**
- Assuming that someone else implements the feature, please state if you know
  how to test it from a side branch of Topgrade
I'm using topgrade fromHomwbrew, but I know how to checkout a git branch. I think, I would be able to test a feature branch.

**Comment by r-darwish** [comment]
I actually tried to implement it once and found out that it takes long time and always tells me that there are no upgrades (while the GUI says there are).

Maybe it was fixed since then. I'll try.

**Comment by andunix** [comment]
It worked! Thank you!
```
―― 17:53:57 - Microsoft AutoUpdate ―――――――――――――――――――――――――――――――――――――――――――――
Checking for updates...
Updates available:
  PPT315  PowerPoint Update 16.16.20 (20030700)
  MSWD15  Word Update 16.16.20 (20030700)
  XCEL15  Excel Update 16.16.20 (20030700)
Detecting and downloading updates...
Queued updates:
  PPT315
  MSWD15
  XCEL15

―― 17:56:04 - macOS system update ――――――――――――――――――――――――――――――――――――――――――――――
```
