### ISSUE TITLE
Does not recognize Manjaro KDE

### ISSUE THREAD

**Issue by sduford** [r-darwish/topgrade#35]
Topgrade throws an error "Unkown Linux Distribution", only upgrades flatpaks and snaps.
I'm running Manjaro Linux 17.1.10 w 4.17.0-2-MANJARO kernel.

**Comment by r-darwish** [comment]
Can you please paste the content of `/etc/os-release`?

**Comment by sduford** [comment]
NAME="Manjaro Linux"
ID=manjaro
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"

**Comment by r-darwish** [comment]
@sduford I don't have a Manjaro VM at the moment. Can you compile and run the `manjaro` branch which I just pushed at tell me if it's ok?

**Comment by sduford** [comment]
How do I build it?

**Comment by r-darwish** [comment]
Never mind. I downloaded a VM and checked it. The support will be available in the next version.

**Comment by sduford** [comment]
Great, thanks. Got it compiled and it works.
