### ISSUE TITLE
Add a more verbose Dry Run

### ISSUE THREAD

**Issue by modularTaco** [r-darwish/topgrade#355]
**I want to suggest some general feature**
Topgrade should have a more verbose dry run option than the current one.
The behavior of the current dry run is like "these are the commands that would be run".
Personally I would prefer a behavior like "These are the updates I would install, if you would start me without `-n`".
So Topgrade should check if there are new updates available and list them for each tool, instead of just list the commands it would run to update.
For yum it should run `yum check-update` (same for dnf), I think something similar is available for the most of the included tools.
Otherwise I can just run topgrade and update everything, without knowing  which packages it'll update.
So the behavior of a normal topgrade run for Firmware upgrade, just listing which components could get a firmware update, should be possible for the majority of the other supported tools via command line option.

I think this issue is kind of similar to #207, but not completely the same

**Comment by r-darwish** [comment]
I think this is identical to #207, isn't it? What extra feature is suggested in this issue?

**Comment by modularTaco** [comment]
> I think this is identical to #207, isn't it? What extra feature is suggested in this issue?

#207 does not specify **what** the output of the dry command should be, it could be barely anything that just outputs something and does nothing else.
I am asking for a certain output (pending updates), no matter how it is achieved.
Maybe this would be sufficient as a comment to #207

**Comment by r-darwish** [comment]
I'll close this in favor of #207 because this is probably what we'll get once we implement it. 

Note that not all packages have a dry run flag, so once this is implemented you will probably still see some "would run" messages in steps which involves package managers that don't have a built-in dry-run support
