### ISSUE TITLE
Improve scanning for Git Repositories

### ISSUE THREAD

**Issue by NerdyMcNerd** [r-darwish/topgrade#356]
Hi,

**What I tried**
I configured the `git_repos` option to my Dev folder using the double star in the path:
```toml
git_repos = [
    "D:\\Dev\\**"
]
```
... which works (big thanks for that!), except for one little inefficiency: Topgrade recurses the complete subtree.

When I run Topgrade in Verbose Mode, I get a ton of outputs like:
```
 2020-03-02T19:27:46.020Z DEBUG topgrade::steps::git > Checking if \\?\D:\Dev\myGitServer\myGroup\myRepo\.git\objects\f4 is a git repository
 2020-03-02T19:27:46.021Z DEBUG topgrade::steps::git > Transformed path to D:\Dev\myGitServer\myGroup\myRepo\.git\objects\f4
 2020-03-02T19:27:46.046Z TRACE topgrade::executor   > Output of "C:\\Program Files\\Git\\cmd\\git.EXE" "rev-parse" "--show-toplevel": Output { status: ExitStatus(ExitStatus(128)), stdout: "", stderr: "fatal: this operation must be run in a work tree\n" }
```
The output tells me that Topgrade is looking for git repos in the `.git` subfolder (and even in its subfolders)

There are no git repositories in the `.git` folder of a git repository.
And in most cases there are no git repositories inside of git repositories (submodules are handled differently)

The repo scanning can be improved by capping the recursion once a folder is positively identified as git repo.

To be clear: noting is broken, it's just a little inefficient.

**Additional details:**
- OS: Windows 10
- Downloaded topgrade.exe (version 4.1.0) directly from github (windows-msvc package)

**Comment by r-darwish** [comment]
This is an interesting proposition. Sadly [glob](https://github.com/rust-lang-nursery/glob) returns an iterator and doesn't provide any mechanism to skip traversing something in runtime. 

Maybe someone else can suggest an idea about how to implement it.

**Comment by NerdyMcNerd** [comment]
I re-ran topgrade on a big tree of git repos and I observed that the paths seem to be ordered lexicographically. (At least this is the case on my Windows Machines)
If we assume that this is always the case we can try something like this:

```cpp
last_known_repo_path = NULL
while(iterator_returned_by_glob.has_next())
{
	if(last_known_repo_path != NULL && itreator.starts_with(last_known_repo_path))
	{
		continue
	}

	if(check_if_is_git_repo(iterator))
	{
		last_known_repo_path = iterator
	}

	iterator_returned_by_glob.next()
}

```
(Sorry for the bad C++ style pseudocode, but I litterally saw Rust sourceode for the first time yesterday)

Even it the iterator does not return the paths ordered, this won't lead to wrong behavior,
since the invariant of this function is correct: all subpaths of a git repo can be skipped.
In the worst case (inverse sorted paths), this will lead to the current behavior.

**Comment by r-darwish** [comment]
Not sure we can rely on lexical order, but we can keep a hashset with the recorded git repositories

**Comment by NerdyMcNerd** [comment]
Keeping all recorded git repositories is an option.  
But the detection if a directory can be skipped will lead to increased complexity, something like O(n!) or O(n²) if I recall correctly.
Because for each folder, we need to check if it is a sub-path of each recorded git repository.

But maybe this can be ignored, because the real performance gain would be to get rid of the call to the git executable for each non-repo folder.

**Comment by NerdyMcNerd** [comment]
Oh, nice thing, the last sentence in the [glob Documentation](https://docs.rs/glob/0.3.0/glob/fn.glob.html): "Paths are yielded in alphabetical order."

So we can rely on on lexical order, because the library guarantees it.

**Comment by r-darwish** [comment]
> Oh, nice thing, the last sentence in the [glob Documentation](https://docs.rs/glob/0.3.0/glob/fn.glob.html): "Paths are yielded in alphabetical order."
> 
> So we can rely on on lexical order, because the library guarantees it.

Good catch. I'll try to implement it as you suggested

**Comment by andrei-pavel** [comment]
Highjacking this thread to signal a possible problem with submodules.

To my understanding, unlike subtrees, submodules don't get pulled with the parent repository.

Consider this: parent repository gets pulled through topgrade, commit of submodule gets updated in `.gitmodules`, but on `git status` it shows `modified:   submodule_name (new commits)`, topgrade stops and doesn't pull the inner submodule. Parent repository is up to date except for the submodule which is now NOT inline with the parent repository.

Previous behavior was wrong in pulling, but shouldn't topgrade also run `git submodule update --init --recursive` so that it checks out the submodule to the updated pinned version?

**Comment by r-darwish** [comment]
@andrei-pavel we should probably update submodules as well. I'll open a different issue for that.
