### ISSUE TITLE
Handling of pinned packages in Homebrew

### ISSUE THREAD

**Issue by pauxus** [r-darwish/topgrade#359]
**I want to suggest some general feature**
When a homebrew package is pinned, `brew upgrade` returns a non-zero exit code, which leads topgrade to stop right there and ask how to handle it (see https://github.com/Homebrew/brew/issues/4063)

I might be as easy as calling `brew upgrade --ignored-pinned`, but since the error is intentional from the homebrew side, it might be safer to make this configurable, so I would like to put this to discussion.

**More information**
This can be easily checked by pinning a package to an older version using `brew pin` and the running `topgrade`.

**Comment by r-darwish** [comment]
I'm fine with making it non configurable default
