### ISSUE TITLE
[Question] Custom tools support

### ISSUE THREAD

**Issue by aheritier** [r-darwish/topgrade#362]
Hi,

  Is there a feature to support custom tools upgrades?
  If I have a binary `foo`, I would like to configure topgrade to call `foo upgrade` for instance.
  I saw a git_repo configuration entry but I am not sure if it could allow me to do such extension.

Thanks

**Comment by idanski** [comment]
You can edit the configuration file to use custom commands:
see [https://github.com/r-darwish/topgrade/blob/master/config.example.toml#L48](example)

**Comment by aheritier** [comment]
@idanski ah yes ! it's exactly what I was looking for.
Thanks a lot
