### ISSUE TITLE
Failed to obtain auth after fwupd successful update

### ISSUE THREAD

**Issue by kflak** [r-darwish/topgrade#371]
**What did you expect to happen?**
Select item 1-3 in the report dialog after successful fw update.

**What actually happened?**
Getting the error "Failed to obtain auth"

**Additional details:**
- Which operating system or Linux distribution are you using?
Arch Linux on a Thinkpad T480s
- How did you install Topgrade?
AUR

<details><pre>
Output of `topgrade -v`
―― 17:30:12 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
 2020-03-14T16:30:12.810Z DEBUG topgrade::executor         > Running "/usr/bin/fwupdmgr" "refresh"
Firmware metadata last refresh: 1 hour ago. Use --force to refresh again.
 2020-03-14T16:30:12.826Z DEBUG topgrade::executor         > Running "/usr/bin/fwupdmgr" "get-updates"
• Thunderbolt Controller has no available firmware updates
• Samsung SSD 970 EVO Plus 1TB has no available firmware updates
• System Firmware has the latest available firmware version
• UEFI Device Firmware has the latest available firmware version
• UEFI Device Firmware has the latest available firmware version
________________________________________________

Devices that have been updated successfully:

 • System Firmware (0.1.38 → 0.1.39)

Uploading firmware reports helps hardware vendors to quickly identify failing and successful updates on real devices.
Upload report now? (Requires internet connection):
0.	Do not upload reports at this time, but prompt again for future updates
1.	Do not upload reports, and never ask to upload reports for future updates
2.	Upload reports just this one time, but prompt again for future updates
3.	Upload reports this time and automatically upload reports after completing future updates
3
Failed to obtain auth
 2020-03-14T16:30:25.481Z DEBUG topgrade::terminal         > Desktop notification: Firmware upgrades failed
</pre></details>

**Comment by r-darwish** [comment]
Does it happen when you run `fwupd` on your own?

**Comment by kflak** [comment]
When I run `fwupdmgr update` I get a list of the supported devices, but no request for reporting. I am not really sure which command `topgrade` runs that makes this happen...

**Comment by r-darwish** [comment]
Run `topgrade --dry-run` and you'll see the command

**Comment by kflak** [comment]
Ah,  this gives me the same error. fwupd issue, thus, so will take it further there! Sorry for the noise :-)
