### ISSUE TITLE
Topgrade fails to handle pacman error"file xxx already exists in file system" - unusable

### ISSUE THREAD

**Issue by DAC324** [r-darwish/topgrade#372]
Hello,
Sorry, but I have to admit that topgrade, at least in its current version, does not appear to be satisfactorily usable under Manjaro and other Arch based Linux distributions.

I guess you all have already experienced pacman's error message "file xxx already exists in the filesystem", and have learned to love it as pacman then refuses to install all packages.

Topgrade handles this problem even worse - you only have the options to repeat (which is complete nonsense - the file surely will not disappear on its own), to abort or to go to (s)hell.
Why is there no "override" option to choose from?
Because finally, in order to solve this problem, you will have to go to the command line anyway and issue
<pre>
sudo pacman -Syyu --override '*'
</pre>
But as you'll have to do this anyway, what's then the benefit of topgrade? Right, there's none.
On the other hand, upon every topgrade install or update, it downloads seperate versions of all the tools it needs, and compiles them, no matter if they are already present in the system or not. That's, in my opinion, nonsense as well.
That being said, I regret having to say that topgrade currently cannot really be recommended for Arch-based Linux distributions.

**Comment by andrei-pavel** [comment]
You are so completely right, no benefit whatsoever.

![image](https://user-images.githubusercontent.com/6838492/76747352-ad0d6600-6781-11ea-8118-a12d5eb80bf3.png)

Since we're taxing every mistake out there, it's not `--override`, it's `--overwrite`, amirite?

Now try installing `yay` and confuguring this:
```
yay_arguments = "-yyuu --needed --noconfirm --overwrite '*'"
```
in `~/.config/topgrade.toml`

Oh, you want it to work for pacman as well?
Oh, you want it to be interactive?
Maybe ask nicely.

**Comment by r-darwish** [comment]
"Sorry" isn't a magic word that you can put at the beginning of such a toxic text and expect people to help you out.

If you have a specific feature request, open another issue explaining what you wish without all the "Topgrade is awful and I won't recommend it to anyone unless you do what I want".

P.S
@andrei-pavel thank you for helping out here 👍
