### ISSUE TITLE
Option to ignore Pi-hole

### ISSUE THREAD

**Issue by xyrolaith** [r-darwish/topgrade#373]
I am running Pi-hole on Arch Linux using the **pi-hole-server** AUR package.

As the package takes care of updating Pi-hole itself, the "-up" switch has been removed and throws an error message when topgrade tries to run the update command.

Topgrade should have an option to ignore Pi-hole, e.g. `disable = ["pihole"]`

**Comment by r-darwish** [comment]
I prefer Topgrade to be as "smart" as possible and figure out on its own whether it should do it or not. Do you have any suggestion for how can we detect? Perhaps only run this if we're on the official pi-hole distribution

**Comment by xyrolaith** [comment]
I do not know about the official Pi-hole distribution but when running `/usr/bin/pihole -h` the help for updating Pi-hole is missing, which contains the string **updatePihole**.

The shell script used for the actual update (`/opt/pihole/update.sh`) is also missing. The official Pi-hole installer will place the update script there as well.

**Comment by r-darwish** [comment]
Great. I'll check for the presence of `/opt/pihole/update.sh`
