### ISSUE TITLE
run diff when upgrading (not a bug)

### ISSUE THREAD

**Issue by dkwo** [r-darwish/topgrade#377]
Nice tool.
When I update, I'd like to also run
`diff ~/Projects/dropbox.py <(curl -sL https://www.dropbox.com/download?dl=packages/dropbox.py)`
to check whether my Dropbox script is up to date with what they have online.
Is there a simple way to include this check in topgrade?

**Comment by r-darwish** [comment]
There are [custom command](https://github.com/r-darwish/topgrade/blob/master/config.example.toml#L55)
