### ISSUE TITLE
Cannot disable yarn without npm, though my yarn is Hadoop yarn, not node

### ISSUE THREAD

**Issue by Yamp** [r-darwish/topgrade#378]
**What did you expect to happen?**
I expect topgrade to either use proper yarn or to have an ability to disable yarn without disabling npm. My "yarn" command which is in my PATH is hadoop yarn, and not the node yarn.

**What actually happened?**
NPM: OK
yarn: FAILED

**Additional details:**
- Which operating system or Linux distribution are you using? **MacOS**
- How did you install Topgrade? With homebrew
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)

<details><pre>
<img width="712" alt="Screenshot 2020-03-19 at 21 07 12" src="https://user-images.githubusercontent.com/5207009/77099799-9dae4700-6a25-11ea-9c23-f35936a46b1b.png">

It also seems like I cannot disable specifically yarn update, only the whole node updates possible.

 2020-03-19T17:57:26.372Z ERROR topgrade::config > failed to load configuration: unknown variant `yarn`, expected one of `system`, `packagemanagers`, `gitrepos`, `vim`, `emacs`, `gem`, `node`, `composer`, `sdkman`, `remotes`, `rustup`, `cargo`, `flutter`, `go`, `shell`, `opam`, `vcpkg`, `pipx`, `stack`, `tlmgr`, `myrepos`, `pearl`, `jetpack`, `atom`, `firmware`, `restarts`, `tldr` for key `disable` at line 48 column 1

</pre></details>

**Comment by r-darwish** [comment]
Can you show me the output of `yarn -v`. I'll run this command to detect if it's Hadoop's yarn

**Comment by Yamp** [comment]
❯ yarn -v
ERROR: -v is not COMMAND nor fully qualified CLASSNAME.
Usage: yarn [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
 or    yarn [OPTIONS] CLASSNAME [CLASSNAME OPTIONS]
  where CLASSNAME is a user-provided Java class

  OPTIONS is none or any of:

--buildpaths                       attempt to add class files from build tree
--config dir                       Hadoop config directory
--daemon (start|status|stop)       operate on a daemon
--debug                            turn on shell script debug mode
--help                             usage information
--hostnames list[,of,host,names]   hosts to use in worker mode
--hosts filename                   list of hosts to use in worker mode
--loglevel level                   set the log4j level for this command
--workers                          turn on worker mode

  SUBCOMMAND is one of:


    Admin Commands:

daemonlog            get/set the log level for each daemon
node                 prints node report(s)
rmadmin              admin tools
scmadmin             SharedCacheManager admin tools

    Client Commands:

applicationattempt   prints applicationattempt(s) report
app|application      prints application(s) report/kill application/manage long running application
classpath            prints the class path needed to get the hadoop jar and the required libraries
cluster              prints cluster information
container            prints container(s) report
envvars              display computed Hadoop environment variables
jar <jar>            run a jar file
logs                 dump container logs
nodeattributes       node attributes cli client
queue                prints queue information
schedulerconf        Updates scheduler configuration
timelinereader       run the timeline reader server
top                  view cluster information
version              print the version

    Daemon Commands:

nodemanager          run a nodemanager on each worker
proxyserver          run the web app proxy server
registrydns          run the registry DNS server
resourcemanager      run the ResourceManager
router               run the Router daemon
sharedcachemanager   run the SharedCacheManager daemon
timelineserver       run the timeline server

SUBCOMMAND may print help when invoked w/o parameters or with -h.

**Comment by Yamp** [comment]
May be this is more helpful

`
❯ yarn version
Hadoop 3.2.1
Source code repository https://gitbox.apache.org/repos/asf/hadoop.git -r b3cbbb467e22ea829b3808f4b7b01d07e0bf3842
Compiled by rohithsharmaks on 2019-09-10T15:56Z
Compiled with protoc 2.5.0
From source with checksum 776eaf9eee9c0ffc370bcbc1888737
This command was run using /usr/local/Cellar/hadoop/3.2.1_1/libexec/share/hadoop/common/hadoop-common-3.2.1.jar
`
