### ISSUE TITLE
upgrading vim giving errors

### ISSUE THREAD

**Issue by muralikodali** [r-darwish/topgrade#381]
in previous versions of topgrade , i have not faced any issue with vim upgrade. while i have used vundle as addon manager previously, now I have Plug as addon manager for vim.

topgrade is giving errors as shown below:
XSMP opening connection
not found in 'runtimepath': "spell/en.vim"
not found in 'runtimepath': "autoload/grepper.vim"
not found in 'packpath': "pack/*/start/*"
not found in 'runtimepath': "autoload/sneak.vim"
not found in 'packpath': "pack/*/start/*"
Opening the X display took 0 msec
Reading viminfo file "/home/xxxx/.viminfo" info oldfiles
Opening the X display took 0 msec
Error detected while processing command line:
E492: Not an editor command: PluginUpdate
Writing viminfo file "/home/xxxx/.viminfo"

I request you to give suggestions in wiki to to specifically include or exclude any package.

**Comment by r-darwish** [comment]
What happens if you run `topgrade -n` and run the upgrade command yourself?

**Comment by muralikodali** [comment]
topgrade -n giving no errors. 

when topgrade is run, it is giving errors  for vim and nevoim.

**Comment by r-darwish** [comment]
What I meant is what happens if you manually run the command that is displayed when you run `topgrade -n`
