### ISSUE TITLE
Disable tlmgr by default

### ISSUE THREAD

**Issue by BjoernDaase** [r-darwish/topgrade#384]
**I want to suggest some general feature**
I think we should disable `tlmgr` by default.  
The background is, that updating with `tlmgr`, if texlive is installed via your package manager, breaks your existing texlive installation. But at least on Fedora texlive also installs `tlmgr` by default.

This is the message which always gets printed during the `tlmgr` update:
```
―― 23:06:07 - TeX Live package manager ―――――――――――――――――――――――――――――――――――――――――
*** WARNING ***: Performing this action will likely destroy the Fedora TeXLive install on your system.
*** WARNING ***: This is almost NEVER what you want to do.
*** WARNING ***: Try using dnf install/update instead.
*** WARNING ***: If performing this action is really what you want to do, pass the "ignore-warning" option.
*** WARNING ***: But please do not file any bugs with the OS Vendor.
```

While it's not dangerous per se, it looks very dangerous and therefore does not really give a good user experience.

**Comment by r-darwish** [comment]
Is there any tlmgr command that we can execute that reports if TeX Live was installed using a package manager?

**Comment by BjoernDaase** [comment]
At least I do not know any :(

**Comment by Evpok** [comment]
Is it not recommended *not* to install texlive via package managers?

**Comment by BjoernDaase** [comment]
> Is it not recommended _not_ to install texlive via package managers?

AFAIK both ways are fine and have their individual pros and cons (stability vs. availability/cutting edge). But  you should never mix it, meaning e.g. installing `texlive` via your package manager but updating the packages using `tlmgr` is a very bad idea as it will most likely break your `texlive` installation.

**Comment by Evpok** [comment]
Ah right, I understand the issue now: some distros include tlmgr in their packaged texlive even though you are not supposed to use it. I thought it could still be useful to manage a local texmf
