### ISSUE TITLE
Add pre_commands per git repo, or global git repo pre_commands

### ISSUE THREAD

**Issue by folknor** [r-darwish/topgrade#387]
**I want to suggest some general feature**

I've got 20+ git repos checked out from which I build tools that I use daily that are not part of my systems package repository. These commands include `fd-find`, `ripgrep`, and so forth. I don't want to install them using `cargo` because that removes customization options available to me when building these packages.

I've kept an eye on topgrade since your initial release wanting to use it for updating these git repositories, and I just tested it again - but the problem is I need to do a full git reset every time because I often (almost daily) make local adjustments to these git repos before building, and it seems difficult to do with topgrade at the moment. I currently use a custom script to update these repositories, and what it does is basically `git fetch --all`, `git reset --hard origin/master`, and finally `git pull`.

My custom script is fine, but I love your tool and I'd like to get this added somehow.

For example, either
1. Add a config option that specifies commands that are run for all git repos pre-pull, or
2. Add a new `git_repos_with_pre` array which would get the treatment I defined above or some alternative defined in an `git_repo_pre_commands` option string/array.

Or some other, much more elegant solution that you come up with :-)

Perhaps a `_post` command could also future-proof it for some other usecases.

Thanks for reading!

**Comment by r-darwish** [comment]
In addition to custom steps, there are [pre_commands](https://github.com/r-darwish/topgrade/blob/a981aad3df1f11d59e231538713a6aa3deb61036/config.example.toml#L46-L49) which are guaranteed to run before anything. You could make a precommand that only resets your repositories

**Comment by folknor** [comment]
Indeed, thank you, but then I might as well just continue to use my custom script since I'll have to maintain the list of repositories in two places.

I understand this is an obscure feature request, and obviously I don't expect anything from something I get to enjoy entirely for free.

You should not feel bad about rejecting my request and closing the ticket, if that is your wish. Or leave it open. I've worked on open source projects where tickets remain open for literally multiple decades before someone suddenly touches it, and also on projects where maintainers want a "clean" issue list.

**Comment by r-darwish** [comment]
I prefer closing this one for the time. Thanks for understanding.
