### ISSUE TITLE
Please support rbenv by making `--user-install` optional in the gem step

### ISSUE THREAD

**Issue by pro-sumer** [r-darwish/topgrade#393]
Since I use [rbenv](https://github.com/rbenv/rbenv) to manage my Ruby versions, gems will be installed "system wide" in my home folder, for example:

~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0

However, since `topgrade` always uses the option `--user-install` when executing `gem update` it will install/update gems in:

~/.gem/ruby/2.7.0

Please make using that parameter `--user-install` optional (configurable via the config file) so that:
- topgrade will not install a duplicate set of gems
- topgrade will update the correct set of gems (those that I installed, not the duplicates from topgrade)

**Comment by r-darwish** [comment]
Does it always make sense not to use `--user-install` when using rbenv? If so, I suggest detecting whether the user is using rbenv and set the flag accordingly. Does that sound reasonable? If so, how should Topgrade detect if Ruby is managed by rbenv?

**Comment by pro-sumer** [comment]
I think you're right about not using `--user-install` at all when using [rbenv](https://github.com/rbenv/rbenv), but I'm not sure what would be the best way to detect whether rbenv is managing Ruby.
