### ISSUE TITLE
Can't upgrade oh-my-zsh

### ISSUE THREAD

**Issue by oleynikandrey** [r-darwish/topgrade#394]
**What did you expect to happen?**
`oh-my-zsh` upgraded successfully

**What actually happened?**
```
brew: OK
oh-my-zsh: FAILED
vim: OK
NPM: OK
System upgrade: OK
```

**Additional details:**
- macOS Catalina 10.15.4
- topgrade installed by brew
<details><pre>
―― 10:44:20 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
 2020-04-20T07:44:20.989Z TRACE topgrade::executor   > Output of "zsh" "-i" "-c" "echo -n $ZSH_CUSTOM": Output { status: ExitStatus(ExitStatus(0)), stdout: "\u{1b}]1337;RemoteHost=user@host.local\u{7}\u{1b}]1337;CurrentDir=/Users/user\u{7}\u{1b}]1337;ShellIntegrationVersion=10;shell=zsh\u{7}/Users/user/.oh-my-zsh/custom", stderr: "" }
 2020-04-20T07:44:20.989Z DEBUG topgrade::steps::zsh > oh-my-zsh custom dir: /Users/user/.oh-my-zsh/custom/plugins
 2020-04-20T07:44:20.989Z DEBUG topgrade::terminal   > Desktop notification: oh-my-zsh failed
</pre></details>

**Comment by r-darwish** [comment]
Can you please post your `~/.zshrc`?

**Comment by oleynikandrey** [comment]
I've removed all comments

```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE="awesome-patched"

plugins=(rails ruby git osx pep8 git-extras pip python screen pyenv vagrant z httpie dircycle tmux docker golang dash vscode zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

LESSPIPE=`which src-hilite-lesspipe.sh`
export LESSOPEN="| ${LESSPIPE} %s"
export LESS=' -R '

export LC_ALL=en_US.UTF-8

if [[ -t 0 && $- = *i* ]]
then
    stty -ixon # unmap ctrl-s
fi 

ack() {vi -c "Ack $_"}

alias -g ND='*(/om[1])' # newest directory
alias -g NF='*(.om[1])' # newest file

TERM=xterm-256color
alias tmux="TERM=screen-256color-bce tmux"
export TERM
alias vim="reattach-to-user-namespace vim"
alias vi="vim"

gn() {
	growlnotify Finished -n "shell" -m "Done" $@
}

export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

alias inotebook="cd ~/ipython_notebooks; vex tests ipython notebook"

DEFAULT_USER=user

fpath=(/usr/local/share/zsh-completions $fpath)


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

function tabname {
  if [ -z $TMUX ] ; then
    printf "\e]1;$@\a"
  else
   tmux rename-window $@
  fi
}

fpath=(~/zsh_functions $fpath)
autoload transfer
export PATH="/usr/local/opt/libpq/bin:$PATH"

alias lynx='/Applications/Lynxlet.app/Contents/Resources/lynx/bin/lynx'

export PATH=$PATH:$HOME/go/bin

export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.8/bin

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

**Comment by r-darwish** [comment]
Can you please check if it works when you comment out everything that's not necessary for oh-my-zsh?

**Comment by oleynikandrey** [comment]
@r-darwish, you are right, route cause in `.zshrc` file.

When I left only the following lines
```
export ZSH=$HOME/.oh-my-zsh
plugins=(rails ruby git osx pep8 git-extras pip python screen pyenv vagrant z httpie dircycle tmux docker golang dash vscode zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
```

`oh-my-zsh` successfully upgraded.

Do you have any suggestions where the is?

**Comment by r-darwish** [comment]
My suggestion is to start commenting stuff back in until it breaks again. This way you'll be able to know what exactly breaks the update.

**Comment by r-darwish** [comment]
Can you try sourcing this script in `.zlogin` instead of `.zshrc`?

**Comment by oleynikandrey** [comment]
> Can you try sourcing this script in `.zlogin` instead of `.zshrc`?

It fixed the problem.
