### ISSUE TITLE
Oh My ZSH started failing since some weeks

### ISSUE THREAD

**Issue by augustocdias** [r-darwish/topgrade#397]
[Oh My ZSH](https://github.com/ohmyzsh/ohmyzsh) doesn't work anymore and it doesn't show any error. Just the prompt to go to shell, retry or continue...

I'm running on latests MacOS.
I can update it manually through either `upgrade_oh_my_zsh` function or updating the git repo in the `~/.oh-my-zsh` folder.

**Comment by Kordyjan** [comment]
https://github.com/r-darwish/topgrade/issues/394#issuecomment-617262538 may be the reason.

**Comment by augustocdias** [comment]
Yeah. It is right... Very weird, but solved.
