### ISSUE TITLE
yarn version vs. yarn --version

### ISSUE THREAD

**Issue by SWallo** [r-darwish/topgrade#411]
**What did you expect to happen?**
Topgrade does not create a new version and git tag for my node project, if I run it from a node project directory.

**What actually happened?**
Topgrade does create a new version and git tag for my node project, if I run it in a node project directory. 
My guess is the check which yarn version is installed uses the wrong command, see:
https://github.com/r-darwish/topgrade/blob/5487a005b7a35424f2b72f79012413c563036a64/src/steps/node.rs#L56
It should be `yarn --version`.

The `yarn version` command updates the version of your package via the command line: 
https://classic.yarnpkg.com/en/docs/cli/version
or 
https://yarnpkg.com/cli/version (for yarn v2).

This is maybe connected to the issue #403. 

**Additional details:**
- Which operating system or Linux distribution are you using? MacOS Catalina
- How did you install Topgrade? via brew
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)

<details><pre>
Paste the output of `topgrade -v`
</pre></details>

**Comment by r-darwish** [comment]
Fixed in 89578a7fd98f7d41bf5bc1e3ee0371e2ca4c7105
