### ISSUE TITLE
Tmux session creation failed

### ISSUE THREAD

**Issue by dvogt23** [r-darwish/topgrade#413]
**What did you expect to happen?**
Start topgrade in a tmux session.

**What actually happened?**
Got an error: 
```
create window failed: index 1 in use
thread 'main' panicked at 'Error running topgrade in tmux: exit code: 1', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-4.5.0/src/steps/tmux.rs:92:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and a tmux session with window name "dummy" created.

**Additional details:**
- Which operating system or Linux distribution are you using? MacOs
- How did you install Topgrade? brew
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)

<details><pre>
 2020-05-22T06:08:30.020Z DEBUG topgrade::config > Configuration at $HOME/.config/topgrade.toml
 2020-05-22T06:08:30.022Z DEBUG topgrade::config > Loaded configuration: ConfigFile { pre_commands: None, commands: Some({"Update rust-analyzer": ". $HOME/.scripts/update-rust-analyzer"}), git_repos: None, predefined_git_repos: None, disable: Some([GitRepos, Gem]), remote_topgrades: None, ssh_arguments: None, git_arguments: None, tmux_arguments: None, set_title: None, assume_yes: None, yay_arguments: Some("--nodevel --ignore=jdk8"), no_retry: Some(true), run_in_tmux: Some(true), cleanup: None, notify_each_step: None, accept_all_windows_updates: None, only: None, composer: None, brew: None, linux: None }
 2020-05-22T06:08:30.022Z DEBUG topgrade         > Version: 4.5.0
 2020-05-22T06:08:30.022Z DEBUG topgrade         > OS: x86_64-apple-darwin
 2020-05-22T06:08:30.022Z DEBUG topgrade         > Args { inner: ["topgrade", "-v"] }
 2020-05-22T06:08:30.022Z DEBUG topgrade         > Binary path: Ok("/Users/dmitrijvogt/.cargo/bin/topgrade")
 2020-05-22T06:08:30.022Z DEBUG topgrade         > Self Update: false
 2020-05-22T06:08:30.023Z DEBUG topgrade::utils  > Detected "/usr/local/bin/tmux" as "tmux"
create window failed: index 1 in use
thread 'main' panicked at 'Error running topgrade in tmux: exit code: 1', $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-4.5.0/src/steps/tmux.rs:92:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

</pre></details>

**Comment by r-darwish** [comment]
I'm not sure what's the proper solution. It worked as expected for me as well until I implemented [this suggestion](https://github.com/r-darwish/topgrade/issues/275#issuecomment-623952288) because people complained, but now it's broken for me as well.

Which version of Tmux are you using?

**Comment by dvogt23** [comment]
> I'm not sure what's the proper solution. It worked as expected for me as well until I implemented [this suggestion](https://github.com/r-darwish/topgrade/issues/275#issuecomment-623952288) because people complained, but now it's broken for me as well.
> 
> Which version of Tmux are you using?

Actually I use tmux 3.1b. Maybe it would make sense to parameterize this (tmux arguments)  within the config file. With `-a` it would works 🤔

**Comment by r-darwish** [comment]
Yeah, I'm using 3.1b as well. I prefer that Topgrade will auto detect the correct settings instead of putting configuration options. I'll change it so that it will use `-a` when using tmux 3.1b or above.

**Comment by Arabus** [comment]
Got the same error unfortunately:

```
RUST_BACKTRACE=full topgrade
create window failed: index 1 in use
thread 'main' panicked at 'Error running topgrade in tmux: exit code: 1', src/steps/tmux.rs:92:5
stack backtrace:
   0:        0x10e9c0886 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1216a26f3ce3c114
   1:        0x10e982dbe - core::fmt::write::ha0ec7ad9e1aa7104
   2:        0x10e9c0639 - std::io::Write::write_fmt::he79f4e513ba146b5
   3:        0x10e9b63fa - std::panicking::default_hook::{{closure}}::hdf6a192f990c9642
   4:        0x10e9b6042 - std::panicking::rust_panic_with_hook::hbe9b3056eff949a6
   5:        0x10e9b5c2a - rust_begin_unwind
   6:        0x10ea2f07f - core::panicking::panic_fmt::hf1009b33c3b398fd
   7:        0x10ea2f145 - core::result::unwrap_failed::h09cf7a39453b742a
   8:        0x10e9ddb79 - topgrade::steps::tmux::run_in_tmux::h57fd79224e73f84d
   9:        0x10ea06a69 - topgrade::run::ha3b6fc4b1bd30005
  10:        0x10e9e646e - topgrade::main::h192dbb58b04bba63
  11:        0x10ea22276 - std::rt::lang_start::{{closure}}::h6c4918d94ae8315c
  12:        0x10e9e618b - main
```

It appears to me this setting affects it:

```
set -g base-index 1
setw -g pane-base-index 1
```
Because when I comment it out, topgrade works just fine.

**Comment by r-darwish** [comment]
Thanks @Arabus, it makes sense as I have this set in my configuration as well. I'll try to think about a proper solution.
