### ISSUE TITLE
topgrade should ask user before doing big updates/upgrade in macOS

### ISSUE THREAD

**Issue by AWHubGit** [r-darwish/topgrade#419]
running topgrade on macOS it should ask user for confirmation before doing major updates/upgrades e.g. macOS 10.14.6 to 10.15.5. And even within 10.14.xxx / 10.15.xxx.

I have installed topgrade by homebrew on macOS 10.15.xxx. I run topgrade as usual, wasn't aware there is 10.15.5 available and topgrade started immediately to install 10.15.5. I had to wait a long time until upgrade was done. There topgrade should ask user before doing big updates/upgrade in macOS.

**Comment by r-darwish** [comment]
fixed in #433

**Comment by AWHubGit** [comment]
topgrade is TOP! I wish topgrade were available in other distros. Everywhere!
