### ISSUE TITLE
oh-my-Zsh getting stuck

### ISSUE THREAD

**Issue by ben2talk** [r-darwish/topgrade#434]
Topgrade runs through everything smoothly until I installed oh-my-Zsh.
`―― 20:23:34 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Orphaned AUR Packages:  pcmanfm-gtk3-root
 -> Flagged Out Of Date AUR Packages:  xdg-su
 there is nothing to do

―― 20:23:39 - oh-my-zsh ―――――――――――――――――――――――――――――――――――――――――――
`
I waited 5 minutes.
Ctrl+C lets it continue:
```
―― 20:23:34 - System update ――――――――――――――――――――――――――――――――――――――――――――――――――――
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Orphaned AUR Packages:  pcmanfm-gtk3-root
 -> Flagged Out Of Date AUR Packages:  xdg-su
 there is nothing to do

―― 20:23:39 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――

```
...

Requires CTRL+C to continue with Oh-my-zsh update.
The same issue occurs running topgrade -n (Dry run).

- How did you install Topgrade?
2 aur/topgrade 4.7.1-1 (+15 0.34%) (Installed)

<details><pre>
Paste the output of `topgrade -v`
</pre></details>
―― 20:28:27 - System update ――
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Orphaned AUR Packages:  pcmanfm-gtk3-root
 -> Flagged Out Of Date AUR Packages:  xdg-su
 there is nothing to do
―― 20:28:34 - oh-my-zsh ――
Updating Oh My Zsh
―― 20:28:38 - Flatpak User Packages ――
Looking for updates…
Nothing to do.
Looking for updates…
Nothing to do.
―― 20:28:38 - snap ――

[0m[?25h[K―― 20:28:38 - Firmware upgrades ――
―― 20:28:38 - Summary ――
System update: OK
oh-my-zsh: FAILED
Flatpak: OK
snap: OK
Firmware upgrades: OK
―― 20:28:52 - System update ――
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Orphaned AUR Packages:  pcmanfm-gtk3-root
 -> Flagged Out Of Date AUR Packages:  xdg-su
 there is nothing to do
―― 20:28:59 - oh-my-zsh ――
Updating Oh My Zsh
Current branch master is up to date.
         __                                     __   
  ____  / /_     ____ ___  __  __   ____  _____/ /_  
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ 
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / 
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  
                        /____/                       
Hooray! Oh My Zsh has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh
Get your Oh My Zsh swag at: https://shop.planetargon.com/collections/oh-my-zsh
―― 20:29:55 - Flatpak User Packages ――
Looking for updates…
Nothing to do.
Looking for updates…
Nothing to do.
―― 20:29:55 - snap ――

[0m[?25h[K―― 20:29:55 - Firmware upgrades ――
―― 20:29:55 - Summary ――
System update: OK
oh-my-zsh: OK
Flatpak: OK
snap: OK
Firmware upgrades: OK

Ran topgrade -v >> topgrade.txt and had to press CTRL+C to continue with oh-my-zsh.

**Comment by ben2talk** [comment]
I can't say why, I just ran ~ >>> upgrade_oh_my_zsh                                                                               
After doing this. Topgrade now completes without any issue.

**Comment by ffloimair** [comment]
Seeing the same issue as well but with topgrade 4.8.0

**Comment by ffloimair** [comment]
and running upgrade_oh_my_zsh doesn't do anything for me. The issue is still there. I have to press CRTL+C everytime then it will continue with updating oh-my-zsh.
It seems like topgrade is stuck somewhere between printing out oh-my-zsh "headline" and actually running upgrade_oh_my_zsh, since after pressing CTRL+C everything does work as expected.

**Comment by ffloimair** [comment]
`―― 18:48:35 - Brew ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Updated Homebrew from 0dbbefe33f to 4fa540b259.
Updated 1 tap (homebrew/cask).
No changes to formulae.
Updating Homebrew...
Updating Homebrew...
==> No Casks to upgrade

―― 18:49:01 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
^CUpdating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch              master     -> FETCH_HEAD
Current branch master is up to date.
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/
Hooray! Oh My Zsh has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh
Get your Oh My Zsh swag at: https://shop.planetargon.com/collections/oh-my-zsh

―― 18:49:19 - Go ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

―― 18:49:22 - Node Package Manager ―――――――――――――――――――――――――――――――――――――――――――――

`

**Comment by ffloimair** [comment]
please reopen

**Comment by r-darwish** [comment]
Can you please run `topgrade -v`?

**Comment by ffloimair** [comment]
Seems like it's stuck where it asks "would you like to upgrade" which is hidden from view in a normal run.
Here is the snippet (userdate anonymized) from oh-my-zsh
```
 2020-06-23T22:25:53.009Z DEBUG topgrade::runner     > Step "oh-my-zsh"
 2020-06-23T22:25:53.009Z DEBUG topgrade::utils      > Detected "/usr/local/bin/zsh" as "zsh"
 2020-06-23T22:25:53.009Z DEBUG topgrade::utils      > Path "/Users/***/.oh-my-zsh" exists

―― 00:25:53 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
^C 2020-06-23T22:26:19.816Z TRACE topgrade::executor   > Output of "zsh" "-i" "-c" "echo -n $ZSH_CUSTOM": Output { status: ExitStatus(ExitStatus(0)), stdout: "[oh-my-zsh] Would you like to update? [Y/n] /Users/***/.oh-my-zsh/custom", stderr: "" }
 2020-06-23T22:26:19.816Z DEBUG topgrade::steps::zsh > oh-my-zsh custom dir: [oh-my-zsh] Would you like to update? [Y/n] /Users/***/.oh-my-zsh/custom/plugins
 2020-06-23T22:26:19.817Z DEBUG topgrade::executor   > Running "sh" "/Users/***/.oh-my-zsh/tools/upgrade.sh"
Updating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch              master     -> FETCH_HEAD
Current branch master is up to date.
         __                                     __
  ____  / /_     ____ ___  __  __   ____  _____/ /_
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/
                        /____/
Hooray! Oh My Zsh has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on twitter: https://twitter.com/ohmyzsh
Get your Oh My Zsh swag at: https://shop.planetargon.com/collections/oh-my-zsh
 2020-06-23T22:26:20.964Z DEBUG topgrade::runner     > Step "fisher"
 2020-06-23T22:26:20.965Z DEBUG topgrade::utils      > Cannot find "fish"
 2020-06-23T22:26:20.965Z DEBUG topgrade::runner     > Step "tmux"
 2020-06-23T22:26:20.965Z DEBUG topgrade::utils      > Path "/Users/***/.tmux/plugins/tpm/bin/update_plugins" doesn't exist
 2020-06-23T22:26:20.965Z DEBUG topgrade::runner     > Step "TLDR"
 2020-06-23T22:26:20.966Z DEBUG topgrade::utils      > Cannot find "tldr"
 2020-06-23T22:26:20.966Z DEBUG topgrade::runner     > Step "rustup"
 2020-06-23T22:26:20.967Z DEBUG topgrade::utils      > Cannot find "rustup"
 2020-06-23T22:26:20.967Z DEBUG topgrade::runner     > Step "cargo"
 2020-06-23T22:26:20.967Z DEBUG topgrade::utils      > Cannot find "cargo-install-update"
 2020-06-23T22:26:20.967Z DEBUG topgrade::runner     > Step "Flutter"
 2020-06-23T22:26:20.967Z DEBUG topgrade::utils      > Cannot find "flutter"
 2020-06-23T22:26:20.967Z DEBUG topgrade::runner     > Step "Go"
 2020-06-23T22:26:20.968Z DEBUG topgrade::utils      > Detected "/usr/local/bin/go" as "go"
 2020-06-23T22:26:20.968Z DEBUG topgrade::utils      > Path "/Users/***/go" exists
```

**Comment by ffloimair** [comment]
I can confirm that this is fixed now. Thanks!
