### ISSUE TITLE
Topgrade at crates.io still stays at version 4.5.0

### ISSUE THREAD

**Issue by omasanori** [r-darwish/topgrade#435]
**What did you expect to happen?**

The latest version is available not only on GitHub releases, but also on crate.io.

**What actually happened?**

While the latest release is available on GitHub releases, crate.io still provides an older one, version 4.5.0.

**Additional details:**

I confirmed with Ubuntu 18.04 LTS, and topgrade is installed using Cargo.

**Comment by r-darwish** [comment]
Sorry, I keep forgetting to upload to crates.io. I just uploaded the most recent version.

**Comment by omasanori** [comment]
Thank you for your rapid response, and making this tool!
