### ISSUE TITLE
Auto-upgrade pip

### ISSUE THREAD

**Issue by alejandro5042** [r-darwish/topgrade#437]
**I want to suggest a new step**

***Which tool is this about? Where is its repository?***
Upgrade [pip](https://pip.pypa.io/en/stable/) (the Python package manager)

***Which operating systems are supported by this tool?***
Anywhere Python runs (so almost everywhere).

***What should Topgrade do to figure out if the tool needs to be invoked?***
Not sure, but it is possible because pip gives a warning if it is out of date:

```
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

***Which exact commands should Topgrade run?***

```
python -m pip install --upgrade pip
```

**Comment by r-darwish** [comment]
This is a bit problematic for several reasons:

1. You won't always have permissions to update pip, especially in Linux. Trying to upgrade pip with sudo is a bad idea
2. You probably use virtual environments like any python developer. Each virtual environment has its own copy of pip, and Topgrade cannot detect all your virtual environments.

I don't think this feature suits general availability, so I suggest that you use the configuration to add a custom command to upgrade pip in hosts which you see appropriate.

**Comment by alejandro5042** [comment]
Makes sense. Thank you for looking into it and replying back :)
