### ISSUE TITLE
unable to edit an invalid config

### ISSUE THREAD

**Issue by greaka** [r-darwish/topgrade#442]
**What did you expect to happen?**
I used an invalid key in my config and expected to be able to change it back

**What actually happened?**
Topgrade is just throwing an error message

**Additional Details**
![image](https://user-images.githubusercontent.com/2805834/85292007-8f941a80-b49b-11ea-913c-6394bf9a1eee.png)

<details><pre>
/mnt/d/Git > 1 topgrade -v
Error: Error reading the configuration
Caused by: unknown variant `npm`, expected one of `system`, `gitrepos`, `vim`, `emacs`, `gem`, `node`, `sdkman`, `remotes`, `rustup`, `cargo`, `shell` for key `disable` at line 1 column 1
</pre></details>

**Comment by r-darwish** [comment]
This should have been fixed in 1182675170d40601768d67cd47b5e2a93dfeb6b4. Are you using the latest version of Topgrade?

**Comment by greaka** [comment]
Ah, found the issue. My wsl topgrade seems to not being upgraded when running topgrade from powershell. They are both installed via cargo.

I'm sorry that I didn't find the other issue.
