### ISSUE TITLE
npm's capitalization is incorrect

### ISSUE THREAD

**Issue by jungaretti** [r-darwish/topgrade#443]
**What did you expect to happen?**
Topgrade should report `npm: OK` in its post-upgrade summary.

**What actually happened?**
Topgrade reports `NPM: OK` in its post-upgrade summary.

**Additional details:**

- Using macOS 10.15.5
- Installed Topgrade with Homebrew
- https://docs.npmjs.com/about-npm/

**Comment by jungaretti** [comment]
Tiny refinement 🤓 check out PR #444

**Comment by r-darwish** [comment]
Merged #444
