### ISSUE TITLE
topgrade does not detect Neovim plugins managed by vim-plug if defined outside of init.vim

### ISSUE THREAD

**Issue by openjck** [r-darwish/topgrade#448]
**I want to suggest some general feature**

I'd to request that topgrade document the how to define a custom path. The feature is listed on the [wiki page](https://github.com/r-darwish/topgrade/wiki/Step-list), but I'm not sure how to use it. I can't find documentation here or in the example config file.

I list my Neovim plugins in a separate file named *plugins.vim*, so if this feature would help topgrade to find my plugins and upgrade them, I'd love to use it.

**Comment by r-darwish** [comment]
From the example file:
```toml
#[git]
# Additional git repositories to pull
#repos = [
#    "~/src/*/",
#    "~/.config/something"
#]
```

Is this what you mean?

**Comment by openjck** [comment]
I'm not exactly sure. The issue I'm having is that my Neovim plugins are configured in a file called *~/.config/nvim/init/plugins.vim* which is included from *~/.config/nvim/init.vim*. As a result, or perhaps due to another issue, topgrade doesn't seem to find it and doesn't upgrade my Neovim plugins. Is there a way to make topgrade aware of my *~/.config/nvim/init/plugins.vim* file so that it does upgrade my Neovim plugins?

**Comment by r-darwish** [comment]
Topgrade tries to detect which Vim plugin system you're using (It supports Plug, Vundle, NeoBundle and Dein) and then run the plugin's system update method. Perhaps to does not detect your plugin system. Can you please publish your neovim configuration?

**Comment by openjck** [comment]
Sure thing. Here's a minimal reproduction of the issue:

https://github.com/openjck/bug-demo-topgrade-448
