### ISSUE TITLE
Will topgrade update globally installed NPM packages?

### ISSUE THREAD

**Issue by maxwelljordanwhite** [r-darwish/topgrade#453]

**Comment by openjck** [comment]
The [wiki](https://github.com/r-darwish/topgrade/wiki/Step-list), which is linked from the README, explains that topgrade will:

> Run `npm update -g`. In Unix systems other then macOS the step will be performed only if `npm root -g` is a path inside your home directory.

[This comment](https://github.com/r-darwish/topgrade/issues/303#issuecomment-579115893) explains why there is a restriction on running `npm update -g`.

**Comment by r-darwish** [comment]
@openjck thanks for helping out 👍

**Comment by maxwelljordanwhite** [comment]
@openjck @r-darwish Thanks! Not sure how I missed this.
