### ISSUE TITLE
Idea: New "ignore_fail"/"warning" state for unreliable steps

### ISSUE THREAD

**Issue by derphilipp** [r-darwish/topgrade#455]
**I want to suggest some general feature**
Topgrade should...

Topgrade should be configurable to "ignore" certain failing steps, but try it anyway.

Example: Some steps [1] can have failing updates in the installed packages. Nontheless I want to *try* to update it every time i run topgrade.
But every time topgrade asks be about that failing step (retry?) and displays it as failed in the end.
It would be nice to specify to ignore a failing step: Do perform the step, but if it fails, don't ask me about retrying, nor show it as an error, but only as a warning.

In the end result it should show up as positive "ok" (if nothing failed at all) or yellow "failed, but ignored"/"warning" state.

[1] Example: 
  - programming languages (go, rust, etc.) with unstable packages. I want to update them, but they can fail from time to time.
  - tasks that depend on unreliable network connectivity etc.

**Comment by openjck** [comment]
There is a `--no-retry` option (`no_retry = true` in the config file). I don't think it can be configured on a task-by-task basis.

**Comment by r-darwish** [comment]
@openjck correct, but this idea makes sense to me. I will check if it doesn't take too much to implement.
