### ISSUE TITLE
Self update doesn't work on Windows

### ISSUE THREAD

**Issue by mati865** [r-darwish/topgrade#458]
**What did you expect to happen?**
Topgrade should update itself successfully.

**What actually happened?**
It fails with:
```
Package         Installed  Latest   Needs update
topgrade        v4.8.0     v4.9.0   Yes
cargo-update    v3.0.0     v3.0.0   No
<other crates>

Updating topgrade
  Downloaded topgrade v4.9.0
  <build log>
   Replacing C:\Users\mateusz\.cargo\bin\topgrade.exe
error: failed to move `C:\Users\mateusz\.cargo\bin\cargo-installgExTkS\topgrade.exe` to `C:\Users\mateusz\.cargo\bin\topgrade.exe`

Caused by:
  Access denied. (os error 5)
```

**Additional details:**
- Which operating system or Linux distribution are you using?
Windows 10 Pro 2004
- How did you install Topgrade?
`cargo install topgrade`
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)

<details><pre>
 2020-06-30T09:29:08.334Z DEBUG topgrade::executor   > Running "C:\\Users\\mateusz\\.cargo\\bin\\cargo-install-update.EXE" "install-update" "--git" "--all"
    Updating registry 'https://github.com/rust-lang/crates.io-index'

Package         Installed  Latest   Needs update
topgrade        v4.8.0     v4.9.0   Yes
cargo-update    v3.0.0     v3.0.0   No
<other crates>

Updating topgrade
    Updating crates.io index
  Installing topgrade v4.9.0
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.9
   Compiling proc-macro2 v1.0.18
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.33
   Compiling cfg-if v0.1.10
   Compiling winapi-build v0.1.1
   Compiling memchr v2.3.3
   Compiling version_check v0.9.2
   Compiling lazy_static v1.4.0
   Compiling autocfg v1.0.0
   Compiling libc v0.2.71
   Compiling log v0.4.8
   Compiling slab v0.4.2
   Compiling pin-project-internal v0.4.22
   Compiling winapi v0.2.8
   Compiling getrandom v0.1.14
   Compiling proc-macro-nested v0.1.6
   Compiling unicode-segmentation v1.6.0
   Compiling bitflags v1.2.1
   Compiling once_cell v1.4.0
   Compiling serde_derive v1.0.114
   Compiling regex-syntax v0.6.18
   Compiling proc-macro-hack v0.5.16
   Compiling futures-sink v0.3.5
   Compiling futures-core v0.3.5
   Compiling unicode-width v0.1.8
   Compiling serde v1.0.114
   Compiling iovec v0.1.4
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.5
   Compiling ppv-lite86 v0.2.8
   Compiling quick-error v1.2.3
   Compiling anyhow v1.0.31
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling encode_unicode v0.3.6
   Compiling topgrade v4.9.0
   Compiling bytes v0.5.5
   Compiling pin-project-lite v0.1.7
   Compiling glob v0.3.0
   Compiling thread_local v1.0.1
   Compiling kernel32-sys v0.2.2
   Compiling ws2_32-sys v0.2.1
   Compiling futures-task v0.3.5
   Compiling heck v0.3.1
   Compiling futures-channel v0.3.5
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling proc-macro-error-attr v1.0.3
   Compiling proc-macro-error v1.0.3
   Compiling rand_core v0.5.1
   Compiling aho-corasick v0.7.13
   Compiling rand_chacha v0.2.2
   Compiling quote v1.0.7
   Compiling rand v0.7.3
   Compiling regex v1.3.9
   Compiling atty v0.2.14
   Compiling winapi-util v0.1.5
   Compiling net2 v0.2.34
   Compiling dirs-sys v0.3.5
   Compiling socket2 v0.3.12
   Compiling terminal_size v0.1.12
   Compiling time v0.1.43
   Compiling remove_dir_all v0.5.3
   Compiling dirs v2.0.2
   Compiling directories v2.0.2
   Compiling clicolors-control v1.0.1
   Compiling clap v2.33.1
   Compiling tempfile v3.1.0
   Compiling termcolor v1.1.0
   Compiling same-file v1.0.6
   Compiling shellexpand v2.0.0
   Compiling console v0.10.3
   Compiling miow v0.3.5
   Compiling chrono v0.4.11
   Compiling walkdir v2.3.1
   Compiling env_logger v0.7.1
   Compiling syn-mid v0.5.0
   Compiling pretty_env_logger v0.4.0
   Compiling miow v0.2.1
   Compiling mio v0.6.22
   Compiling futures-macro v0.3.5
   Compiling thiserror-impl v1.0.20
   Compiling strum_macros v0.18.0
   Compiling mio-named-pipes v0.1.6
   Compiling tokio v0.2.21
   Compiling thiserror v1.0.20
   Compiling which v4.0.1
   Compiling structopt-derive v0.4.8
   Compiling strum v0.18.0
   Compiling pin-project v0.4.22
   Compiling futures-util v0.3.5
   Compiling structopt v0.3.15
   Compiling futures-executor v0.3.5
   Compiling futures v0.3.5
   Compiling toml v0.5.6
    Finished release [optimized] target(s) in 1m 37s
   Replacing C:\Users\mateusz\.cargo\bin\topgrade.exe
error: failed to move `C:\Users\mateusz\.cargo\bin\cargo-installORuk8I\topgrade.exe` to `C:\Users\mateusz\.cargo\bin\topgrade.exe`

Caused by:
  Odmowa dost─Öpu. (os error 5)

Updated 0 packages.
Failed to update topgrade.
</pre></details>

Running in MSYS2 MINGW64 shell if that matters.

**Comment by r-darwish** [comment]
There's really nothing that I can do here. It's a [limitation of Windows](https://github.com/r-darwish/topgrade/wiki/Windows).

The binaries released in Github contain a self update feature which works in Windows.

**Comment by mati865** [comment]
Cargo-update has workaround that works well on Windows:
https://github.com/nabijaczleweli/cargo-update#self-update

**Comment by r-darwish** [comment]
It uses that hack to update itself, just like Topgrade does. However, cargo-install doesn't know that it's being run by Topgrade, which makes Topgrade locked.

**Comment by r-darwish** [comment]
There is something we can try, however. I can add a configuration option that when set, causes Topgrade to move itself to the temp directory when it's run, and then move it back when it finished if it does not detect a file in its former location. This will require you to change your configuration as it's a bad idea to make it a default behavior.

**Comment by mati865** [comment]
> I can add a configuration option that when set, causes Topgrade to move itself to the temp directory when it's run, and then move it back when it finished if it does not detect a file in its former location. This will require you to change your configuration as it's a bad idea to make it a default behavior.

Sounds good!
