### ISSUE TITLE
Topgrade self update error

### ISSUE THREAD

**Issue by nshtg** [r-darwish/topgrade#462]
When running topgrade un Ubuntu 20.04 it throws an error on trying to selfupdate:

```
Self update error: ReleaseError: No asset found for target: `x86_64-unknown-linux-musl``
```

The newest release (5.0.0) is missing the musl binaries.

**Comment by r-darwish** [comment]
Fixed

**Comment by nshtg** [comment]
Thank you!

**Comment by nshtg** [comment]
@r-darwish 
5.7.1 same error again

**Comment by r-darwish** [comment]
It takes some time from Travis to build all binaries once I release a version. The binaries are there now
