### ISSUE TITLE
Why is Brew Cask getting run on linux?

### ISSUE THREAD

**Issue by modularTaco** [r-darwish/topgrade#467]
As far as I know brew casks are only supported on MacOS (https://github.com/Linuxbrew/brew/issues/742) but since i installed homebrew, topgrade is trying to install brew cask on my fedora system (on any unix system, as it seems):

 https://github.com/r-darwish/topgrade/blob/5c7f04c2cfaaa889b298413f13a2f3fb60f5720f/src/main.rs#L151

 I couldn't find any configuration option to disable brew casks, only brew in general

![image](https://user-images.githubusercontent.com/37046961/87004567-e8fb8980-c1bd-11ea-91fb-bb68265995e8.png)

**Comment by r-darwish** [comment]
To be honest I was not sure whether it's intended to be supported in Linux or not. I'll make it a macOS only step. Thanks for clarifying.
