### ISSUE TITLE
please add a chocolatey (silent) installer for Topgrade

### ISSUE THREAD

**Issue by TheBigBear** [r-darwish/topgrade#473]
chocolatey should be able to install topgrade - step towards achieving this goal is to create a silent installer. once you have a silent installer you can setup a chocolatey installer pgk for topgrade. see https://chocolatey.org/docs/create-packages

**Comment by bingalls** [comment]
Fwiw, Chocolatey-Gui allows you to upgrade all Chocolatey packages with a single click. I'm sure this maps to a CLI option.
Also, I don't see a CLI means to upgrade Microsoft system updates, as I cannot find a *.msc snap-in
* https://mikerodionov.com/2012/10/list-of-windows-mmc-snap-ins-and-control-panel-applets/
* https://www.ghacks.net/2015/11/27/mmcsnapinsview-lists-all-windows-mmc-snap-ins/

If this means that Topgrade cannot unify Chocolatey with System Updates nor The Microsoft Store, then Topgrade cannot add value, and this ticket should be closed.

**Comment by r-darwish** [comment]
@TheBigBear I uploaded an MSI. Now we need someone to create an maintain the chocolatey package. I'm not sure I want to do that.

**Comment by r-darwish** [comment]
I'm closing this one as packaging isn't done by myself. If anyone wishes to package Topgrade for Choco then they are welcome to do so.
