### ISSUE TITLE
Consider supporting sheldon

### ISSUE THREAD

**Issue by xaocon** [r-darwish/topgrade#484]
**I want to suggest a new step**
sheldon is a general purpose shell plugin manager

***Which tool is this about? Where is its repository?***
sheldon, https://github.com/rossmacarthur/sheldon

***Which operating systems are supported by this tool?***
Generally all the ones topgrade currently supports

***What should Topgrade do to figure out if the tool needs to be invoked?***
Check for sheldon in the path?

***Which exact commands should Topgrade run?***
I don't think a lib is used for git in topgrade so I guess you'd check some env vars, find the correct base for repos, walk a tree looking for `.git` then `git pull`. Maybe just run `sheldon lock` either way.

**I want to suggest some general feature**

**More information**
I'm not a rust expert but have been trying to learn more and would be happy to make a PR if someone with commit powers could tell me that they would accept a particular functionality and OK a broad outline of implementation.

**Comment by r-darwish** [comment]
I think that the best method would be:
1. Add `~/.sheldon/` to the list of predefined git repositories. This will pull your sheldon configuration from git (if it is checked into git)
2. Run `sheldon lock`

What do you think?

**Comment by xaocon** [comment]
I was really talking about repos downloaded by sheldon though I think that's a good idea as well (with the caveat that we should probably look at ENV vars to see where the sheldon dir is.) As far as I know `sheldon lock` by itself doesn't update the repos it has downloaded and linked and a quick test seems to support that, though I could be missing something. Under normal circumstances that would mean doing something like `cd ~/.sheldon; git pull; sheldon lock; cd ~/.sheldon/repos; for REPO in **/.git/..; do (cd "$REPO"; git pull); done; sheldon lock`.

**Comment by r-darwish** [comment]
It feels somewhat odd that sheldon is a package manager that have no command for upgrading installed packages. Is this the actual recommended way to keep sherldon installed dependencies up-to-date?

**Comment by xaocon** [comment]
I'm not sure to be honest. I'll ask them about recommendations. Maybe
there's something I don't understand currently. There is a reinstall flag
that would probably do it. There may be some concern overwriting local
changes or something.

**Comment by xaocon** [comment]
Ahh, https://github.com/rossmacarthur/sheldon/issues/61

**Comment by r-darwish** [comment]
> Ahh, [rossmacarthur/sheldon#61](https://github.com/rossmacarthur/sheldon/issues/61)

I think I rather wait for this one to be resolved

**Comment by xaocon** [comment]
It has been resolved. `sheldon lock --update`. Cargo updates have been pushed so topgrade should get the install for most people.
