### ISSUE TITLE
Don't explicitly call needrestart

### ISSUE THREAD

**Issue by BjoernDaase** [r-darwish/topgrade#485]
At least when using `dnf` on Fedora 32 (I have now clue how other package managers deal with that), `needrestart` is automatically triggered by `dnf` when it finished its transaction.  

However, due to `needrestart` being called explicitly at the last `topgrade` step, it is called twice. This means `needrestart` is also called every time even though there was no package change by `dnf`.

Therefore I would suggest to not call `needrestart` explicitly by `topgrade`.

**Comment by r-darwish** [comment]
I don't think other package managers call `needrestart`. I can make this step skipped in Fedora.

**Comment by BjoernDaase** [comment]
Sounds like a good idea :+1:
