### ISSUE TITLE
Add flag for limit execution to specific remote hosts

### ISSUE THREAD

**Issue by panticz** [r-darwish/topgrade#491]
**I want to suggest some general feature**
Topgrade supports remote updates on hosts specified by remote_topgrades. It would be useful to by able so limit the execution only to specific hosts / groups (preferably with RegEx) with a flag, e.g.:

`--only-remote www*-stage-node

(similar to ansible --limit flag, see: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html#patterns-and-ansible-playbook-flags)

**Comment by r-darwish** [comment]
I'm debating between regex, which is more feature rich, and glob, which is more simple. Your example actually uses a glob and not regex.

**Comment by panticz** [comment]
Glob should be sufficient for operators and its easier to use because no masking is required
