### ISSUE TITLE
Read topgrade configuration from local directory

### ISSUE THREAD

**Issue by panticz** [r-darwish/topgrade#494]
**I want to suggest some general feature**
Try to read topgrade configuration from local directory (if available) and override inherited settings from ~/.config/topgrade.toml

**More information**
This will allow to override topgrade settings by directory with can contain specific settings for a environment.

See also Ansible Configuration Settings:
https://docs.ansible.com/ansible/latest/reference_appendices/config.html#the-configuration-file

**Comment by panticz** [comment]
Alternatively, a parameter to configure path to a topgrade configuration file would also be possible in order to be able to use different configurations

**Comment by r-darwish** [comment]
There's `--config`. Doesn't it do what you asked?
