### ISSUE TITLE
Is it possible to create sudoers rules so topgrade can get root passwordless?

### ISSUE THREAD

**Issue by Popkornium18** [r-darwish/topgrade#497]
This is technically not a bug report, but more like a support request. Not sure if this is the right place for this.

So once you add a decent amount of remote machines it gets pretty annoying to type the sudo password for each machine.
Since it is possible to configure sudo in a way that certain commands don't require a password for certain users, I was wondering if it is possible to create a sudo config that allows topgrade to get root privileges without a password?

If so, which rules would be necessary? A seperate one for each step that requires root? How could I find out which commands are actually run by topgrade, in order to create these rules?

**Additional details:**
Arch Linux (Topgrade installed from AUR)

**Comment by r-darwish** [comment]
You can run `topgrade -n` to see the list of commands that Topgrade will execute

**Comment by Popkornium18** [comment]
Ah nice, that should be enough to figure it out
