### ISSUE TITLE
Error detecting current distribution: Unknown Linux Distribution

### ISSUE THREAD

**Issue by SecretAgentAgentX** [r-darwish/topgrade#506]
I ran topgrade twice in a row to see if "Error detecting current distribution: Unknown Linux Distribution" was just a one off, and looks like it's not. I had has just run it not even an hour earlier without issue. Anyone have any idea what might be causing this? thanks

    Garuda Linux 5.8.3-zen1-1-zen x86_64

     08:30:29  alienprober@TheMothership  ~ 
    $ topgrade
    Error detecting current distribution: Unknown Linux Distribution

    ―― 08:30:36 - Flatpak User Packages ――――――――――――――――――――――――――――――――――――――――――――
    Looking for updates…
    Nothing to do.
    Looking for updates…
    Nothing to do.

    ―― 08:30:37 - snap ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    [sudo] password for alienprober:                      
    All snaps up to date.

    ―― 08:30:45 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
    Firmware metadata last refresh: 4 hours ago. Use --force to refresh again.
    • ST3000DM001-1E6166 has no available firmware updates
    • Samsung SSD 850 EVO 120GB has no available firmware updates
    • System Firmware has no available firmware updates
    • Unifying Receiver has no available firmware updates
    • Viper M.2 VPN100 has no available firmware updates
    • WDC WD10EARS-00Y5B1 has no available firmware updates
    • WL3000GSA6454 has no available firmware updates
    No updatable devices

    ―― 08:30:45 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    Flatpak: OK
    snap: OK
    Firmware upgrades: OK

     08:30:45  alienprober@TheMothership  ~  9s 
    $ topgrade
    Error detecting current distribution: Unknown Linux Distribution

    ―― 08:31:16 - Flatpak User Packages ――――――――――――――――――――――――――――――――――――――――――――
    Looking for updates…
    Nothing to do.
    Looking for updates…
    Nothing to do.

    ―― 08:31:16 - snap ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    All snaps up to date.

    ―― 08:31:16 - Firmware upgrades ――――――――――――――――――――――――――――――――――――――――――――――――
    Firmware metadata last refresh: 4 hours ago. Use --force to refresh again.
    • ST3000DM001-1E6166 has no available firmware updates
    • Samsung SSD 850 EVO 120GB has no available firmware updates
    • System Firmware has no available firmware updates
    • Unifying Receiver has no available firmware updates
    • Viper M.2 VPN100 has no available firmware updates
    • WDC WD10EARS-00Y5B1 has no available firmware updates
    • WL3000GSA6454 has no available firmware updates
    No updatable devices

    ―― 08:31:16 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
    Flatpak: OK
    snap: OK
    Firmware upgrades: OK

     08:31:17  alienprober@TheMothership  ~ 
    $ 

I'm running Garuda KDE which is a Arch based distro.

https://garudalinux.in/

**Comment by idanski** [comment]
Hey, can you attach the content of `/etc/os-release`

**Comment by sgse** [comment]
```
$ cat /etc/os-release                                                                                                    [1]
NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.garudalinux.in/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://forum.garudalinux.in/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=garudalinux
```

**Comment by idanski** [comment]
@sgse :
I opened a PR - https://github.com/r-darwish/topgrade/pull/507
If you can test this branch it will be awesome. anyway I'll wait for @r-darwish to review it.

**Comment by kkga** [comment]
Having the same output on Artix (https://artixlinux.org/)

**Comment by r-darwish** [comment]
Looks good to me if it works

**Comment by idanski** [comment]
@kkga can post here the output of `cat /etc/os-release` as well and I'll add it to the PR?

**Comment by SecretAgentAgentX** [comment]
@sgse  did you install and test to see if you get the sane error message?

```
$ cat /etc/os-release
NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.garudalinux.in/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://forum.garudalinux.in/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
LOGO=garudalinux
```

**Comment by SecretAgentAgentX** [comment]
How about not closing a issue till it's actually resolved? Just came to ask about progress on this. THanks

**Comment by r-darwish** [comment]
We made a change according to the `/etc/os-release` and merged it. We also tested it in Artix. Does it not work in Garuda?

**Comment by SecretAgentAgentX** [comment]
No it's still not working with Garuda at this point. Just uninstalled and used the build files from AUR after testing, and even using the build files still the same.

**Comment by r-darwish** [comment]
We did not publish a version to AUR. Can you test the master branch of this repository?

**Comment by SecretAgentAgentX** [comment]
Topgrade doesn't install using:

git clone https://github.com/r-darwish/topgrade.git
cd topgrade
makepkg -si
