### ISSUE TITLE
add update-usbids and update-pciids

### ISSUE THREAD

**Issue by rcampbel3** [r-darwish/topgrade#51]
Hi,

Would be nice to add in support (if found) for:

sudo /usr/sbin/update-usbids
and
sudo /usr/sbin/update-pciids

to pull the latest snapshots for each.

Thanks!

**Comment by r-darwish** [comment]
I'm not sure whether it's actually recommended to run these scripts. `update-pciids` seems to be included in Arch Linux, but they [claim](https://bugs.archlinux.org/task/29031#comment94600) to have removed it in the past. I saw no documentation in the Arch wiki about these scripts, and the files that they update seems to be updated by the package manager, so I'm afraid I'll have to close this. You can still use the configuration file to run these steps as custom commands.

**Comment by rcampbel3** [comment]
An 'update everything' tool, should update things like this IMHO. Other distros recommend running these, and they fix problems. At worst, I don't see how it could hurt.

http://www.linux-usb.org/usb.ids

Ubuntu recommends this in a few places:

https://help.ubuntu.com/community/WirelessTroubleshootingProcedure
https://askubuntu.com/questions/874694/usb-drives-not-detected-after-fresh-install-ubuntu-16-04-1
https://ubuntuforums.org/showthread.php?t=2381785
https://www.quora.com/I-have-a-desktop-running-Ubuntu-Linux-14-04-Which-graphics-card-is-running-in-my-system

Debian: 
https://wiki.debian.org/HowToIdentifyADevice/USB

**Comment by r-darwish** [comment]
You made valid points, so I read these scripts. Both of them download their files over plain HTTP. There are is no checksum or signature checking. Running such scripts on a regular basis is dangerous.
