### ISSUE TITLE
Could you please add oh-my-fish?

### ISSUE THREAD

**Issue by niheaven** [r-darwish/topgrade#513]
**I want to suggest a new step**
***Which tool is this about? Where is its repository?***
- oh-my-fish
- The Fish Shell Framework
- https://github.com/oh-my-fish/oh-my-fish
***Which operating systems are supported by this tool?***
- Linux/Mac/WSL
***What should Topgrade do to figure out if the tool needs to be invoked?***
- `omf update`
***Which exact commands should Topgrade run?***
- None

**Comment by niheaven** [comment]
`omf` still cannot update.

![image](https://user-images.githubusercontent.com/5832170/93047079-297bf580-f68e-11ea-8f9e-10916c8071f0.png)

**Comment by r-darwish** [comment]
Can you post the output of `which omf`?

**Comment by niheaven** [comment]
`which omf` outputs NULL.

`omf` is just a function of fish shell, and is located in `.local/share/omf/pkg/omf/functions/omf.fish`.

Maybe it could be checked by `omf -v`?
