### ISSUE TITLE
FreeBSD 12.1 Cargo 5.7.0 compile failure

### ISSUE THREAD

**Issue by denningsrogue** [r-darwish/topgrade#519]
I have 4 FreeBSD systems running 12.1-RELEASE-p9 and cargo 1.46.0. I installed topgrade using cargo. Attempting to update topgrade from 5.4.0 to 5.7.0 results in the following errors:

error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> /home/denningsrogue/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-5.7.0/src/steps/os/freebsd.rs:9:16
    |
9   |     let sudo = require_option(sudo)?;
    |                ^^^^^^^^^^^^^^ ---- supplied 1 argument
    |                |
    |                expected 2 arguments
    |
   ::: /home/denningsrogue/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-5.7.0/src/utils.rs:121:1
    |
121 | pub fn require_option<T>(option: Option<T>, cause: String) -> Result<T> {
    | ----------------------------------------------------------------------- defined here

error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> /home/denningsrogue/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-5.7.0/src/steps/os/freebsd.rs:18:16
    |
18  |     let sudo = require_option(sudo)?;
    |                ^^^^^^^^^^^^^^ ---- supplied 1 argument
    |                |
    |                expected 2 arguments
    |
   ::: /home/denningsrogue/.cargo/registry/src/github.com-1ecc6299db9ec823/topgrade-5.7.0/src/utils.rs:121:1
    |
121 | pub fn require_option<T>(option: Option<T>, cause: String) -> Result<T> {
    | ----------------------------------------------------------------------- defined here

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0061`.
error: failed to compile `topgrade v5.7.0`, intermediate artifacts can be found at `/tmp/cargo-installaxBMvg`

Caused by:
  could not compile `topgrade`.

**Comment by r-darwish** [comment]
@denningsrogue can you please verify that the master branch compiles?

**Comment by denningsrogue** [comment]
It does.  Thank you very much.
