### ISSUE TITLE
`brew upgrade` covers regular and cask brew as of brew v2.4.16 at least

### ISSUE THREAD

**Issue by jasikpark** [r-darwish/topgrade#520]
**What did you expect to happen?**
no warning output from upgrade commands

**What actually happened?**
```shell
―― 17:08:19 - Brew Cask ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Warning: Calling brew cask upgrade is deprecated! Use brew upgrade --cask instead.
```

From https://github.com/Homebrew/brew/issues/8228 I have found that `brew upgrade --cask` and `brew upgrade --formula` are both options now.

**Additional details:**
- Which operating system or Linux distribution are you using?
- How did you install Topgrade?
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)

macOS 10.15.6
Homebrew
Homebrew Casks is providing a warning

homebrew stats on my mac: 
```
Homebrew 2.5.0-61-g7500b1c
Homebrew/homebrew-core (git revision d4a71; last commit 2020-09-09)
Homebrew/homebrew-cask (git revision 20113d; last commit 2020-09-09)
```

<details><pre>
Paste the output of `topgrade -v`
</pre></details>

**Comment by r-darwish** [comment]
This should have been fixed in b8cca4e00c8c923f01880193e011581e7d237f40. Is the latest version of Topgrade available in homebrew?

**Comment by jasikpark** [comment]
The thing is - `brew upgrade` upgrades formula and casks in one go. You need `brew upgrade --formula` and `brew upgrade --cask` or just `brew upgrade`

**Comment by claui** [comment]
Can confirm that 5.7.1 has landed in Homebrew, and the _Brew Cask_ step no longer exits with an error.

But as @jasikpark said, the _Brew Cask_ step now effectively no longer does anything because `brew upgrade` covers both, and has already run in the _Brew_ step.

**Comment by r-darwish** [comment]
I see, then I should probably remove the brew cask step. Now the question is whether support for [cask upgrade](https://github.com/buo/homebrew-cask-upgrade) should be removed as well, because I suppose it also won't do anything if `brew upgrade` upgrades casks.

**Comment by jasikpark** [comment]
well, it seems like if someone has cask upgrade installed they want more granularity / more descriptive service - so maybe a way for the configuration of topgrade to allow a `brew upgrade --formula` step + a `brew cu` step, whereas normally it's just a `brew upgrade` step? Or maybe that's just automatic if they have cask upgrade installed?

**Comment by claui** [comment]
Might be easiest then to leave the _Brew Cask_ step as-is, and change the _Brew_ step to only `brew upgrade --formula`.

**Comment by jasikpark** [comment]
Though that's not working in step with Homebrew's intentions at least: they're trying to integrate brew and brew cask fully over time. So with that in mind I should have just led with that... it should probably just be the one step - specifically for `brew v2.4.16` or so and after of course

**Comment by claui** [comment]
Yes, `brew cask` commands are gradually going away but Homebrew isn’t planning any further unification on the `upgrade` front.

If _Brew_ and _Brew Cask_ remain separate steps, topgrade users keep their freedom of `disable`-ing one or the other.
