### ISSUE TITLE
Windows Defender detects potential unwanted application

### ISSUE THREAD

**Issue by moritzrupp** [r-darwish/topgrade#521]
**What did you expect to happen?**
Windows Defender does not find any potential threats.

**What actually happened?**
After upgrading to topgrade 5.7.1 with the build-in update mechanism, Windows Defender has raised an alert for a potentially unwanted app: PUA:Win32/Pearfoos.A!ml

The Screenshot is in German, unfortunately.
![screenshot](https://user-images.githubusercontent.com/2112402/92996347-38866a80-f50b-11ea-875f-370bdac99a2a.png)

It says:
```
Alert level: low
Status: Active
Date: 09/12/2020 02:43 PM
Category: Potentially unwanted app
Details: The behavior of this app is potentially unwanted

Affected items:
 - file: C:\Program Files\Topgrade\topgrade.exe
```

**Additional details:**
- Which operating system or Linux distribution are you using?
  ```Windows 10 Version 2004 (Build 19041.450)```
- How did you install Topgrade?
  ```Initially downloaded the compiled binary from the releases page of this repository, then updated it with the internal update mechanism```
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)
  ```This has happend while I have started topgrade. No specific step is failing```

<details><pre>
Paste the output of `topgrade -v`
```
PS > topgrade -v
Fehler beim Ausführen des Programms "topgrade.exe": Zugriff verweigertIn Zeile:1 Zeichen:1
+ topgrade -v
+ ~~~~~~~~~~~.
In Zeile:1 Zeichen:1
+ topgrade -v
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
Windows 10 is now blocking the execution of topgrade.
</pre></details>

**Comment by r-darwish** [comment]
Not sure why it doesn't happen on my machines. Maybe because you downloaded it to Program files? What happens if you try to download it to your home directory?

**Comment by moritzrupp** [comment]
I'm not sure if this is the reason, but when I wanted to try it, even Chrome is blocking the download. Further information is redirecting to the following Google Chrome help page: https://support.google.com/chrome/answer/6261569?visit_id=637355184734420848-1620194118&p=ib_download_blocked&hl=en&rd=1

**Comment by r-darwish** [comment]
Okay, we'll try to deal with everything one at a time. First, if anyone else is experiencing this please upvote this ticket. 

I don't have Chrome installed by I tried Microsoft Edge and did not encounter any issue while downloading. Since it happens on your machine, could you try [submitting Topgrade for analysis](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-antivirus/antivirus-false-positives-negatives)?

I'm not sure whether Chrome has a similar mechanism or not.

**Comment by moritzrupp** [comment]
First of all, thanks a lot for your help! 👍 

## Windows Defender issue

I have just submitted topgrade for analysis (I have selected Software Developer, instead of of Home customer). I'll update the issue as soon as any results are in.

Furthermore, here is more information about [how Microsoft identifies malware and potentially unwanted applications](https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/criteria#unwanted-software).

## Chrome issue

I believe Chrome started to report it as an unwanted application in combination with Windows Defender. But I couldn't find any documentation about that in detail.

Nevertheless, I have now deleted the detection history in Windows Defender, removed topgrade from `C:\Program Files` and have downloaded it again into my home folder. When I run it now, everything works fine (as I have deleted the detection history). But Chrome is still complaining directly after the download.

For Chrome, you can only report the issue if you are the actual owner of the website, so that doesn't help.

Let's see what the analysis from Microsoft says.

**Comment by moritzrupp** [comment]
By now, Microsoft has worked on the analysis with the following result.

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
>
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
>
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
>
> Thank you for contacting Microsoft.

After executing the mentioned steps, Chrome is also no longer reporting an issue and the download is smoothly finishing. Therefore, I'm closing the issue ans nothing is left to be done.

Thanks again for your support, topgrade is awesome!

**Comment by r-darwish** [comment]
Thank you also for helping out investigating this issue.
