### ISSUE TITLE
Add support for `mas`?

### ISSUE THREAD

**Issue by adavidzh** [r-darwish/topgrade#522]
***Which tool is this about? Where is its repository?***

The tool is [`mas`](https://github.com/mas-cli/mas),
> A simple command line interface for the Mac App Store. Designed for scripting and automation.

***Which operating systems are supported by this tool?***

Mac OS.

***What should Topgrade do to figure out if the tool needs to be invoked?***

Depends on `brew`.
I suppose the presence of
```
`brew --prefix`/bin/mas
```
would work.

***Which exact commands should Topgrade run?***

Check if `mas outdated` is non-empty and in that case run `mas upgrade`.
There may be sign-in issues that I am not completely sure of.

**Comment by r-darwish** [comment]
Mas is already supported. The step is called "macOS App Store". Are you sure mas is in your PATH?

**Comment by adavidzh** [comment]
Yikes! *hides under a rock*
