### ISSUE TITLE
Allow skip checks option during run

### ISSUE THREAD

**Issue by rcampbel3** [r-darwish/topgrade#53]
I think topgrade is really neat, however... when I'm installing a lot of package dependencies in rapid succession while trying to figure out what I need to build something else, I wish there were a way to override the topgrade checks if I've just run apt commands in the last few minutes.

Something like "press 'q' to skip upgrade checks"

Also, perhaps an internal config setting like "don't check for upgrades if last run was less than N hours/days ago" -- that might be a good overall solution.

**Comment by r-darwish** [comment]
I don't think we can find a robust way to detect when was the last system upgrade performed, so I think that the best solution would be to add a `--skip-system` command line argument
