### ISSUE TITLE
`--only` should ignore `disable` config

### ISSUE THREAD

**Issue by m0nhawk** [r-darwish/topgrade#533]
**I want to suggest a new feature**

Topgrade should ignore `disable` option from config when running the `--only` command.

I found it would be really useful, I can think of example of `tlmgr` and `git_repos` - I don't want for topgrade to run it every time (as it will spent long time upgrading everything), but running with `--only` once in a while would be really nice.

PS: I'll try to see if I can address this through the weekend.

**Comment by m0nhawk** [comment]
@r-darwish It was fast! 🎉  I just cloned the repo to check on weekend how to do that.

I hope this is a useful addition!

**Comment by r-darwish** [comment]
Yeah, it makes sense. Thanks for suggesting.
