### ISSUE TITLE
After update to 5.8.0 throwing an error with greedy_cask enabled

### ISSUE THREAD

**Issue by xxfatumxx** [r-darwish/topgrade#535]
**What did you expect to happen?**
brew upgrade

**What actually happened?**
Error: Options --formula and --greedy are mutually exclusive.

**Additional details:**
- Which operating system or Linux distribution are you using?
MacOS 10.15.7
- How did you install Topgrade?
Via Homebrew
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)
/usr/local/bin/brew upgrade --ignore-pinned --formula --greedy
Error: Options --formula and --greedy are mutually exclusive.

If in you have these strings uncommented in your topgrade.toml config:

[brew]
greedy_cask = true

topgrade 5.8.0 throws error mentioned previously and asks for retry. Disabling of greedy_casks helps but obviously does not force ```brew``` to install latest versions of casks

**Comment by xxfatumxx** [comment]
The question is: Can I disable ```--formula``` somehow in ```topgrade.toml``` config?

**Comment by r-darwish** [comment]
Sounds like a bug. I'll fix it

**Comment by ollixx77** [comment]
Uncommeting "greedy_cask = true" in the topgrade.toml still throws an error:

`Olli-A1378:~ olli$ topgrade
 2021-12-20T15:49:26.146Z ERROR topgrade::config > Failed to deserialize /Users/olli/.config/topgrade.toml
 2021-12-20T15:49:26.147Z ERROR topgrade::config > failed to load configuration: unknown field `greedy_cask`, expected one of `pre_commands`, `post_commands`, `commands`, `git_repos`, `predefined_git_repos`, `disable`, `ignore_failures`, `remote_topgrades`, `remote_topgrade_path`, `ssh_arguments`, `git_arguments`, `tmux_arguments`, `set_title`, `assume_yes`, `yay_arguments`, `no_retry`, `run_in_tmux`, `cleanup`, `notify_each_step`, `accept_all_windows_updates`, `bashit_branch`, `only`, `composer`, `brew`, `linux`, `git`, `windows`, `npm`, `vim`, `firmware`, `vagrant`, `flatpak` at line 1 column 1`

Using topgrade 8.1.2, Homebrew 3.3.9, macOS 11.6.2

**Comment by MCOfficer** [comment]
> Uncommeting "greedy_cask = true" in the topgrade.toml still throws an error:
> 
> Olli-A1378:~ olli$ topgrade 2021-12-20T15:49:26.146Z ERROR topgrade::config > Failed to deserialize /Users/olli/.config/topgrade.toml 2021-12-20T15:49:26.147Z ERROR topgrade::config > failed to load configuration: unknown field `greedy_cask`, expected one of `pre_commands`, `post_commands`, `commands`, `git_repos`, `predefined_git_repos`, `disable`, `ignore_failures`, `remote_topgrades`, `remote_topgrade_path`, `ssh_arguments`, `git_arguments`, `tmux_arguments`, `set_title`, `assume_yes`, `yay_arguments`, `no_retry`, `run_in_tmux`, `cleanup`, `notify_each_step`, `accept_all_windows_updates`, `bashit_branch`, `only`, `composer`, `brew`, `linux`, `git`, `windows`, `npm`, `vim`, `firmware`, `vagrant`, `flatpak` at line 1 column 1
> 
> Using topgrade 8.1.2, Homebrew 3.3.9, macOS 11.6.2

pretty sure you don't have `greedy_cask` under the `brew` section, but at top level. It should be like this:

```toml
[brew]
greedy_cask = true
```

**Comment by ollixx77** [comment]
You were absolutely right. Thanks a lot.
