### ISSUE TITLE
add checking/installing for updates for most important browser like Firefox and Chrome under macOS

### ISSUE THREAD

**Issue by AWHubGit** [r-darwish/topgrade#536]
Please add checking/installing for updates for most important browser like Firefox and Chrome under macOS.

In macOS only manually looking at "about Firefox" or "about Google Chrome" tells if there are new versions/updates available.

Topgrade should do this too under macOS.

Thanks.

Edit 1:
Or better: All manually/individually downloaded and installed DMG- and PKG-files(-apps). Not only browsers installed this way.

**Comment by r-darwish** [comment]
If you install your browser using brew cask then brew will handle the upgrade

**Comment by NicoHaase** [comment]
How should such a check work? If you want to keep your applications upgradable, install them using a package manager like Chocolatey or Brew
