### ISSUE TITLE
Prevent Deno upgrade if installed by Chocolatey

### ISSUE THREAD

**Issue by Tarnadas** [r-darwish/topgrade#549]
I installed Deno via Chocolatey.

Chocolatey is the first thing that starts its update process, but it detaches itself from the current shell due to the sudo requirement and the remaining upgrades from Topgrade can continue.
Then Topgrade hit `deno upgrade`, which unfortunately failed on my machine. I don't know the exact reason, but it could be due to a separate admin account setup. The Chocolatey upgrade succeeded and it updated Deno to the latest version, but that happened after Topgrade failed to upgrade Deno manually.

I assume this can only happen on Windows with Chocolatey, so it might be good to detect whether Deno has been installed via Chocolatey and if yes, skip it.

**Comment by r-darwish** [comment]
> but it detaches itself from the current shell due to the sudo requirement and the remaining upgrades from Topgrade can continue.

Weird. I use [gsudo](https://github.com/gerardog/gsudo) in Windows and it doesn't happen to me. Chocolatey run in the current shell. Are you using a different version of sudo for Windows?

**Comment by Tarnadas** [comment]
I use this sudo: https://chocolatey.org/packages/Sudo
It instantly detaches the Chocolatey update process from the current shell.

**Comment by r-darwish** [comment]
Could you try switching to gsudo instead?
