### ISSUE TITLE
Add a `check` command

### ISSUE THREAD

**Issue by bingalls** [r-darwish/topgrade#551]
**I want to suggest a new step**
`topgrade check`
***Which tool is this about? Where is its repository?***
This runs the self-check for each package manager, at bottom
***Which operating systems are supported by this tool?***
all
***What should Topgrade do to figure out if the tool needs to be invoked?***
Perhaps print a recommendation at the end of normal use
***Which exact commands should Topgrade run?***
* brew doctor
* brew cask doctor
* composer diagnose
* flutter doctor
* gem check
* npm -g audit
* npm -g outdated
* pip check
* yarn --global check

**Comment by jeetelongname** [comment]
I can also add 
- `doom doctor`
- `zplug check`

**Comment by r-darwish** [comment]
I have decided that this is out of scope for Topgrade at the moment. I'll reopen this if I ever change my mind
