### ISSUE TITLE
Fisher is broken since Fisher 4.0.0

### ISSUE THREAD

**Issue by andreiborisov** [r-darwish/topgrade#558]
**What did you expect to happen?**
...
Fisher updates working

**What actually happened?**
...

**Additional details:**
- Which operating system or Linux distribution are you using?
- How did you install Topgrade?
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)

<details><pre>
Paste the output of `topgrade -v`
</pre></details>

**Comment by andreiborisov** [comment]
Apologize, already resolved

**Comment by r-darwish** [comment]
I will release a version with the fix in a few days because the new version isn't compatible with the old fisher, so I'll give people some time to upgrade.
