### ISSUE TITLE
Fancy documentation site

### ISSUE THREAD

**Issue by r-darwish** [r-darwish/topgrade#560]
The wiki is unmaintained and isn't the nicest place to have a documentation. Topgrade should have a cool [hugo](https://gohugo.io/) site.

**Comment by jeetelongname** [comment]
I don't mind helping out with this. I assume that it will be using GitHub pages for the hosting?

**Comment by r-darwish** [comment]
Yeah, that's the plan

**Comment by Jogai** [comment]
Gridsome is a breeze to work with, and has integration as well: https://gridsome.org/docs/deploy-to-github/

**Comment by jasikpark** [comment]
TADA 🎉 https://jasikpark.github.io/topgrade-docs/

Hosted on Github Pages, deployed via Github Actions, there's a blog that I figure could use some content, maybe just the releases page, and there's a couple of minute bugs I'm working out with https://github.com/alex-shpak/hugo-book/issues, but TADA :)

**Comment by r-darwish** [comment]
@jasikpark thank you so much for this. Would you mind transferring the repository ownership to me so I can start filling it up?

**Comment by jasikpark** [comment]
done. I already filled out the documentation that was available in the wiki, and fixed the links and such.

**Comment by r-darwish** [comment]
Thank you. I will start adding more content
