### ISSUE TITLE
SSH can be handled with pure Rust rather than shelling out

### ISSUE THREAD

**Issue by strangelittlemonkey** [r-darwish/topgrade#563]
https://github.com/r-darwish/topgrade/blob/9a368d8218242e8087342a3eada522c42c2242c3/src/steps/remote/ssh.rs#L10

The ssh2 crate is maintained and works quite well and could replace shelling out here to call on a local implementation of ssh.

https://crates.io/crates/ssh2

**Comment by r-darwish** [comment]
I don't see the added value. This will both increase the size of the binary as well require more code to handle interactive use appropriately.

**Comment by andrei-pavel** [comment]
++portability
--dependency
Would work on machines that don't have an external SSH client installed.
