### ISSUE TITLE
flatpack stopps and sends topgrade process into background

### ISSUE THREAD

**Issue by mordax777** [r-darwish/topgrade#564]
**What did you expect to happen?**
That it upgrades the Flatpacks.

**What actually happened?**
It send the process into the background when at the Flatpack upgrade step.

**Additional details:**
- Which operating system or Linux distribution are you using?
**Arch Linux, 5.9.9-arch1-1**
- How did you install Topgrade?
**Via yay(https://aur.archlinux.org/packages/topgrade/)**
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)
* **Command exits without any error, output:**
```bash
❯ /usr/bin/flatpak update --user -y
Looking for updates…
Nothing to do.
```

<details><pre>
―― 23:23:16 - Flatpak User Packages ――――――――――――――――――――――――――――――――――――――――――――
 2020-11-23T22:23:16.801Z DEBUG topgrade::executor         > Running "/usr/bin/flatpak" "update" "--user" "-y"
Looking for updates…
</pre></details>

**Comment by r-darwish** [comment]
Are you using zsh as your shell?

**Comment by mordax777** [comment]
@r-darwish, no, i am using `fish`

**Comment by r-darwish** [comment]
So this seems different than #475. You're the first one using fish that reported about this. I don't have any idea at the moment about what's causing it. Does it reproduce every time? Does it reproduce if you use bash instead of fish?

**Comment by mordax777** [comment]
* Does it reproduce every time? 
 yes
* Does it reproduce if you use bash instead of fish?
 yes
```bash
―― 09:45:39 - Flatpak User Packages ――――――――――――――――――――――――――――――――――――――――――――
 2020-11-24T08:45:39.223Z DEBUG topgrade::executor         > Running "/usr/bin/flatpak" "update" "--user" "-y"
Looking for updates…

[1]+  Stopped                 topgrade -v
```

**Comment by r-darwish** [comment]
Is this still happening?

**Comment by mordax777** [comment]
@r-darwish I cannot say because I stopped using Flatpacks. You can close the issue since it seems like its only me who had this issues and I cannot reproduce them currently.
