### ISSUE TITLE
Faster and less verbose powershell invocations

### ISSUE THREAD

**Issue by bugabinga** [r-darwish/topgrade#566]
**I want to suggest some general feature**
Topgrade should invoke the `powershell` command with `-NoLogo -NonInteractive -NoProfile` arguments by default.

**-NoLogo**: Do not print copyright and version information.
**-NonInteractive**: Prevent interactive commands like `Read-Host` from blocking execution, throwing an error instead.
**-NoProfile**: Do not initially source the user profile script.

`-NoProfile` and `-NonInteractive` are risky changes because existing users could potentially rely on the current behaviour.
One way to mitigate the risk would be to allow setting custom arguments to `powershell` steps in the topgrade config.

**Comment by r-darwish** [comment]
Are you talking about the step that upgrades powershell modules or about the option to drop you to a shell when a step fails?

**Comment by bugabinga** [comment]
I believe the powershell modules update step already uses `-NoProfile`.
I was primarly concerned about the shell steps.

**Comment by r-darwish** [comment]
What shell steps? The only steps related to Powershell are the module update and Windows update.

**Comment by bugabinga** [comment]
The "custom commands" steps.


Am 2. Dezember 2020 13:13:40 MEZ schrieb Roey Darwish Dror <notifications@github.com>:
>What shell steps? The only steps related to Powershell are the module
>update and Windows update.

-- 
Oliver Jan Krylow
