### ISSUE TITLE
Problem with retrying operations

### ISSUE THREAD

**Issue by m-cat** [r-darwish/topgrade#58]
Great tool, but I noticed a minor bug:

```
―― Emacs ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Symbol's value as variable is void: user-emacs-directory

Retry? [y/N] y

―― Emacs ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Symbol's value as variable is void: user-emacs-directory

Retry? [y/N] N
Retry? [y/N] N
Retry? [y/N]
```

Typing `N` per the prompt does nothing, and topgrade doesn't quit asking to retry until I press enter.

The culprit is this line which checks if the input is lowercase `n`:
https://github.com/r-darwish/topgrade/commit/6c00fae63c3c987b1ab6a780d0d39ec279ea185d#diff-6d00071c5cb83f348e478f2a87d45999R88

Solution is pretty simple, just convert the input to lowercase before comparing. The prompt can stay as it is or change to `[y/n]` (not sure why `N` is uppercase, to be honest).

**Comment by r-darwish** [comment]
The purpose of printing the uppercase N was to show the user that n is the default choice when the user just presses enter, so you aren't expected to write an uppercase N. Nevertheless, uppercase N should also work. Thanks for reporting the issue.
