### ISSUE TITLE
topgrade doesn't run "PlugUpdate" command from vim-plug

### ISSUE THREAD

**Issue by openjck** [r-darwish/topgrade#581]
**What did you expect to happen?**
topgrade should run `PlugUpdate` in addition to `PlugUpgrade`

**What actually happened?**
topgrade runs `PlugUpgrade`, which updates vim-plug itself, but does not run `PlugUpdate`, which updates the actual plugins. See the [vim-plug documentation](https://github.com/junegunn/vim-plug/blob/5430b6213a5c6c3bafd7e25b1e80ccb2afd7f5ba/README.md#commands) for more information.

**Additional details:**
- Which operating system or Linux distribution are you using: **Ubuntu 20.10**
- How did you install Topgrade: **cargo install topgrade**

**Comment by r-darwish** [comment]
https://github.com/r-darwish/topgrade/blob/0ed5f8f96aa57c5aab450e9cc30769e900c87343/src/steps/upgrade.vim#L14

I think that the script should run `PlugUpdate`. Can you run this debug script in vim and maybe figure out why `PlugUpdate` isn't executed?

**Comment by openjck** [comment]
Oh, huh. I hadn't noticed that. Strangely, it's acting as though `PlugUpdate` was not run. Earlier tonight, I ran `PlugUpdate` manually after running `topgrade` and 3 updates were performed. I'll look into it soon. Thanks!

**Comment by r-darwish** [comment]
Hi @ openjck. Did you find anything?

**Comment by openjck** [comment]
If I save *upgrade.vim* to a file named *test.vim* and then run `nvim -c 'so test.vim'`, it seems to work fine. I also see *Plug* printed when I use the `--verbose` flag.

I think I might have been confused about something when I judged that the plugins were not updated. Sorry for the false alarm. I'll reopen if I can reproduce.
