### ISSUE TITLE
[DISCUSSION] Handling 'brew' on Apple Silicon

### ISSUE THREAD

**Issue by Byron** [r-darwish/topgrade#584]
[Brew recommends](https://docs.brew.sh/Installation#untar-anywhere) to separate intel brew installations staying in `/usr/local` from the ARM based one which are now to be found in `/opt/homebrew`.

Depending on the user's configuration, either `brew` binary might be in the path.

For now I have added a custom command into `~/config/topgrade.yml` like so…

```yaml
# Custom commands
[commands]
"Intel Brew" = "/usr/local/bin/brew upgrade"
"Intel Brew Cleanup" = "/usr/local/bin/brew cleanup"
```

…to allow running intel brew updates as well.

### What topgrade currently does

Topgrade finds `brew` in the PATH using `which` essentially.

### What I think topgrade _could_ do

On Mac there are now up to two binaries around in well-known places. Once could check for both and run both if present. If none is there, one could fall back to searching `brew` in PATH as before.

### Discussion

What do you think :D?  Maybe there are better ways and I love to hear about them.
Once there is agreement on what can be done, I am happy to submit a PR implementing the change.

Thank you

**Comment by r-darwish** [comment]
It seems reasonable to run them both. @claui what do you think?
