### ISSUE TITLE
topgrade wants to downgrade tons of packages on Fedora

### ISSUE THREAD

**Issue by BjoernDaase** [r-darwish/topgrade#587]
*Fedora 33
* topgrade 6.1.0

Since version 6.1.0 topgrade wants to downgrade tons of packages on Fedora 33.
This is caused by the change to `distro-sync` instead of `upgrade` which is plain wrong to use in the `topgrade` case. I, and many other users as well, take packages either out of the testing repo or download them from koji directly. This is often needed, to have a bugfix there which often need lots of time to end up in the stable repos.

Therefore, please revert https://github.com/r-darwish/topgrade/commit/76ae636f202e5e2386d1e96235e99b6bbbc510f3!

**Comment by r-darwish** [comment]
Since I'm not a Fedora user, @msmafra can you guys please discuss the  desired behavior?

**Comment by BjoernDaase** [comment]
I don't think there is anything to discuss here, just see the documentation: https://dnf.readthedocs.io/en/latest/command_ref.html#distro-sync-command-label. Something which does intentional downgrades can never be part of an upgrade tool.

**Comment by r-darwish** [comment]
I'm convinced. Reverted.

**Comment by msmafra** [comment]
> I'm convinced. Reverted.

As distro-sync is the desired behaviour for me (don't want broken dependencies etc.), could an optional config or parameter/configuration be added then?

**Comment by r-darwish** [comment]
I'll make that configurable

**Comment by msmafra** [comment]
> I'll make that configurable
Hello there!
Thank you very much. Should I open as feature request? I'm not sure.

**Comment by r-darwish** [comment]
No need
