### ISSUE TITLE
Please make brew casks updates as a separate step

### ISSUE THREAD

**Issue by xxfatumxx** [r-darwish/topgrade#588]
**I want to suggest some general feature**
Topgrade should upgrade brew formulae and brew casks separately, not as a single step.
**Operating system**
MacOs Big Sur 11.1

**More information**
- Maybe it's just my case but I hope it's not. Mostly brew formulae has much more problems because of linkage, xcode dependency etc. and usually fails the step. But unlike formulae, casks are way more stable (mostly because they're monoliths with no dependencies) So the problem is obvious, If I have problem with brew formulae, I won't be able to upgrade brew casks via topgrade until I'll solve the formulae's problem, what is inconvenient sometimes. May I ask you to separate them from each other to avoid such a problem? Much appreciate it.

**Comment by r-darwish** [comment]
This used to be implemented like this, but Brew themselves are trying to unify this into a single command. If you have [brew-cask-upgrade](https://github.com/buo/homebrew-cask-upgrade) installed then Topgrade will run two commands and the problem you described might happen. However, if not, then Topgrade should just run `brew upgrade`, which now should handle casks as well as formulas in the same command. Isn't that so?

**Comment by xxfatumxx** [comment]
Hi @r-darwish I'm not sure about default behaviour of `brew upgrade` command, but actually you can specify `--casks` or `--formula` key to upgrade ONLY casks or forlmulae accordingly. Proof on the [screenshot](https://imgur.com/a/Yt0q65U). So what I ask is to create `brew-formula` and `brew-cask` steps which will give us an option to upgrade formulae specifically with `topgrade --only brew-formula` or exclude them from global upgrade with `topgrade --disable brew-formula` Thanks for your attention.
