### ISSUE TITLE
Dotnet tools upgrade fails if there are none installed.

### ISSUE THREAD

**Issue by Jogai** [r-darwish/topgrade#592]
**What did you expect to happen?**
Nothing

**What actually happened?**
It tried to upgrade .net tool ' ---------------------' which doesnt exist.

**Additional details:**
Installed topgrade on a fairly clean vm supplied by ms: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/
There are no global dotnet tools installed, thats probably causing parsing of the output to go haywire.

<details><pre>
error NU1101: Unable to find package ---------------------. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
Tool '---------------------' failed to update due to the following:
The tool package could not be restored.
Tool '---------------------' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
</pre></details>

**Comment by r-darwish** [comment]
Can you show me the output of `dotnet tool list --global`?

**Comment by Jogai** [comment]
Yeah, ofc:
<pre>
C:\Users\User>dotnet tool list --global
Package Id      Version      Commands
-------------------------------------
C:\Users\User>
</pre>

**Comment by r-darwish** [comment]
Weird. I deleted all my tools and this is what I'm getting:

```
❯ dotnet tool list --global
Package Id      Version      Commands
-------------------------------------

❯ cargo run -- --only dotnet --show-skipped
    Finished dev [unoptimized + debuginfo] target(s) in 1.99s
     Running `target\debug\topgrade.exe --only dotnet --show-skipped`

―― 20:18:18 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
.NET: SKIPPED: No dotnet global tools installed
```

Can you post `dotnet --info`?

**Comment by Jogai** [comment]
Well, now I have the same result. I did do a restart in the meantime.. So, the above just happened only directly after upgrading, maybe I didnt restart that cli window but I'm not sure.

**Comment by Virakal** [comment]
I've had the same issue and it has persisted through restarts, but running `dotnet tool list --global` seems to have fixed it, oddly enough.

**Comment by r-darwish** [comment]
I suppose that in some cases `dotnet tool list --global` might print something else on the first run

**Comment by moritzrupp** [comment]
I'm also having this issue. When I run `topgrade`, the .NET step directly asks for Retry without any other output. In the summary, it says
```powershell
―― 19:46:14 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Chocolatey: OK
Powershell Modules Update: OK
.NET: FAILED
Flutter: OK
pipx: OK
Windows update: OK
```

dotnet says .NET Core SDK is not installed, which is true:
```powershell
PS > dotnet tool list --global
  It was not possible to find any installed .NET Core SDKs
  Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download
PS >
```

**Comment by r-darwish** [comment]
Thank you @moritzrupp. This seems like a different issue than when this step tries to install `--------`, but I will fix that as well
