### ISSUE TITLE
config: Allow ignoring the npm root path when running as root

### ISSUE THREAD

**Issue by IngwiePhoenix** [r-darwish/topgrade#599]
Really simple: I am setting up all my maschines with Topgrade and I have NPM on a couple of them and even added custom steps for some of my cross-compiler toolchains like Vita SDK. However, I noticed that NPM is only run when the root is within the user's home folder. Now, on most of my maschines, this is not the case.

Would it be possible to add a config option to deliberately ignore this circumstance? I am running all my upgrades as root.

**Comment by r-darwish** [comment]
You mean that you run Topgrade as root?

**Comment by IngwiePhoenix** [comment]
Yeah - and hence, the NPM step can be ran. :)

**Comment by r-darwish** [comment]
I pushed a branch named `feature/root-npm`. Can you please test it? There's no need to configure anything.
