### ISSUE TITLE
APT: The ncurses interface ends up printing nothing - use apt-get instead

### ISSUE THREAD

**Issue by IngwiePhoenix** [r-darwish/topgrade#601]
**What did you expect to happen?**
While updating remotes via topgrade, each time `apt` was invoked, the expected ncurses UI did not show - instead, the text either did not display, or my terminal just went all over the place instead.

**What actually happened?**
![image](https://user-images.githubusercontent.com/2893716/104328089-c3906500-54eb-11eb-8268-d7bcf4c67292.png)

**Additional details:**
- Which operating system or Linux distribution are you using?
  * Debian 10
- How did you install Topgrade?
  * Cargo
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)
  * Running via SSH on it's own, the ncurses UI displays as intended.

Also: From the `apt` manpage:
```
SCRIPT USAGE AND DIFFERENCES FROM OTHER APT TOOLS
       The apt(8) commandline is designed as an end-user tool and it may change behavior between versions. While it tries not to break backward compatibility this is not guaranteed either if a change
       seems beneficial for interactive use.

       All features of apt(8) are available in dedicated APT tools like apt-get(8) and apt-cache(8) as well.  apt(8) just changes the default value of some options (see apt.conf(5) and specifically the
       Binary scope). So you should prefer using these commands (potentially with some additional options enabled) in your scripts as they keep backward compatibility as much as possible.
```

You might want to consider using `apt-get` instead.

<details><pre>
Not relevant. But! Here are my config files instead:

# Windows (from where I ran topgrade)
# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
#disable = ["node"]

# Ignore failures for these steps
#ignore_failures = [""]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
remote_topgrades = ["macmini", "ingwie.io", "dragonsinn"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Path to Topgrade executable on remote machines
#remote_topgrade_path = ".cargo/bin/topgrade"

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title
#set_title = false

# Cleanup temporary or old files
cleanup = true

[git]
max_concurrency = 10
# Additional git repositories to pull
repos = [
    "E:\\cloud.ingwie.me\\Work\\Git"
]

# Don't pull the predefined git repos
#predefined_repos = false

# Arguments to pass Git when pulling Repositories
#arguments = "--rebase --autostash"

[composer]
self_update = true

# Commands to run before anything
[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
# V
"V (self)" = "v up"
"v (modules)" = "v upgrade"

[brew]
#greedy_cask = true

[linux]
# Arguments to pass yay when updating packages
#yay_arguments = "--nodevel"
#trizen_arguments = "--devel"
#enable_tlmgr = true
#emerge_sync_flags = "-q"
#emerge_update_flags = "-uDNa --with-bdeps=y world"
#redhat_distro_sync = false

[windows]
# Manually select Windows updates
#accept_all_updates = false
#open_remotes_in_new_terminal = true

# Causes Topgrade to rename itself during the run to allow package managers
# to upgrade it. Use this only if you installed Topgrade by using a package
# manager such as Scoop to Cargo
#self_rename = true

The given SSH hostnames are defined in .ssh/config - hence, they are abbreviated.
</pre></details>

**Comment by r-darwish** [comment]
Sounds reasonable. I'll change it to apt-get
