### ISSUE TITLE
Interaction between Topgrade and Cargo-Update

### ISSUE THREAD

**Issue by iXialumy** [r-darwish/topgrade#606]
Whenever you use topgrade while there is an upgrade available for itself it should be able to upgrade itself.
...

While the cargo update all updates succeed except for the update for the update for topgrade, since it is running.
This seems to be an issue under Windows only, but I have not confirmed that.
Cargo-update has a workaround for itself, which might be a starting point to look at for a fix.
...

**Comment by r-darwish** [comment]
There'a already a workaround. please set `self_rename = true`  in the `[windows]` section of the configuration.
