### ISSUE TITLE
Error while building on arch

### ISSUE THREAD

**Issue by open-antux** [r-darwish/topgrade#607]
**What did you expect to happen?**
topgrade installed on my system.

**What actually happened?**
A building error.

**Additional details:**
- Which operating system or Linux distribution are you using? ArchLinux x86_64 GNU/Linux
- How did you install Topgrade? Using ``yay -S topgrade``
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)
- Error:
```
==> Starting build () ...
error: no override and no default toolchain set
==> ERROR: An error occurred in build ().
     The operation is about to be stopped ...
error making: topgrade
```

**Comment by r-darwish** [comment]
How did you install Rust?

**Comment by open-antux** [comment]
``yay -S rust``

**Comment by r-darwish** [comment]
@idanski maybe you have any ideas?

**Comment by idanski** [comment]
Weird, works fine on my machine, however I installed rust by downloading rustup.

@open-antux
As the message specifies `no default toolchain set`. Maybe you haven't set default toolchain by running:
`rustup default stable` ?

Please try.
Also I'd link https://wiki.archlinux.org/index.php/Rust here for further help.
Let us know if that's any help.

**Comment by open-antux** [comment]
My bad, I had installed ``rustup`` and not ``rust``, sorry for the useless open issue... I'm feeling so stupid...

**Comment by r-darwish** [comment]
> My bad, I had installed ``rustup`` and not ``rust``, sorry for the useless open issue... I'm feeling so stupid...

These things happen. Don't be too hard on yourself
