### ISSUE TITLE
Is there a blacklist or whitelist option?

### ISSUE THREAD

**Issue by Compro-Prasad** [r-darwish/topgrade#61]

**Comment by r-darwish** [comment]
Not at the moment. I do my best to auto detect what should and what should not be run. Is there some step that runs on your system while it should not?

**Comment by Compro-Prasad** [comment]
I just thought it would be nice not to update something like Spacemacs/Emacs which often breaks stuff when updated.

**Comment by manuel-uberti** [comment]
This would be very helpful.

Since I use `early-init.el` (see: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=24acb31c04b4048b85311d794e600ecd7ce60d3b), it'd be nice to blacklist Emacs packages update, because right now when I run `topgrade` I am getting `Symbol’s function definition is void: package-installed-p`

**Comment by Compro-Prasad** [comment]
I am also using straight.el instead of package.el. So, it would be preferable not to update package.el packages when its not in the `init.el` file. For example update using package.el only if `(require 'package)` is declared in init.el.

Looking forward to see the unpopular straight.el integration. But usually I can update the packages using a single command.

**Comment by r-darwish** [comment]
I will implement `--no-emacs`, but I want it to be a flag that you may *want* to use when you don't feel like upgrading your Emacs today, but not a flag that you *have* to use because Topgrade can't handle your setup.

@Compro-Prasad @manuel-uberti [here](https://github.com/r-darwish/topgrade/blob/master/src/emacs.el) is my elisp code. How can I modify it so it will fit your setup?

**Comment by manuel-uberti** [comment]
A flag sounds reasonable to me. Could you try add `(require 'package)` at the top your code?

**Comment by r-darwish** [comment]
@manuel-uberti I'd like to try. I pushed a branch called `emacs`, in which I try to load the early init file. Can you try to see if it works? If it doesn't can you please check if `topgrade -n` actually shows that the early init file is loaded?

**Comment by manuel-uberti** [comment]
Sure, no problem.

Running `topgrade` now results in `package.el is not yet initialized!` for Emacs packages.

This is the output of `topgrade -n` related to Emacs:
```
―― Emacs ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/local/bin/emacs --batch -l /home/manuel/.emacs.d/early-init.el -l /home/manuel/.emacs.d/init.el --eval (if (fboundp 'paradox-upgrade-packages)
    (progn
      (paradox-upgrade-packages)
      (princ
       (if (get-buffer "*Paradox Report*")
           (with-current-buffer "*Paradox Report*" (buffer-string))
         "\nNothing to upgrade\n")))
  (progn
    (let ((package-menu-async nil))
      (package-list-packages))
    (package-menu-mark-upgrades)
    (condition-case nil
        (package-menu-execute 'noquery)
      (user-error nil))))
```

**Comment by r-darwish** [comment]
I just did a force push that calls `(package-initialize)`. Can you pull and try again?

**Comment by manuel-uberti** [comment]
Same message, and this is from `topgrade -n`:
```
―― Emacs ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/local/bin/emacs --batch -l /home/manuel/.emacs.d/early-init.el -l /home/manuel/.emacs.d/init.el --eval (progn
  (package-initialize)
  (if (fboundp 'paradox-upgrade-packages)
      (progn
        (paradox-upgrade-packages)
        (princ
         (if (get-buffer "*Paradox Report*")
             (with-current-buffer "*Paradox Report*" (buffer-string))
           "\nNothing to upgrade\n")))
    (progn
      (let ((package-menu-async nil))
        (package-list-packages))
      (package-menu-mark-upgrades)
      (condition-case nil
          (package-menu-execute 'noquery)
        (user-error nil)))))
```

**Comment by r-darwish** [comment]
Ok, so I'll implement `--no-emacs` in the meantime and I'll try to figure out how to deal with Emacs 27 somewhere in the future

**Comment by manuel-uberti** [comment]
Thanks for your patience, @r-darwish, and sorry to be a PITA with all this bleeding edge stuff. :)

**Comment by r-darwish** [comment]
No problem. I'm an Emacs user myself so Emacs is a first citizen in Topgrade. I will have to deal with version 27 eventually, but currently it involves cloning the entire Git tree. Maybe by the time an RC will be released someone will come up with a solution.
