### ISSUE TITLE
Self-update should prompt for elevation when necessary

### ISSUE THREAD

**Issue by RoryO** [r-darwish/topgrade#610]
If topgrade is in a protected location, like `/usr/bin`, and run as a normal user, self-update will fail. The other checks continue fine of course. This is expected. However, topgrade does know when to ask for sudo when necessary, such as when updating `snap`. I suggest the self update check should catch permission denied and prompt for elevation when doing so. Since topgrade handles so much automatically and gracefully I think this is reasonable. For example:

```
―― 11:15:56 - Self update ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Self update error: IoError: Permission denied (os error 13) at path "/usr/bin/topgrade_downloadUKoOTd"
```

**Comment by andrei-pavel** [comment]
Alternative 1. wrapper script
```
#!/bin/bash

(( EUID != 0 )) && exec sudo -- "${0}" "${@}"

topgrade "${@}"
```

Alternative 2. chmod
```
chmod a+x /usr/bin/topgrade
```

Alternative 3. chown
```
user=${USER}
group=$(stat -c %G "${HOME}")
chown -R "${user}:${group}" /usr/bin/topgrade
```

So why these workarounds and not an embedded elevation of privileges?
topgrade might upgrade different things in your root than in your user like your vim configuration or git repositories or rust crates. And you might not realize this and falsely think that everything is up to date. Alternative 1 doesn't solve this, but maybe it's what you want. Why is topgrade only executable under root in your setup?

**Comment by andrei-pavel** [comment]
After the second read, I realized this was not an execution permission problem. This is less of a scary change if only self update is done under root. Carry on.

**Comment by RoryO** [comment]
Topgrade already understands when to elevate when run as an unelevated user, such as when updating snap. I suggest extending this for self update.

**Comment by AWHubGit** [comment]
Same problem: Self update error: IoError: Permission denied (os error 13) at path "/usr/bin/topgrade_downloadxyz"
A "sudo topgrade --only bin" upgraded topgrade to most recent version. Dangerous to use sudo for step "bin"?

**Comment by r-darwish** [comment]
I gave a bit more though about this. There's no good reason for requiring sudo for Topgrade's self-update capability. I use the self-updating binaries on Linux, Windows and macOS. What I do for Linux is put Topgrade in `~/.local/bin` and add it to my `PATH`. This is much less dangerous then running the upgrade as root.
