### ISSUE TITLE
(ana|mini)conda base environment update

### ISSUE THREAD

**Issue by McCio** [r-darwish/topgrade#615]
Hello, I think supporting automatic conda update, just for the base environment, would be useful to many.

In my experience most of the people install (ana|mini)conda via the [provided script](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html), and that requires manual updates (that could be forgotten for a long time).

Any linux-ish installation is supported by the conda devs (also Windows, but I don't use it there).
The full update command for miniconda is
```
/opt/miniconda3/bin/conda update -n base conda
```

Actually, if running topgrade through a conda-inited shell, you can find the `$CONDA_EXE` and `$CONDA_DEFAULT_ENV` env vars that hold the `conda` path and the name of the default environment (normally it should be `base`).
In fact, I've currently configured the custom command in topgrade to execute
```
$CONDA_EXE update -n $CONDA_DEFAULT_ENV -c defaults conda
```
The `-c defaults` part is a possible _custom arg_ to configure in topgrade for this new step.

To be noticed for a conda-inited shell, `conda` is not an actual binary file, but a shell function, while the `$CONDA_EXE` file is the actual python script that normally we want to execute.

Also, it has a clean command
```
$CONDA_EXE clean
```
This command supports different flags, for which `-t` could be the safest choice, but probably most people would want to execute it with `-a`. I don't know how to make an educated decision on the flag to apply by default. Unfortunately, it **needs** a flag to be executed (maybe neither the conda devs don't want to impose a default behaviour).
<details>
<pre>
Removal Targets:
  -a, --all             Remove index cache, lock files, unused cache packages,
                        and tarballs.
  -i, --index-cache     Remove index cache.
  -p, --packages        Remove unused packages from writable package caches.
                        WARNING: This does not check for packages installed
                        using symlinks back to the package cache.
  -t, --tarballs        Remove cached package tarballs.
  -f, --force-pkgs-dirs
                        Remove *all* writable package caches. This option is
                        not included with the --all flag. WARNING: This will
                        break environments with packages installed using
                        symlinks back to the package cache.
  -c TEMPFILES [TEMPFILES ...], --tempfiles TEMPFILES [TEMPFILES ...]
                        Remove temporary files that could not be deleted
                        earlier due to being in-use. Argument is path(s) to
                        prefix(es) where files should be found and removed.
</pre>
</details>

I can surely help testing with the miniconda installation I have.

**Comment by SuperSandro2000** [comment]
Anaconda can easily end up in a loop where you update and downgrade packages with each update and never be done.

**Comment by McCio** [comment]
I never experienced that. I've mainly used miniconda always creating specific envs for each project, so the base env is always clean (=basic conda-needed packages).
But I can see that it could be a stretch to expect the base env to be clean for the majority of users. I'll let @r-darwish decide on the matter, but since the custom command isn't complicated we could probably close this.

**Comment by r-darwish** [comment]
I don't have specific experience with Anaconda but I have enough experience with Python to know that trying to upgrade all packages is almost always a bad idea. It's event being said [here](https://www.anaconda.com/blog/keeping-anaconda-date). I think this is too risky to become a Topgrade feature.
