### ISSUE TITLE
Oh-My-Zsh is up to date but topgrade wants to retry

### ISSUE THREAD

**Issue by CzernyJ** [r-darwish/topgrade#617]
## What did you expect to happen:

If Oh-My-Zsh is up to date, topgrade should mark the step as successful and go on with the execution.

## What actually happened:

topgrade seems not to recognize the version and thinks the update did fail in some way.

```
Updating Oh My Zsh
From https://github.com/ohmyzsh/ohmyzsh
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
         __                                     __   
  ____  / /_     ____ ___  __  __   ____  _____/ /_  
 / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ 
/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / 
\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  
                        /____/                       

Oh My Zsh is already at the latest version.
To keep up with the latest news and updates, follow us on Twitter: https://twitter.com/ohmyzsh
Want to get involved in the community? Join our Discord: https://discord.gg/ohmyzsh
Get your Oh My Zsh swag at: https://shop.planetargon.com/collections/oh-my-zsh

Retry? (y)es/(N)o/(s)hell 
```

### Systeminfo: 
System:
  Host: ******** Kernel: 5.4.0-65-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.4.8 Distro: Linux Mint 19.3 Tricia
zsh:
  zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
topgrade:
  Topgrade 4.3.0

topgrade installed via cargo

topgrade command:
```
―― 12:42:56 - oh-my-zsh ――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: sh /home/######/.oh-my-zsh/tools/upgrade.sh
```

**Comment by r-darwish** [comment]
Your version of Topgrade is very old

**Comment by CzernyJ** [comment]
Oh. I assumed that topgrade looks for its own updates. Dunno if it is something that version > 4.3.0 do.

For non rustaceans: How do you recommend updating topgrade without doing a de-installing and re-installing?

**Comment by r-darwish** [comment]
You have three options:
1. Install Topgrade from your system's package manager (such as brew)
2. Install cargo-update by running `cargo install cargo-update`. The latest version of Topgrade will now warn you if it's not installed.
3. Download the compiled binary from Github, which is compiled with a self-update feature
