### ISSUE TITLE
SDKman versions seems not to be recognized

### ISSUE THREAD

**Issue by CzernyJ** [r-darwish/topgrade#618]
**What did you expect to happen?**

When updating SDKman then topgrade should recognize SDKmans version number.

**What actually happened?**

topgrade prints the current version as empty string. Not sure if it is able to retrieve SDKmans version number.

```
―― 12:07:40 - SDKMAN! ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
No update available at this time.
==== BROADCAST =================================================================
* 2021-02-05: jbang 0.65.1 available on SDKMAN! https://git.io/Jt2BB
* 2021-02-05: jbang 0.65.0 available on SDKMAN! https://git.io/Jt24n
* 2021-02-05: gradle 6.8.2 available on SDKMAN!
================================================================================

No new candidates found at this time.


ATTENTION: A new version of SDKMAN is available...

The current version is , but you have 5.10.0+617.

Would you like to upgrade now? (Y/n): y

Updating SDKMAN...

```

**Additional details:**
- Which operating system or Linux distribution are you using?
System:
  Host: ******** Kernel: 5.4.0-65-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.4.8 Distro: Linux Mint 19.3 Tricia
zsh:
  zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

- How did you install Topgrade?
topgrade installed via cargo
- If a specific step is failing, what happens when you run the command on your own? (Run `topgrade --dry-run` to see which commands Topgrade is running)

```
―― 12:50:55 - SDKMAN! ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /bin/bash -c source /home/#######/.sdkman/bin/sdkman-init.sh && sdk selfupdate
Dry running: /bin/bash -c source /home/#######/.sdkman/bin/sdkman-init.sh && sdk update
Dry running: /bin/bash -c source /home/#######/.sdkman/bin/sdkman-init.sh && sdk upgrade

```

```
➜  ~ sdk update

No new candidates found at this time.
➜  ~ sdk selfupdate
No update available at this time.
```

<details><pre>
Topgrade 4.3.0
</pre></details>

**Comment by r-darwish** [comment]
The line `The current version is , but you have 5.10.0+617.` isn't printed by Topgrade. It's printed by SDKman. Topgrade doesn't try to parse SDKman version by itself.

**Comment by CzernyJ** [comment]
Ok I did not double-check the sdkman's own selfupdate output when an update is actually available.
