### ISSUE TITLE
Unable to install on ubuntu

### ISSUE THREAD

**Issue by ajft** [r-darwish/topgrade#63]
Completely unfamiliar with rust, cargo or any of its toolchain.   Successfully installed & using topgrade on a macOS system and tried to install it on my linux box:

I've installed cargo via "sudo apt install cargo" on a ubuntu 18.04 64 bit system

Then try "cargo install topgrade"

After downloading various components and doing its magic, it errors out with:

error[E0425]: cannot find function `read_to_string` in module `fs`
  --> src/linux.rs:27:27
   |
27 |         let content = fs::read_to_string("/etc/os-release")?;
   |                           ^^^^^^^^^^^^^^ did you mean `read_string`?

error[E0425]: cannot find function `read_to_string` in module `fs`
  --> src/config.rs:24:52
   |
24 |         let mut result: Self = toml::from_str(&fs::read_to_string(config_path)?)?;
   |                                                    ^^^^^^^^^^^^^^ did you mean `read_string`?
 : 
approx 200 other error lines
 : 
error: aborting due to 32 previous errors

error: failed to compile `topgrade v0.13.0`, intermediate artifacts can be found at `/tmp/cargo-install.gQMkxf4WQ5WN`

Caused by:
  Could not compile `topgrade`.

Caused by:
  process didn't exit successfully: `rustc --crate-name topgrade src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=ea68cdf97ff087b3 -C extra-filename=-ea68cdf97ff087b3 --out-dir /tmp/cargo-install.gQMkxf4WQ5WN/release/deps -L dependency=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps --extern termcolor=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libtermcolor-17b98b182474ca44.rlib --extern which=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libwhich-90150912dd020376.rlib --extern failure=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libfailure-d38be4717192ea51.rlib --extern shellexpand=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libshellexpand-18f5cebc3ad03f83.rlib --extern directories=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libdirectories-5eb4e2fc68390a36.rlib --extern env_logger=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libenv_logger-0ac71985b6c4b824.rlib --extern toml=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libtoml-27ea54fba0c740a9.rlib --extern serde_derive=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libserde_derive-356aa8c9a94cc2bc.so --extern serde=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libserde-737204b9eda1b67e.rlib --extern log=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/liblog-45ffdfeb3809bf3e.rlib --extern clap=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libclap-820466d79b7643a3.rlib --extern failure_derive=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libfailure_derive-b674c2ea6bd5fe02.so --extern term_size=/tmp/cargo-install.gQMkxf4WQ5WN/release/deps/libterm_size-8f9015e02373147c.rlib --cap-lints allow -L native=/tmp/cargo-install.gQMkxf4WQ5WN/release/build/backtrace-sys-0b70bb72646526bf/out` (exit code: 101)

**Comment by r-darwish** [comment]
I don't see which version of Rust are you using, but I assume that Ubuntu LTS doesn't ship the latest Rust. The problem is probably the fact that I never bothered supporting older Rust versions. I will try to see how much effort does it take to support the Rust version that ships with Ubuntu. Can you please give me the output of `rustc --version`?

In the meantime, I can suggest that you download `topgrade-v0.13.0-x86_64-unknown-linux-musl.tar.gz` from the release page. It should probably work on your system.

**Comment by ajft** [comment]
$ rustc --version
rustc 1.25.0

$ dpkg -l rustc
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                            Version              Architecture         Description
+++-===============================-====================-====================-====================================================================
ii  rustc                           1.25.0+dfsg1+llvm-0u amd64                Rust systems programming language

Yes, the binary from topgrade-v0.13.0-x86_64-unknown-linux-musl.tar.gz works just fine

thanks for hte help, you can probably close this if you like, I'll use the bin.

**Comment by r-darwish** [comment]
Will do. If I ever decide to support older Rust versions then I will update the README. If Topgrade will have enough Ubuntu users then I make a PPA for it.
