### ISSUE TITLE
Support for Zeal Docsets

### ISSUE THREAD

**Issue by MCOfficer** [r-darwish/topgrade#638]
**I want to suggest a new step**

***Which tool is this about? Where is its repository?***
[Zeal](https://github.com/zealdocs/zeal)

***Which operating systems are supported by this tool?***
Windows, MacOS, Linux

***What should Topgrade do to figure out if the tool needs to be invoked?***
On Linux, call `zeal` (it installs to PATH by default). On Windows and MacOS, more guessing may be needed.

***Which exact commands should Topgrade run?***
At the time of writing, this feature is still missing from zeal. See https://github.com/zealdocs/zeal/issues/986

**Comment by r-darwish** [comment]
Please reopen once the missing feature has been implemented in Zeal.
