### ISSUE TITLE
Feature: parallel updates

### ISSUE THREAD

**Issue by AlexanderWillner** [r-darwish/topgrade#640]
**I want to suggest some general feature**
Topgrade should be able to run the updates in parallel.

**More information**
I'd implemented a feature very similar to `topgrade` in `bash` in the past and used following simple method to parallelize the update processes:
```bash
runInBackground() {
  osascript -e 'tell application "Terminal" to do script "'"$1"'"'
}
type softwareupdate > /dev/null 2>&1 && runInBackground "softwareupdate -ia --include-config-data"
type brew > /dev/null 2>&1 && runInBackground "brew update && brew upgrade && brew upgrade --cask && brew cleanup -s"
...
```
Of course, we should discuss another way how to do this with `topgrade`.

**Comment by r-darwish** [comment]
I thought about it deeply at the begnning of Topgrade. Aside for being way to much job to do now, there are multiple potential problems:

1. We'll probably lose colors and fancy output if we redirect the stdout off all executed programs
2. Package managers won't be able to prompt the user of stdout is captured
3. There are kinds of possible race conditions, like trying to update cargo packages at the same time while updating rustup itself
4. We may cause a high load on the system if many package managers are invoked at the same time 

At the bottom line, upgrading your system is a process that may need your attention and intervention, so I rather keep the execution of things once at a time.

**Comment by SuperSandro2000** [comment]
> We'll probably lose colors and fancy output if we redirect the stdout off all executed programs

unbuffer can fix that.

**Comment by AlexanderWillner** [comment]
An alternative could be to implement `topgrade --list` (or similar) and then let the user implement something like this:

```bash
runInBackground() {
  osascript -e 'tell application "Terminal" to do script "'"$1"'"'
}
for app in $(topgrade --list); do
  runInBackground "topgrade --only $app"
done
```

**Comment by r-darwish** [comment]
You can get this list by parsing the output of `topgrade --help`

**Comment by AlexanderWillner** [comment]
> You can get this list by parsing the output of `topgrade --help`

Unfortunately, this would list all the available "plugins" not those that can be used on the local machine.

**Comment by r-darwish** [comment]
Sadly there's no easy way to implement such feature with the current architecture of Topgrade. You can also run `topgrade --dry-run` and maybe try to work with that output.
