### ISSUE TITLE
Invisible fail, worked on retry

### ISSUE THREAD

**Issue by jasikpark** [r-darwish/topgrade#644]
**What did you expect to happen?**
That when Microsoft AutoUpdate fails, it outputs some diagnostic info that lets me know what went wrong

**What actually happened?**
The command was reported as failed, but the logging displayed normally, with no indication anything was wrong. Selecting "retry" within topgrade worked, and it successfully ran on the second try, but there was no error message...
<img width="1036" alt="Screen Shot 2021-02-17 at 2 47 52 PM" src="https://user-images.githubusercontent.com/10626596/108266420-b2142b80-712f-11eb-8bf3-4b3974fb03d4.png">

**Additional details:**
- Which operating system or Linux distribution are you using? macOS 11.2.1
- How did you install Topgrade? brew

Run `topgrade --dry-run` to see which commands Topgrade is running. If the command seems wrong and you know why pleaes tell us so.
If the command seems fine try to run it yourself and tell us if you got a different result from Topgrade.

<details><pre>
Paste the output of `topgrade -v`
</pre></details>

**Comment by r-darwish** [comment]
I wish I understood the Microsoft updater better. There's no documentation that I know of about its exit codes. To be honest I mark it as an ignored step on my machine due to the unexplained failures

**Comment by jasikpark** [comment]
- https://docs.microsoft.com/en-us/officeupdates/release-history-microsoft-autoupdate
not really docs, but at least a vague changelog...

**Comment by r-darwish** [comment]
Sandly that doesn't tell much about the exit codes. Can you run Topgrade with `-v` so we'll see the exit code?
