### ISSUE TITLE
Improve VSCode speed by installing all extensions with one call

### ISSUE THREAD

**Issue by MCOfficer** [r-darwish/topgrade#647]
currently topgrade loops over all extensions and calls a command for each:
```
code --install-extension $EXTENSION_ONE --force
code --install-extension $EXTENSION_TWO --force
```

instead, code can accept multiple extensions, so it can only be called once:

```
code --install-extension $EXTENSION_ONE --install-extension $EXTENSION_TWO --force
```

Do you see any arguments against this? if not, i'm willing to open a PR.

**Comment by r-darwish** [comment]
Sounds good
