### ISSUE TITLE
Is it possible to support changelogs?

### ISSUE THREAD

**Issue by amituttam** [r-darwish/topgrade#649]
It would be nice if topgrade supports detailed changelogs where applicable? For example, topgrade was upgraded from v6.5.1 to v6.5.2, it would be great to have an option to list changes in this release. Another example, for debian packages that got upgraded, there are usually changelogs.

This feature would be useful as an audit of all the software that was upgraded and the changes included in them.

Thanks for considering.

**Comment by r-darwish** [comment]
You can find the changelog in the Github releases page. If you use the binaries from Github (which have a self-update feature) then You will see the changelog when Topgrade upgrades itself.
