### ISSUE TITLE
Sparkle for updates

### ISSUE THREAD

**Issue by kmplngj** [r-darwish/topgrade#657]
Topgrade should support [Sparkle](https://github.com/sparkle-project/Sparkle) for updates.

**More information**
Many macOS apps are using the sparkle framework to find and load updates. Would it be possible to update (or show) this apps with Topgrade?

There is a macOS GUI app that does this. It is called [Latest](https://github.com/mangerlahn/latest).

Best regards
Jan

**Comment by r-darwish** [comment]
Do you know if there's any command line utility that works like Latest?

**Comment by MCOfficer** [comment]
There's [sparkle-cli](https://sparkle-project.org/documentation/sparkle-cli/), but only in sparkle 2.0 (see https://github.com/sparkle-project/Sparkle/issues/1523 for adoption).

Also, TIL sparkle's author is kornelski. Doesn't that name sound familiar :D

**Comment by r-darwish** [comment]
I will do that once Sparkle 2.0 is out, but until it happens I have no way to test it. Please reopen this issue with Sparkle 2.0 is generally available.

**Comment by dec0dOS** [comment]
Seems that Sparkle 2.0 is out
https://github.com/sparkle-project/Sparkle/releases/tag/2.0.0

**Comment by dec0dOS** [comment]
Thanks for the awesome project! Any updates to this issue?

**Comment by r-darwish** [comment]
Could you explain what needs to run now? What's the name of the CLI tool and which arguments should Topgrade pass to it?

**Comment by dec0dOS** [comment]
Check the following docs:
https://sparkle-project.org/documentation/sparkle-cli/

**Comment by MCOfficer** [comment]
Is there any specific location sparkle-cli is installed to? is it in PATH? or do users just drop it somewhere, windows-style?

**Comment by r-darwish** [comment]
Also, it doesn't seem that this cli can detect and upgrade all Sparkle enabled apps. Is there any way to determine whether a specific App uses Sparkle?

**Comment by r-darwish** [comment]
@kmplngj @dec0dOS please advise

**Comment by dec0dOS** [comment]
Checking the `Frameworks` dir of the app should be the easiest solution, afaik.

![Screenshot 2022-05-28 at 21 10 23](https://user-images.githubusercontent.com/14824142/170837881-f9825928-551d-4ee4-a7af-8ac206bbc529.png)
![Screenshot 2022-05-28 at 21 10 28](https://user-images.githubusercontent.com/14824142/170837898-3eb5238d-be87-4a6f-8595-00a8e0f71450.png)

**Comment by kmplngj** [comment]
Great help from Sparkle dev! https://github.com/sparkle-project/Sparkle/issues/2131
