### ISSUE TITLE
steps/go: topgrade breaks updating the Go packages (or whatever) with Go 1.16

### ISSUE THREAD

**Issue by Akeshihiro** [r-darwish/topgrade#659]
**What did you expect to happen?**
Updating the Go packages correctly or whatever should be updated here.

**What actually happened?**
Failed to update the Go packages or whatever should be updated.
Message: `go get: cannot match "all": working directory is not part of a module`

**Additional details:**
- Which operating system or Linux distribution are you using?
  - `Arch linux running 5.10.16 linux kernel`
- How did you install Topgrade?
  - `yay -S topgrade` (AUR https://aur.archlinux.org/packages/topgrade/)

**Actual description:**
What is the intention of the Go step?

As of `topgrade --dry-run` topgrade tries to run `/usr/bin/go get -u all in /home/link/go` on the Go step (also this was what I saw in the code base). As of Go 1.16 the behavior of `go get` changed. In the previous versions `go get` could be used to eather download a Go package or to install a Go tool (if the package could be built as a command). Now with Go 1.16 `go get` does not support the installation of commands anymore but can only download the requested Go packages (libraries). To install a Go command/tool now you have to use `go install` explicitly. That's why `go get -u all` does not work anymore if the `go` command is executed outside of a Go module project.

Currently this behavior can be changed temporarily by using `GO111MODULE=auto|off go get -u all` but as of https://blog.golang.org/go116-module-changes Go 1.17 will ignore the GO111MODULE completly and so the GOPATH mode also. In other words Go 1.17 will drop the GOPATH mode completly and the GOMODULE mode will not only be the default but the only option to manage and develop Go projects.

So now I wonder what the initial intention was behind the Go step of topgrade so that one might be able to tackle this issue somehow, eather by changing the behaivor according to some kind of wanted or wishable behaivor or even by dropping the step completly as it would not have any effect in the future.

**Comment by r-darwish** [comment]
Is there a new recommended way to upgrade tools installed by `go install`?

**Comment by Akeshihiro** [comment]
The recommended way to install a Go tool is by running `go install <PathToGoToolRepo>@latest` to install tool with its latest version (or with another version as one might not want the latest version, e.g. `@v1.0.5`). The issue here is that the installed Go tools will be installed to `$(go env GOPATH)/bin` and the only information here would be the binaries name itselfs. It might be possible to filter all subdirectories of `$(go env GOPATH)/pkg/mod` according to the installed Go tools. For example for the Go tool installed by `go install github.com/stuff/stuff@latest` there would be the binary `$(go env GOPATH)/bin/stuff` and the corresponding source code directory `$(go env GOPATH)/pkg/mod/github.com/stuff/stuff@v1.0.0`. But there could be a more complex directory structure if the repo path has some further subdirectories. So at the end the directories with the pattern `**/<name>@<version>` are the one to be aware of and the parent directories do not matter at all. But this is only theory at the moment which does apply to most of the Go tools but I am not sure whether there are exceptions to this.

But yeah, this was the reason I was asking the initial intention behind the Go step of topgrade. Updating the Go libs would not make any sense to me because the libs are managed by the according Go project and updating the libs beforehand would not have any reasonable benefit here. So the only reason I could imagine was to update the Go tools, but this is a more complex task with Go 1.16.

**Comment by Akeshihiro** [comment]
The thing here is that the version suffix is only supported by Go 1.16, previous versions of Go do not support a version suffix. So for backward compatibility the current update behavior should be left for some time if Go <1.16 is installed.

**Comment by r-darwish** [comment]
I see. Yes, there was no intention to update libraries, only tools. I think that it's best to remove this step until Go implement some upgrade command
