### ISSUE TITLE
Failing Go Step

### ISSUE THREAD

**Issue by jasikpark** [r-darwish/topgrade#662]
**What did you expect to happen?**
...
Successful go upgrades

**What actually happened?**
...
```sh
―― 12:42:15 - Go ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
go get: cannot match "all": working directory is not part of a module

Retry? (y)es/(N)o/(s)hell
```

**Additional details:**
- Which operating system or Linux distribution are you using? macOS 11.2.1
- How did you install Topgrade? brew

Run `topgrade --dry-run` to see which commands Topgrade is running. If the command seems wrong and you know why pleaes tell us so.
If the command seems fine try to run it yourself and tell us if you got a different result from Topgrade.

<details><pre>
Paste the output of `topgrade -v`
</pre></details>

**Comment by r-darwish** [comment]
Go support has been removed from Topgrade. This will be deployed in the next released version.

**Comment by jasikpark** [comment]
Ok cool beans
