### ISSUE TITLE
[feature] Update caniuse database

### ISSUE THREAD

**Issue by bingalls** [r-darwish/topgrade#665]
**I want to suggest a new step**
***Which tool is this about? Where is its repository?***
Update local caniuse database
***Which operating systems are supported by this tool?***
Any OS running node >= v12 (?)
Important for gatsby-cli users, but may also benefit Vscode & Babel too.
***What should Topgrade do to figure out if the tool needs to be invoked?***
Always run for node.js users with a global install of babel or gatsby-cli
Any (further) check would be slower than the update command itself.
***Which exact commands should Topgrade run?***
`yes | npx browserslist@latest --update-db`

**I want to suggest some general feature**
Topgrade should keep list of browsers updated

**More information**
- Assuming that someone else implements the feature, please state if you know
  how to test it from a side branch of Topgrade

**Comment by r-darwish** [comment]
I'm assuimg you're talking about [this](https://github.com/sgentle/caniuse-cmd). I don't see where the README says something about updating the database.

**Comment by bingalls** [comment]
You use https://github.com/browserslist/browserslist to keep https://www.npmjs.com/package/caniuse-lite updated. It's used by several npm libraries.
