### ISSUE TITLE
Why is "fwupdmgr update" not run?

### ISSUE THREAD

**Issue by openjck** [r-darwish/topgrade#668]
Quick question. I see on the Wiki that `fwupdmgr` is run, but `fwupdmgr update` is not. I was wondering if you could explain why. I was thinking I'd add it as a custom step, but not if it's problematic in some way.

**Comment by r-darwish** [comment]
It's been a white since I used this tool so I don't exactly remember why did I implement it like this, but I think I chose this method because firmware upgrades are especially risky things, so I prefer notifing the user instead of automatically upgrade. I don't use this tool anymore so I don't mind calling `update` if you think it makes sense.

**Comment by openjck** [comment]
I don't have much experience with *fwupdmgr* either, to be honest. I actually first heard about it in topgrade. That says, it does prompt for confirmation, so unless the user has `assume_yes = true` set, they'll have a chance to read before the update is applied.

**Comment by Knusper** [comment]
I think the old approach was fare more reasonable - sorry.  The firmware update is a bit delicate, and I think you don't want to have this run automatically.   Maybe one could add it as a configuration option - but this now is not a reasonable default.  (I.e. imagine a user is on battery with his laptop and runs topgrade, then the firmware gets updated and the battery dies in the flashing process  - device is bricked).

(Sorry for spamming here - I commented in the wrong bug report before)

**Comment by Knusper** [comment]
Also on my device the new firmware is buggy - so I was quite in shock when I saw the new topgrade version automatically pulling and installing the firmware automatically.   I now disable this of course, but maybe you could revert it back to the old behaviour - just informing the user about firmware upgrades.  From your comments above it seems that you do not haven't recognised the magnitude of this change correctly.

**Comment by r-darwish** [comment]
Actually I consider skipping this step altogether. Firmware upgrades are risky, so maybe they shouldn't be handled by Topgrade at all

**Comment by Knusper** [comment]
Makes sense.

**Comment by ermshiperete** [comment]
I like it that topgrade checks if there is a new firmware upgrade available. However I agree that it should not run the update automatically, at least not by default.
