### ISSUE TITLE
Mac OS fails to upgrade Homebrew in custom location

### ISSUE THREAD

**Issue by gmadrid** [r-darwish/topgrade#673]
**What did you expect to happen?**
brew upgrade

**What actually happened?**
Nothing

**Additional details:**
- Which operating system or Linux distribution are you using?
   - MacOS Big Sur
- How did you install Topgrade?
   - `cargo install topgrade`

My computer is company owned, and system directories (including '/usr/local') are locked down. For this reason, I have installed Homebrew in $HOME/.homebrew. 

topgrade used to upgrade homebrew in this situation, since it just ran `brew` out of the PATH, but with the new ARM/Intel changes, it's running `brew` with an explicit, absolute path. This means that it fails to find `brew` and the upgrade doesn't run. 

Because this code is switched on OS and not by a feature, there is no simple way for me to build my own version that does what I need, and no command line flag I can use. I have to run `brew upgrade` by hand, which defeats the whole purpose of having `topgrade` installed.

**Comment by r-darwish** [comment]
@claui given a directory, is there any way for me to find out whether the brew installed in that directory is compiled for x86 or ARM?

**Comment by QiBaobin** [comment]
Same here I installed brew under my home directory: ~/homebrew/bin/brew

Brew Cask (ARM): SKIPPED: Cannot find "/opt/homebrew/bin/brew" in PATH
Brew Cask (Intel): SKIPPED: Cannot find "/usr/local/bin/brew" in PATH

**Comment by claui** [comment]
> @claui given a directory, is there any way for me to find out whether the brew installed in that directory is compiled for x86 or ARM?

@r-darwish Sorry, I no longer have a Mac.
