### ISSUE TITLE
[feature] minor updates for (node | ruby | etc) Version Managers

### ISSUE THREAD

**Issue by bingalls** [r-darwish/topgrade#678]
**Perform minor updates to Version Manager programs**

***Examples include***
* https://volta.sh/
* https://github.com/nvm-sh/nvm
* https://rvm.io/
pyenv works differently, and might not be feasible
Perhaps some Version Managers are already supported?

***All operating systems***
***What should Topgrade do to figure out if the tool needs to be invoked?***
Running update might be faster than checking actual version

***Which exact commands should Topgrade run?***
Example for Volta, the Node Version Manager:
```bash
volta list            # extract Version, e.g. 14.16.0
volta fetch node@14.16.0
volta install.      # overwrites any older 14.x version
```

**Comment by r-darwish** [comment]
In your example you installed a specfic version of node. I didn't see that any of these managers have a specific update command.

**Comment by bingalls** [comment]
The idea was that `volta list` would find the latest version, but I now believe that it does not work that way.
Perhaps `volta fetch node@lts` will do the trick.
Since this is not getting community support, I am closing this feature request.
