### ISSUE TITLE
Supporting custom commands to update git repos

### ISSUE THREAD

**Issue by amituttam** [r-darwish/topgrade#679]
Often, there are git repos that are part of a larger multi repository project. These projects have a single command like `jiri update`[1] or `repo sync`[2] to update repositories.

If would be great if topgrade can accept these commands to run to update these repositories.

[1] https://fuchsia.googlesource.com/jiri/
[2] https://source.android.com/setup/develop/repo

**Comment by r-darwish** [comment]
There's custom command support in the configuration. Doesn't that do what you want?

**Comment by amituttam** [comment]
Ah yes that works! I missed that. Thanks so much.
