### ISSUE TITLE
Can you please support skipping macOS App Store updates?

### ISSUE THREAD

**Issue by pro-sumer** [r-darwish/topgrade#681]
Unfortunately _mas_ [has trouble properly detecting macOS App Store updates](https://github.com/mas-cli/mas/issues/290). As a result _topgrade_ downloads and installs the same updates over and over again.

Can you please support skipping macOS App Store updates?

**Comment by r-darwish** [comment]
mas is the only tool that I know that does this. I'd be happy to use some 1st party tool but I'm not aware of any.

**Comment by pro-sumer** [comment]
_mas_ is great, when it works. But since it currently has issues it would be nice if we can configure _topgrade_ to skip this step:

 `--disable mas`
