### ISSUE TITLE
Remote host can't find cargo-update

### ISSUE THREAD

**Issue by amituttam** [r-darwish/topgrade#682]
I'm seeing this happen on multiple remote hosts:

```
―― (ct) 12:01:21 - Cargo ―――――――――――――――――――――――――――――――――――――――――――――――――――――――
cargo-update isn't installed so Topgrade can't upgrade cargo packages.
Install cargo-update by running `cargo install cargo-update`
```

I believe it is an issue with the path? i.e. Cargo is installed in the local users path: ~/.cargo/bin. I did set the remote topgrade path in my local host (the one that connects to the remote host):

```
# Path to Topgrade executable on remote machines
remote_topgrade_path = "/home/amituttam/.cargo/bin/topgrade"
```

Is there a way for me to set the remote cargo path as well? Or am I missing a setup/config item here.

**Comment by r-darwish** [comment]
I believe f9002b417cbf90a2971b406b81e230c581917464 will fix it. I will release a version with it tomorrow. Can you please reopen this issue if the next version doesn't fix it?

**Comment by amituttam** [comment]
That's great thanks! Will check it out.

**Comment by amituttam** [comment]
Is the release imminent? I haven't seen a new build this past couple of
days. Thanks
