### ISSUE TITLE
user customizable extension steps

### ISSUE THREAD

**Issue by jonbarksdale** [r-darwish/topgrade#685]
**I want to suggest some general feature**
Topgrade should allow me to specify an extension or set of extensions that call my unique updater, without having to commit to Topgrade. 

Use case - I work for a company that has some tools vended by another internal tool.  I can't patch this into topgrade as it would be considered confidential information, and would not be allowed by my organization.  Also not useful to anyone outside my company.  If, instead, topgrade was based on an extension model, then I or any other group could create extensions and compose them into topgrade.  Ideally, I could create this extension (likely one small file) and share it with others in my company. 

**More information**
- Presumably testing would include writing a trivial extension that's discovered and then executed.  I would also guess there are questions about blocking until complete, or possible thoughts around supporting parallelism in a future release to speed up updates.

**Comment by r-darwish** [comment]
You can specify custom commands in the configuration. Doesn't that do what you wish?

**Comment by jonbarksdale** [comment]
🤦‍♂️ yes, that'll do.  I don't know how I missed that when reading the docs last night.  Thanks for your patience.
