### ISSUE TITLE
How to disable oh-my-zsh upgrade?

### ISSUE THREAD

**Issue by jasek5** [r-darwish/topgrade#686]
Hello,
I am sorry, could someone explain to me how to disable the oh-my-zsh upgrade? It usually fails (due to git issues) I would like to disable it for me. However, I am unable to find a solution here...

I am sorry for the bother, I really love the projects - it really makes the process of upgrade much easier because I have to maintain quite a lot of different distros.
EDIT
It is apparently a git repository - which confused me.. but is it possible to make a list of whitelisted repositories only (specify the non-default list of repository which would override the default one)?

**Comment by r-darwish** [comment]
`--disable shell` should do that.

**Comment by jasek5** [comment]
nice - thank you !
