### ISSUE TITLE
Custom commands not executing in order?

### ISSUE THREAD

**Issue by amituttam** [r-darwish/topgrade#691]
The custom commands don't seem to be executing in order for me on Debian.

Notice that `Fuchsia - Sync tree` happens at the 4th step. This is fairly consistent and the order is the same.

Here is my topgrade config:
```
"Fuchsia - Sync tree" = "cd ~/fuchsia && git checkout master && .jiri_root/bin/jiri update -gc"
"Fuchsia - Build 1" = "cd ~/fuchsia && .jiri_root/bin/fx use out/default && .jiri_root/bin/fx build"
"Fuchsia - Build 2" = "cd ~/fuchsia && .jiri_root/bin/fx use out/workstation && .jiri_root/bin/fx build"
"Fuchsia - Run emulator" = "./run_emu.sh"
"Fuchsia - ffx test" = "cd ~/fuchsia && .jiri_root/bin/ffx target show && .jiri_root/bin/ffx target list"
```

Output when running topgrade:
```
―― 18:38:15 - Summary ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Fuchsia - Build 1: OK
Fuchsia - Build 2: OK
Fuchsia - Run emulator: OK
Fuchsia - Sync tree: OK
Fuchsia - ffx test: OK
```

**Comment by amituttam** [comment]
So this looks like it is because there is no guarantee to the order the config is stored:

```
        let contents = fs::read_to_string(&config_path).map_err(|e| {
            log::error!("Unable to read {}", config_path.display());
            e
        })?;

        let mut result: Self = toml::from_str(&contents).map_err(|e| {
            log::error!("Failed to deserialize {}", config_path.display());
            e
        })?;
```

`result` I believe needs to be a BTreeMap to get a stable order based on the Ord implementation for your key.

**Comment by r-darwish** [comment]
https://github.com/r-darwish/topgrade/blob/8c6a48af76a24c725a806c66b4bab65ed63208f2/src/config.rs#L60

Actually this is already a `BTreeMap`, so I'm not sure what's the solution

**Comment by SuperSandro2000** [comment]
I think they should be executed in the order they are in the config.

**Comment by r-darwish** [comment]
> https://github.com/r-darwish/topgrade/blob/8c6a48af76a24c725a806c66b4bab65ed63208f2/src/config.rs#L60
> 
> 
> 
> Actually this is already a `BTreeMap`,which is ordered by sorting the command names as you can see, so a mitigation will be to name the commands in their right order, but this isn't the desired behaviour. I should switch that to somwthing else

I didn't find any reasonable solution for this so I think the current workaround is reasonable

**Comment by SuperSandro2000** [comment]
The current workaround is really annoying especially if you have 30 custom commands and re-order them from time to time.
