### ISSUE TITLE
topgrade steps fails on wsl when launched by windows

### ISSUE THREAD

**Issue by webartoli** [r-darwish/topgrade#694]
**What did you expect to happen?**

I would like that launching this on windows
``` powershell
topgrade --only wsl
```

is equal to
``` bash
wsl
topgrade
```

**What actually happened?**
Launching topgrade via windows, will cause a failure with some packages: yarn, npm, pip3 in my case
Launching topgrade via linux shell it works like expected

**Additional details:**
- Windows 10
- WSL2, Ubuntu
- python and node installed via asdf (that requires .bashrc/.profile loading)
- default shell on wsl: bash (also tried fish with same results)

It seems that profile cannot be loaded properly.

`topgrade -v` does not shows intresting logs.

**Comment by r-darwish** [comment]
Where do you keep your profile settings? `~/.profile` or `~/.bashrc`?

**Comment by webartoli** [comment]
I've tried both of them with same results

**Comment by webartoli** [comment]
I've find out where was the problem.

1) Inclusions must be on `.profile`
2) `.profile` must not echo any string

This because topgrade normally launches 
```
C:\\windows\\system32\\wsl.EXE" "bash" "-c" "TOPGRADE_PREFIX=WSL exec /usr/local/bin/topgrade\n
```

But if profile files perform some echo like this

``` bash
echo foo bar
```
this string is injected into the command like below:
```
C:\\windows\\system32\\wsl.EXE" "bash" "-c" "TOPGRADE_PREFIX=WSL exec foo bar\n /usr/local/bin/topgrade\n
```

I have solved my own issue, but I think that topgrade should not be affected by an eventual .profile output
