### ISSUE TITLE
Microsoft AutoUpdate step on Mac goes into an infinite loop saying "Daemon is busy..."

### ISSUE THREAD

**Issue by sankalp-khare** [r-darwish/topgrade#698]
Lately (noticing this in the past week or two) my topgrade run gets stuck on the Microsoft AutoUpdate step, as under:
```
―― 12:41:53 - Microsoft AutoUpdate ―――――――――――――――――――――――――――――――――――――――――――――
Checking for updates...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
Daemon is busy...
... (same thing over and over again until I intervene)
```
I'm considering disabling that step in the Topgrade Config, but would like to report this to you as well. Please let me know if I can provide any diagnostic information to help debug this.

Thanks for creating topgrade. It is a wonderful addition to my mac setup.

**Comment by sankalp-khare** [comment]
When I press Ctrl+C to try to abort that, it prints a message but then continues to output the same lines:
```
Daemon is busy...
^CDetecting and downloading updates...
Daemon is busy...
```

**Comment by sankalp-khare** [comment]
In the 2nd Ctrl + C the thing exits and I move on to the next stage of the topgrade run (without the usual "retry / abort ..." choice from Topgrade.

**Comment by sankalp-khare** [comment]
Seems like a `msupdate` bug though:
```
❯ "/Library/Application Support/Microsoft/MAU2.0/Microsoft AutoUpdate.app/Contents/MacOS/msupdate" -
l
Checking for updates...
Daemon is busy...
Daemon is busy...
Daemon is busy...
```
Any idea where/how we can report this to them?

**Comment by r-darwish** [comment]
I think about getting rid of this step as well. It's very unstable.

**Comment by sankalp-khare** [comment]
For anyone else reading this, you can disable it in the topgrade config: https://github.com/sankalp-khare/dotfiles/blob/3078b1d045ac645a8dd96346e0ff187db52e1494/.config/topgrade.toml#L6
