### ISSUE TITLE
 Self update error: ReleaseError: No asset found for target: `x86_64-unknown-linux-gnu`

### ISSUE THREAD

**Issue by comatosejones** [r-darwish/topgrade#715]
**What did you expect to happen?**
...
error when binary version of topgrade attempts self update.

**What actually happened?**
...

**Additional details:**
- Which operating system or Linux distribution are you using?
- How did you install Topgrade?

Run `topgrade --dry-run` to see which commands Topgrade is running. If the command seems wrong and you know why pleaes tell us so.
If the command seems fine try to run it yourself and tell us if you got a different result from Topgrade.

<details><pre>
Paste the output of `topgrade -v`
</pre></details>

**Comment by r-darwish** [comment]
This is.a temporary failure. I just released a version and binary building was not finished yet.

**Comment by comatosejones** [comment]
ty
