### ISSUE TITLE
Self Update fails on x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by msuesskraut** [r-darwish/topgrade#731]
**What did you expect to happen?**

Self update on `x86_64-unknown-linux-gnu` updates to _7.0.1_.

**What actually happened?**

Self Update fails:

```
―― 19:46:50 - Self update ――――――――――――――――――――――――――――――――――――――――――――――――――――――
Self update error: ReleaseError: No asset found for target: `x86_64-unknown-linux-gnu`
```

**Additional details:**
- WSL with Ubuntu-16.04 on Windows 10
- Binary from Github
   - Self updates worked for previous releases

Release 7.0.1 does not contain a binary for `x86_64-unknown-linux-gnu`: https://github.com/r-darwish/topgrade/releases/tag/v7.0.1

Note: Release is 5h old at the time of creating this issue.

**Comment by MCOfficer** [comment]
The CI failed, see https://github.com/r-darwish/topgrade/issues/730#issuecomment-857742172

For 99% of devices, the musl build should work as drop-in replacement for the time being.

**Comment by r-darwish** [comment]
Should be fixed now
