### ISSUE TITLE
Updating flatpak on remote system fails

### ISSUE THREAD

**Issue by ermshiperete** [r-darwish/topgrade#737]
I have topgrade configured to update a remote machine (which runs Ubuntu 20.04; connection through ssh). The remote machine has several system flatpak packages that topgrade tries to update.

**What did you expect to happen?**

Flatpak packages get successfully updated.

**What actually happened?**

Flatpak update fails and outputs messages like:

```
Warning: Flatpak system operation Deploy not allowed for user
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user
Error: Flatpak system operation Deploy not allowed for user
```

**Additional details:**
- Which operating system or Linux distribution are you using?
  _Ubuntu 20.04_

Running `flatpak --system update` works on the remote system. Running `sudo flatpak --system update` works when connected over ssh, running `flatpak --system update` when connected over ssh shows the same errors as topgrade.

<details><pre>
Running `topgrade -v --only flatpak` on the remote system connected through ssh:

―― 20:49:59 - Self update ――
Topgrade is up-to-date
―― 20:49:59 - Flatpak User Packages ――
Looking for updates…
Nothing to do.
Looking for updates…
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.gimp.GIMP
Info: org.freedesktop.Platform//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.tntware.TntConnect
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.VAAPI.Intel//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.VAAPI.Intel//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Required runtime for org.gimp.GIMP/x86_64/stable (runtime/org.gnome.Platform/x86_64/40) found in remote flathub

New org.gimp.GIMP permissions:
    file access [1]

    [1] xdg-run/gvfsd

 1.	   	org.gnome.Platform	40	i	flathub	< 362.6 MB
 2.	   	org.gimp.GIMP	stable	u	gimp-origin	< 117.2 MB
 3.	   	org.gnome.Platform	3.38	u	flathub	< 345.5 MB
 4.	   	com.dropbox.Client	stable	u	flathub	< 102.6 MB
 5.	   	org.freedesktop.Platform	20.08	u	flathub	< 267.0 MB
 6.	   	us.zoom.Zoom	stable	u	flathub	< 52.5 MB
 7.	   	org.kde.KStyle.Adwaita	5.14	i	flathub	< 6.6 MB
 8.	   	org.kde.KStyle.Adwaita	5.15	i	flathub	< 6.4 MB
 9.	   	org.kde.Platform.Locale	5.15	u	flathub	< 341.3 MB (partial)
10.	   	org.kde.PlatformTheme.QGnomePlatform.Sources	5.15	u	flathub	< 477.7 kB
11.	   	org.kde.PlatformTheme.QGnomePlatform	5.15	u	flathub	< 9.5 MB
12.	   	org.kde.WaylandDecoration.QGnomePlatform-decoration	5.15	u	flathub	< 10.0 MB
13.	   	org.kde.Platform	5.15	u	flathub	< 368.5 MB
14.	   	org.kde.WaylandDecoration.QGnomePlatform_decoration.Sources	5.15	u	flathub	< 477.7 kB
15.	   	org.freedesktop.Platform.Locale	18.08	r
16.	   	org.freedesktop.Platform.VAAPI.Intel	18.08	r
17.	   	org.freedesktop.Platform.html5-codecs	18.08	r
18.	   	org.freedesktop.Platform	18.08	r
19.	   	org.gnome.Platform.Locale	3.36	r
20.	   	org.gnome.Platform	3.36	r

Installing 1/20…                                                                                              
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Installing 1/20…                        0%  0 bytes/s
Installing 1/20… ████████████████████ 100%
Info: org.gimp.GIMP was skipped                                                                                 

Updating 2/20…                                                                                                
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 2/20…                        0%  0 bytes/s
Updating 2/20… ████████████████████ 100%
Updating 3/20…                                                                                                
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 3/20…                        0%  0 bytes/s
Updating 3/20… █                      5%
Updating 3/20… ███▍                  17%  10.9 MB/s
Updating 3/20… █████▌                28%  11.3 MB/s
Updating 3/20… ███████▌              38%  11.4 MB/s
Updating 3/20… █████████▊            49%  11.5 MB/s  00:04
Updating 3/20… ████████████          60%  11.5 MB/s  00:03
Updating 3/20… ██████████████        70%  11.6 MB/s  00:02
Updating 3/20… ████████████████▏     81%  11.6 MB/s  00:01
Updating 3/20… ██████████████████▏   91%  11.6 MB/s  00:00
Updating 3/20… ████████████████████ 100%  12.7 MB/s  00:00
Updating 4/20…                                                                                                
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 4/20…                        0%  0 bytes/s
Updating 4/20… ████████████████████ 100%
Updating 5/20…                                                                                                
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 5/20…                        0%  0 bytes/s
Updating 5/20… █                      5%
Updating 5/20… █████▏                26%  10.8 MB/s
Updating 5/20… █████████▍            47%  11.2 MB/s
Updating 5/20… █████████████▌        68%  11.4 MB/s
Updating 5/20… █████████████████▌    88%  11.5 MB/s  00:00
Updating 5/20… ████████████████████ 100%  13.1 MB/s  00:00
Installing 6/20…                                                                                              
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Installing 6/20…                        0%  0 bytes/s
Installing 6/20… ████████████████████ 100%
Installing 7/20…                                                                                              
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Installing 7/20…                        0%  0 bytes/s
Installing 7/20… ████████████████████ 100%
Updating 8/20…                                                                                                
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 8/20…                        0%  0 bytes/s
Updating 8/20… ████████████████████ 100%
Updating 9/20…                                                                                                
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 9/20…                        0%  0 bytes/s
Updating 9/20… ████████████████████ 100%
Updating 10/20…                                                                                               
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 10/20…                        0%  0 bytes/s
Updating 10/20… ████████████████████ 100%
Updating 11/20…                                                                                               
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 11/20…                        0%  0 bytes/s
Updating 11/20… ████████████████████ 100%
Updating 12/20…                                                                                               
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 12/20…                        0%  0 bytes/s
Updating 12/20… ████████████████████ 100%
Updating 13/20…                                                                                               
Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user

Updating 13/20…                        0%  0 bytes/s
Updating 13/20… ████████████████████ 100%
Uninstalling 14/20…                                                                                           
Uninstalling 15/20…                                                                                           
Uninstalling 16/20…                                                                                           
Uninstalling 17/20…                                                                                           
Uninstalling 18/20…                                                                                           
Uninstalling 19/20…                                                                                           
Changes complete.                                                                                               
―― 20:50:18 - Summary ――
Flatpak: FAILED

</pre></details>

**Comment by ermshiperete** [comment]
Cf #107

**Comment by r-darwish** [comment]
@brx75 since you recommended avoiding sudo, can you tell why is it failing for @ermshiperete ?

**Comment by ermshiperete** [comment]
I think I found the reason why it's failing over ssh:
`/usr/share/polkit-1/rules.d/org.freedesktop.Flatpak.rules` checks for `subject.local == true` which isn't true when running over ssh.

**Comment by r-darwish** [comment]
> I think I found the reason why it's failing over ssh:
> `/usr/share/polkit-1/rules.d/org.freedesktop.Flatpak.rules` checks for `subject.local == true` which isn't true when running over ssh.

Very weird. I wonder what's the logic behind that.
