### ISSUE TITLE
Automatically run flatpak with sudo when running on remote machine

### ISSUE THREAD

**Issue by ermshiperete** [r-darwish/topgrade#740]
This is a follow-up of #737. 

It would be nice if `topgrade` would detect that it runs remote (connected through ssh) and if that's the case calls `flatpak update` with `sudo`.

See [comment in #737](https://github.com/r-darwish/topgrade/issues/737#issuecomment-871653951)

**Comment by r-darwish** [comment]
Before we do that we should have a better understanding about what makes it in SSH so that flatpak can't take root permissions by itself, as it should.
