### ISSUE TITLE
Support sudoloop

### ISSUE THREAD

**Issue by tuxiqae** [r-darwish/topgrade#741]
**I want to suggest a new step**
Both `paru` and `yay` support `sudoloop`, a feature which handles the sudo connection open by calling it in the background.
I want Topgrade to support it by default.
 
***Which tool is this about? Where is its repository?***
I know about it being supported in both paru and yay, might be found in other package managers as well.

***Which operating systems are supported by this feature?***
Arch Linux, maybe others as well.
***What should Topgrade do to figure out if the tool needs to be invoked?***
I would enable it by default, and will allow to disable it with flags or configuration
 
***Which exact commands should Topgrade run?***
- `paru --sudoloop`
- `yay --sudoloop`

**Comment by MCOfficer** [comment]
@r-darwish i'm thinking about PRing this, would you prefer if it was configurable? If yes, should it be default on or off?

**Comment by r-darwish** [comment]
This flag can be controlled by setting `~/.config/yay/config.json`. It's disable for security reasons, so I don't see why Topgrade should handle it.
