### ISSUE TITLE
nix step fails when doas is installed

### ISSUE THREAD

**Issue by 234d** [r-darwish/topgrade#742]
The nix step fails since it passes `-i` to what it assumes is `sudo`. Since `doas` is preferred and it doesn't have that option it fails. 

Haven't used nix yet but assume it needs the setup done through `/etc/profile.d/nix{,-daemon}.sh`.

[Nix command](https://github.com/r-darwish/topgrade/blob/develop/src/steps/os/unix.rs#L192)
[sudo function](https://github.com/r-darwish/topgrade/blob/develop/src/utils.rs#L105)

Output:
```
―― 12:22:43 - Nix ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
/usr/bin/doas: invalid option -- 'i'
usage: doas [-Lns] [-C config] [-u user] command [args]
```

**Comment by r-darwish** [comment]
I didn't remember why did we made this changes so I checked. Apperantly [we already knew](https://github.com/r-darwish/topgrade/pull/650#issuecomment-782831694) that this will break with `doas`. The question now is what should we do to solve it.

**Comment by Akeshihiro** [comment]
According to the most recent version of the OpenBSD `doas` (see https://man.openbsd.org/doas) the default behavior of `doas` is to switch the execution environment to the target user's environment.

>By default, a new environment is created. The variables HOME, LOGNAME, PATH, SHELL, and USER and the umask(2) are set to values appropriate for the target user. DOAS_USER is set to the name of the user executing doas. The variables DISPLAY and TERM are inherited from the current environment. This behavior may be modified by the config file. The working directory is not changed.

And from the `sudo` manpage:

>-i [command]
The -i (simulate initial login) option runs the shell specified by the password database entry of the target user as a login shell. This means that login-specific resource files such as .profile or .login will be read by the shell. If a command is specified, it is passed to the shell for execution via the shell's -c option. If no command is specified, an interactive shell is executed. sudo attempts to change to that user's home directory before running the shell. The security policy shall initialize the environment to a minimal set of variables, similar to what is present when a user logs in. The Command Environment section in the sudoers(5) manual documents how the -i option affects the environment in which a command is run when the sudoers policy is in use.

I think based on the actual intention running `doas` could be enough. On the other hand `sudo -i` does some more stuff like switch `$PWD` to the user's home directory whereas `doas` keeps the `$PWD` from the caller.

I know that some Linux distributions like Arch Linux or Gentoo Linux use the OpenDoas (https://github.com/Duncaen/OpenDoas) fork, but I don't know whether this is true for other linux distributions. So there might be some further investigation needed.

Maybe this information helps somehow :)

**Comment by r-darwish** [comment]
Fixed
