### ISSUE TITLE
Ability to disable pnpm

### ISSUE THREAD

**Issue by hildjj** [r-darwish/topgrade#743]
I would like the ability to add `"pnpm"` to the list of disabled steps.

I don't like to use pnpm to manage my global dependencies, so I would like to disable having `pnpm upgrade -g` run during the node step.  I would like to add this to my `topgrade.toml` file:

```toml
disable = ["pnpm"]
```

and have `npm` continue to work.  I would imagine someone else might like to disable `deno`, which is handled the same way as `pnpm`.

**More information**
- I will be able to test this from a branch if needed.

**Comment by sheeepdev** [comment]
How can I disable npm?

**Comment by MCOfficer** [comment]
> How can I disable npm?
```toml
disable = ["node"]
```

**Comment by sheeepdev** [comment]
Thanks
