### ISSUE TITLE
Feature: link to mac-cleanup

### ISSUE THREAD

**Issue by bingalls** [r-darwish/topgrade#746]
**I want to suggest some general feature**
Please add a link in README.md to https://github.com/fwartner/mac-cleanup

**Comment by MCOfficer** [comment]
Why? Which section in the readme would this improve, and if it's a new section, why should it be added?

At this point im neither in favor nor against in, i just dont understand.

**Comment by bingalls** [comment]
mac-cleanup combines for a complete F/OSS periodic MacOS maintenance.
It removes the previous versions that topgrade upgraded.
Many Github projects include a _Related Links_ section at the bottom of their README.md s

**Comment by r-darwish** [comment]
Topgrade already has a cleanup flag. I see no reason to put this on the readme.

**Comment by fwartner** [comment]
Hey.. I am the maintainer of mac-cleanup.

TBH.. I have no idea why this should be done by anyone of us since mac-cleanup also has an update flag. :D 

But anyways. Cool project btw!
