### ISSUE TITLE
Add support for pkgsrc/pkgin

### ISSUE THREAD

**Issue by selfagency** [r-darwish/topgrade#748]
**I want to suggest a new step**

Yes

***Which tool is this about? Where is its repository?***

[pkgsrc](https://pkgsrc.joyent.com/) / [pkgin](https://pkgin.net/)

***Which operating systems are supported by this tool?***

SmartOS/illumos, macOS, Linux, and NetBSD

***What should Topgrade do to figure out if the tool needs to be invoked?***

`sudo pkgin upgrade` will report whether there are any packages to upgrade.

***Which exact commands should Topgrade run?***

`sudo pkgin update -y`, `sudo pkgin upgrade -y`

**Comment by MCOfficer** [comment]
> _**What should Topgrade do to figure out if the tool needs to be invoked?**_
> 
> `sudo pkgin upgrade` will report whether there are any packages to upgrade.


I believe this section wants to say "how should topgrade recognize systems for which it should run the `pkgin` step. For example, if it's a native package manager preinstalled on all such distros (see `apt`) you could look into lsb_release for the distro name. Another approach is to check if `pkgin` is in PATH or at a certain location.
