### ISSUE TITLE
Upgrade pip packages specifically installed with pipsi / pipx

### ISSUE THREAD

**Issue by jasikpark** [r-darwish/topgrade#76]
I've been researching a bit of #60 and I've found [pipsi](https://github.com/mitsuhiko/pipsi), which seems to be a good option to reccomend for python packages you want to be updated by topgrade.

It puts each cli program into their own virtualenv so that it doesn't mess with the global pip dependencies.

Idk whether it supports a `pipsi update all packages` command, but it seems worth looking into.

**Comment by r-darwish** [comment]
Looks interesting. Thank you for sharing this.

**Comment by r-darwish** [comment]
We'll do that once https://github.com/mitsuhiko/pipsi/pull/179 is merged

**Comment by r-darwish** [comment]
pipsi doesn't seem to be maintained anymore. I'll implement it for [pipx](https://github.com/cs01/pipx)

**Comment by jasikpark** [comment]
that sounds like a great idea  


--  
Caleb Jasik  
calebjasik@jasik.xyz(mailto:calebjasik@jasik.xyz)
https://jasik.xyz
281.614.9841(tel:281.614.9841)

**Comment by jasikpark** [comment]
just call `pipx upgrade-all` to upgrade all global packages.
