### ISSUE TITLE
Not possible to download topgrade-v7.1.0-x86_64-unknown-linux-gnu.tar.gz

### ISSUE THREAD

**Issue by mavaa** [r-darwish/topgrade#760]
**What did you expect to happen?**
...
Being able to download the file from the release page: https://github.com/r-darwish/topgrade/releases/tag/v7.1.0

**What actually happened?**
...
An AWS(?) error is shown and it's not possible to download anything. The error is pasted at the bottom

**Additional details:**
So I'm not sure if this is a topgrade, GitHub or Amazon issue, but there seems to be a problem with the 7.1.0 file "topgrade-v7.1.0-x86_64-unknown-linux-gnu.tar.gz"

I'm able to download all the other files from the same release, and I've tried using Chromium, Firefox and Qutebrowser. I also tested from my phone on 4G, so I don't think it's a local issue? I've removed some of the fields from the message below as I'm not familiar enough to rule out this being some kind of security issue, but I have the complete file stored locally if that's of interest. Maybe simply re-uploading will fix it?

Interestingly, I am pretty sure I downloaded this exact file on another machine a few weeks ago without issue.

Direct link to the download: https://github.com/r-darwish/topgrade/releases/download/v7.1.0/topgrade-v7.1.0-x86_64-unknown-linux-gnu.tar.gz

Error message:
```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<AWSAccessKeyId>**REMOVED**</AWSAccessKeyId>
<StringToSign>**REMOVED**/us-east-1/s3/aws4_request **REMOVED**</StringToSign>
<SignatureProvided>**REMOVED**</SignatureProvided>
<StringToSignBytes>**REMOVED**</StringToSignBytes>
<CanonicalRequest>GET /**REMOVED** X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=**REMOVED**%2F20210920%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210920T205313Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=135351354&response-content-disposition=attachment%3B%20filename%3Dtopgrade-v7.1.0-x86_64-unknown-linux-gnu.tar.gz&response-content-type=application%2Foctet-stream host:github-production-release-asset-2e65be.s3.amazonaws.com host UNSIGNED-PAYLOAD</CanonicalRequest>
<CanonicalRequestBytes>**REMOVED**</CanonicalRequestBytes>
<RequestId>**REMOVED**</RequestId>
<HostId>**REMOVED**</HostId>
</Error>
```

**EDIT:**

I checked the other computer I was talking about, and the file was indeed in my downloads folder. Downloaded septemper 16th, so somethig must have happened to the file since then.

**Comment by MCOfficer** [comment]
Reproduced. I'd recommend bring this to github support, something is probably borked on their end.

**Comment by mavaa** [comment]
Checked again today, and now it's back again somehow. Not sure if this issue should just be closed or reported to GitHub somehow?

**Comment by MCOfficer** [comment]
I'd assume they're on top of things, they have all kinds of metrics about their network.
