### ISSUE TITLE
QQ about the versioning scheme

### ISSUE THREAD

**Issue by chenrui333** [r-darwish/topgrade#793]
It looks like topgrade is using `v99.99.99` for the dev releases, but I could not find any documentation for it, can it be clarified in somewhere? Thanks!

**Comment by r-darwish** [comment]
I should delete the v99 version. I used that only for an experiment to migrate my release pipeline from Travis to Github actions. It has no further use

**Comment by r-darwish** [comment]
Just deleted all of these tags

**Comment by chenrui333** [comment]
Thank you!
