### ISSUE TITLE
Pacdiff support

### ISSUE THREAD

**Issue by mhaessig** [r-darwish/topgrade#794]
**I want to suggest a new step**
Because I don't fancy `etc_update`, I'm running `pacdiff` as a custom command, but I figured it might be useful for other people on arch as well.

***Which tool is this about? Where is its repository?***
[`pacdiff`](https://man.archlinux.org/man/pacdiff.8.en) looks for `.pacorig`, `.pacnew`, and `.pacsave` files and helps in merging the changes. It is more or less an arch specific tool of `etc_update`.

***Which operating systems are supported by this tool?***
Any linux distro using `pacman` as a package manager.

***What should Topgrade do to figure out if the tool needs to be invoked?***
Now for why I'm starting this issue: I see three different approaches to implement this, and I figured this needs a little bit of discussion:
1. Just add it as a new step
2. Have it as a second option in the step that is currently only `etc_update`. That would make it a more general "clean up etc" step with multiple tools that could do the job.
3. Add an arch specific option to run `pacdiff` instead of just showing the `.pacnew` files.
I think I prefer option 3, but I would value input.

***Which exact commands should Topgrade run?***
`sudo pacdiff`

I would implement the feature, but I would appreciate feedback on how it should be done.

**Comment by r-darwish** [comment]
I think it should be added as a new step
