### ISSUE TITLE
Feature request: support vcpkg

### ISSUE THREAD

**Issue by bbigras** [r-darwish/topgrade#81]
[vcpkg](https://github.com/Microsoft/vcpkg) is a Microsoft tool to install and update librairies (sdl2, sqlite3...) on Windows/Linux/MacOS. I find it most useful on Windows.

**Comment by r-darwish** [comment]
Does it have any "upgrade everything" subcommand? Because according to [this](https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-update-libraries) it seems that `vcpkg upgrade` only lists out of date packages.

**Comment by ras0219-msft** [comment]
@r-darwish That FAQ is referring to `vcpkg update`, which does currently only list a diff of currently outdated packages. However, we have added a `vcpkg upgrade` which will run the upgrade everything :)

Note that pulling new versions to power the above command is still completely under the user's control via `git pull`.

**Comment by r-darwish** [comment]
I don't have a working `vcpkg` setup at the moment. If I add the appropriate command and push it to a side branch, would you be able to check if it is working as expected?

**Comment by bbigras** [comment]
I would be willing to test. Maybe @ras0219-msft could test it better.

**Comment by ras0219-msft** [comment]
You'll also need to add `--no-dry-run` if you're invoking this from a script; because upgrading is so invasive (it can rebuild a _lot_ of things), we default to printing the plan and asking the user to re-run the command to confirm.

**Comment by r-darwish** [comment]
@ras0219-msft no problem :smile: 
I pushed the commit containing this flag.

**Comment by r-darwish** [comment]
Could you guys confirm whether the current implementation is sufficient?

**Comment by bbigras** [comment]
It works but in my case it needs a `git pull` first. It seems the way to install `vcpkg` is to do a `git clone` and then run a bootstrap script. And do a `git pull` every time before running `vcpkg update`.

```
PS D:\dev\topgrade> vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
```
