### ISSUE TITLE
python3 packages upgrade failing

### ISSUE THREAD

**Issue by muralikodali** [r-darwish/topgrade#810]
topgrade fails to upgrade python3 packages giving following error : 

```
/home/zenova/projects/pyenv/.pyenv/pyenv.d/exec/pip-rehash/pip: line 20: 60533 Segmentation fault      (core dumped) "$PYENV_COMMAND_PATH" "$@"
Defaulting to user installation because normal site-packages is not writeable
ERROR: You must give at least one requirement to install (see "pip help install")
```

**Comment by r-darwish** [comment]
Are you launching topgrade inside a virtual environment?

**Comment by muralikodali** [comment]
i am not launching inside a virtual environment.
i am using topgrade for the past three years (upgrading packages every month) with same setup.

using pyenv to manage local python environment.
![screenshot_20211215185417](https://user-images.githubusercontent.com/11482766/146194888-656afe35-64db-49f2-8261-3ef3620783e0.png)

**Comment by muralikodali** [comment]
this is a problem with pyenv (python package manager).

deleting ~/.pyenv and reinstalling solved the problem.
