### ISSUE TITLE
Topgrade should consider other diff progs

### ISSUE THREAD

**Issue by PolpOnline** [r-darwish/topgrade#811]
Hi, just noticed you released v8.1.2 and the changelog says `Don't run pacdiff if vim isn't installed` and that's right because pacdiff works by default with `vimdiff`.
However, [pacdiff can also use other programs to show the differences](https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave#pacdiff) by setting the `$DIFFPROG` enviromment variable (I personally set my diffprog variable in `~/.profile` and then passed the variable through `sudo` by modifying `/etc/sudo.conf`).

**Comment by MCOfficer** [comment]
Just so we're on the same page: topgrade should run pacdiff when either vim is installed, or `$DIFFPROG` is set?
