### ISSUE TITLE
Cargo warns about unused fields in `OsRelease` (`steps/os/linux.rs`)

### ISSUE THREAD

**Issue by SanchithHegde** [r-darwish/topgrade#812]
Running `cargo check` produces 2 warnings:

```
warning: field is never read: `id_like`
  --> src/steps/os/linux.rs:20:5
   |
20 |     id_like: Option<String>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: field is never read: `id`
  --> src/steps/os/linux.rs:21:5
   |
21 |     id: String,
   |     ^^^^^^^^^^
```

I ran a quick `rg OsRelease` and it returned only one result, the struct definition:
https://github.com/r-darwish/topgrade/blob/0a7d576b59a86c22292e4a0f04d98326df9a420c/src/steps/os/linux.rs#L19-L22

I went through the code, and it seems that `id` and `id_like` variables are assigned, but no instance of the `OsRelease` struct is constructed. 
https://github.com/r-darwish/topgrade/blob/0a7d576b59a86c22292e4a0f04d98326df9a420c/src/steps/os/linux.rs#L46-L47

I have opened this issue to bring it to your notice, you can decide whether to remove the unused struct definition, or to construct an instance of the struct and use it later in the code.

**Comment by MCOfficer** [comment]
What branch is this on? on the current `develop` (specifically 0a7d576b59a86c22292e4a0f04d98326df9a420c), neither `cargo clippy` nor `cargo check` give me any warnings.

**Comment by SanchithHegde** [comment]
@MCOfficer  It's on `develop` (specifically, 0a7d576b59a86c22292e4a0f04d98326df9a420c), with:

```shell
$ cargo version
cargo 1.57.0 (b2e52d7ca 2021-10-21)
$ rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)
```

**Comment by MCOfficer** [comment]
Can reproduce, thank you. I didn't even think about having an outdated cargo.

**Comment by SanchithHegde** [comment]
Well, `topgrade` helps me ensure that I always have the latest stable toolchain installed! :laughing:
