### ISSUE TITLE
W10: Parallel execution of Win-Get and Choco will lead to parallel installations and downgrades

### ISSUE THREAD

**Issue by froeb** [r-darwish/topgrade#820]
**What did you expect to happen?**
- Win-get and chocolatey should run in sequence not parallel.
- In any case, it should be made sure that an update only happensm when the version to be updated to is newer then the already 
installed verison (=no downgrade)
- if this is not possible, it should be possilbe to either disable choco or (preferable) win-get

**What actually happened?**
- topgrade spans an own windows for chocolatey
- in parallel to the chocolatey windows upgrading the software, teh main topgrade windows/task starts win-get. Win-get seems to upgrade many (but not all it seems) of the same programs chocolatey is checking and upgrading in the other task/window (and otoh chocolatey seems to upgrade many (but not all) of the same programs win-get tries to checlk and update,
- worst, it seems that win-get will happily downgrade newer versions installed by chocolatey to an older version by overwriting them with new downloaded program, regardless if a newer version has been isntalled. 

**Additional details:**
- Which operating system or Linux distribution are you using?
Windows 10, Versoion W20H2, Build 19042.1415
Topgrade 8.1.2
Chocolatey 0.11.3

**Comment by r-darwish** [comment]
Sounds weird. I never saw that Topgrade spawns choco in its own window. How did you install choco and what exactly is the binary of your `choco` command? Is it possible that you have some shell script that runs the choco exe itself?

**Comment by Lim-Dul** [comment]
Actually this is a bug with winget, not with topgrade.
You can see discussions about it in winget's repo. Somehow winget recognizes executables that have been installed via other means but sometimes cannot determine their versions. This also leads to "infinite upgrade loops" in winget.
Until they implement slightly more conservative upgrade paths (e.g. update only things installed via winget) I would strongly suggest disabling winget updates if you are already working with Chocolatey.
Which is generally a good idea - not mixing update managers and repos trying to do exactly the same thing.

**Comment by r-darwish** [comment]
I'll probably do that. I myself encountered various issues with winget

**Comment by froeb** [comment]
Thanks for confirming. So i come back to my original message above where i wrote: „ it should be possilbe to either disable choco or (preferable) win-get [in topgrade]“.

before topgrade i only used choco and was happy. I used topgrade for the other functionality. So i would be very gappy to use all of topgrade except for win-get. As long this is not possible, i am using choco only. 

but may be i am overlooking something and ut is already possible to disable win-get in topgrade already?

all the best
Kai

**Comment by MCOfficer** [comment]
> but may be i am overlooking something and ut is already possible to disable win-get in topgrade already?

They appear to be implemented as separate steps, so you should be able to disable them selectively:
https://github.com/r-darwish/topgrade/blob/0251c2769b2fe4d1fe0621715055328a8fc43cb1/src/config.rs#L135

so
```toml
disabled = ["winget"]
```

**Comment by Lim-Dul** [comment]
> Thanks for confirming. So i come back to my original message above where i wrote: „ it should be possilbe to either disable choco or (preferable) win-get [in topgrade]“.
> 
> before topgrade i only used choco and was happy. I used topgrade for the other functionality. So i would be very gappy to use all of topgrade except for win-get. As long this is not possible, i am using choco only.
> 
> but may be i am overlooking something and ut is already possible to disable win-get in topgrade already?
> 
> all the best Kai

Go to %APPDATA% and edit topgrade.toml.
In there you will find a section (commented out by default) to disable certain steps.

`# Disable specific steps - same options as the command line flag
#disable = ["system", "emacs"]`

Uncomment this and change to:
`disable = ["winget"]`

This fixes the compatibility issue until winget is more reliable.

**Comment by froeb** [comment]
Thank you so much. That solved the issue for me.
You might want to put it in the readme file for windows users for now…
