### ISSUE TITLE
No module named 'tldr'

### ISSUE THREAD

**Issue by hexarch** [r-darwish/topgrade#821]
As with cargo-update not being installed it suggested:

> cargo-update isn't installed so Topgrade can't upgrade cargo packages.
> Install cargo-update by running `cargo install cargo-update`

Regarding tldr it only show's the error and asks "retry yes no shell":

```
―― 16:58:33 - TLDR ―――――――――――――――――――――
Traceback (most recent call last):
  File "/usr/bin/tldr", line 5, in <module>
    from tldr import cli
ModuleNotFoundError: No module named 'tldr'

Retry? (y)es/(N)o/(s)hell

```

So it would be nice to install it or tell the user to install it with: "pip install tldr"

**Comment by MCOfficer** [comment]
That's weird, the TLDR step requires a `tldr` executable to be in `$PATH`. So you shouldn't see that step in the first place.

Can you check for that stray executable, or post the output with `--verbose`?

**Comment by r-darwish** [comment]
Something is wrong with your installation of tldr. Either remove or reinstall it.
