### ISSUE TITLE
MacOS Additions

### ISSUE THREAD

**Issue by drewauff** [r-darwish/topgrade#822]
On MacOS I'd love to see the following added :

- The ability to extend the "Summary" by showing the package(s) the were update and not just the name package manager

- The ability to skip MacOS system upgrade (if there is a way to do this I haven't been able to find it..yet .

Thats it for now!
Keep up the awesome work!

**Comment by MCOfficer** [comment]
>     * The ability to skip MacOS system upgrade (if there is a way to do this I haven't been able to find it..yet .

You can disable the `system` step using `--disable` or the config file, but that will disable the App Store.

**Comment by drewauff** [comment]
@MCOfficer Thats precisely the point..disable system upgrade but keep App Store

**Comment by drewauff** [comment]
ok, figured the 2nd point out, just uncomment the line disable etc. and add mas to it.

**Comment by r-darwish** [comment]
> * The ability to extend the "Summary" by showing the package(s) the were update and not just the name package manager
> *

This isn't the purpose of the summary section. The steps themselves show which packages were updated.

**Comment by drewauff** [comment]
I beg to differ, when you are updating a lost of packages its nice to be able to see what was updated. At the very least it should be an option. User should be
able to decide what they want or do not want to see.
