### ISSUE TITLE
Topgrade creates folders named ${XDG_CACHE_HOME} and ${XDG_DATA_HOME} in the current directory

### ISSUE THREAD

**Issue by willbou1** [r-darwish/topgrade#827]
As said in the title, when I run topgrade, I get these folders created in the directory it's run from. Since this is clearly the syntax of a bash substitution, I get the feeling that single quotes were used instead of double quotes somewhere in the code. That, in turn, caused the bash substitution to be interpreted literally as normal characters.

The folders contain a single directory : npm. Therefore, the node packages upgrade process must be to blame.

**Comment by r-darwish** [comment]
Can you create a docker container that reproduces this issue?
