### ISSUE TITLE
Standalone application

### ISSUE THREAD

**Issue by malys** [r-darwish/topgrade#833]
***Which tool is this about? Where is its repository?*** internal development
***Which operating systems are supported by this tool?*** Windows (mainly for me), but every OS

**I want to suggest some general feature**
I think this feature is not currently supported.
We use many times standalone application which binary is downloaded directly from github release  because they don't provide installation package (chocolatey, scoop, deb...)
It could be interesting to add a list of standalone applications in config.yaml
- name: topgrade
- from: regexp url to download it
- to: folder to install it ( /usr/bin or c:\util)

**More information**
- Assuming that someone else implements the feature, please state if you know
  how to test it from a side branch of Topgrade

Thanks for your awesome tool

**Comment by r-darwish** [comment]
Interesting idea. However, it will be hard to know which version is currently installed without keeping track of it in some sort of database.

**Comment by MCOfficer** [comment]
> Interesting idea. However, it will be hard to know which version is currently installed without keeping track of it in some sort of database.

The naive approach would be to call it with `--version` and regex the output for a serde version. That would cover perhaps 80, 90% of cases. For more flexibility, we could also let the user choose to

- regex a file with a provided regex
- regex a provided command with a provided regex

to find the version number.

**Comment by r-darwish** [comment]
Okay, so I think we should leave this logic to an external tool and let Topgrade run it. I don't mind trying to write this tool by myself when I have some spare time, I wonder who is it that no one already made such tool.

**Comment by malys** [comment]
I have not found a CLI doing the stuff. There are many examples of commands to do it for github release.
[example](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8).
For me, it could be natural to integrate it in topgrade to have a universal update manager.
Moreover, it could be possible to use sha1 of file as versioning.

**Comment by MCOfficer** [comment]
> I have not found a CLI doing the stuff. There are many examples of commands to do it for github release. [example](https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8). For me, it could be natural to integrate it in topgrade to have a universal update manager. Moreover, it could be possible to use sha1 of file as versioning.

At that point, this is basically scoop. So imo the answer to "why doesnt it exist" is that it does exist on windows, and mac and linux are to a large extent covered by homebrew, official repos and the AUR.

Not saying that these cases are invalid, but it makes sense that not many programmers who could make such a thing feel the need for it.

**Comment by xeruf** [comment]
Yep, on arch you would simply create an AUR package, on other systems a PPA or whatever (though these tend to be harder).
I know your issue, but I agree with @r-darwish - create a separate tool and make it run by `topgrade`, otherwise it stops being a tool that does one thing well - which for topgrade is finding and invoking package managers, not downloading content by itself.

**Comment by r-darwish** [comment]
Closing this as this is not the scope of Topgrade. I'll add support for an external tool once one with enough popularity will come out

**Comment by xeruf** [comment]
Just chiming in to mention that instalee is ready for beta-testing if anyone is interested :) @malys 
https://github.com/xeruf/instalee

I am starting to use it productively now, on servers, desktop machines and even windows devices (ugh!).
