### ISSUE TITLE
Updateing Gnome Shell extensions will not work on Phosh

### ISSUE THREAD

**Issue by CoderThomasB** [r-darwish/topgrade#835]
**What did you expect to happen?**
Topgrade sees that dbus path `org.gnome.Shell.Extensions` is not registered and does not perform a `Gnome Shell extensions` update.

**What actually happened?**
Topgrade tries to update `Gnome Shell extensions` but fails because Phosh does not register `org.gnome.Shell.Extensions`

**Additional details:**
- Which operating system or Linux distribution are you using?
manjaro-arm
- How did you install Topgrade?
The AUR

**Comment by r-darwish** [comment]
Can you tell which command does Topgrade need to run to determine whether a specific dbus path is registered or not?

**Comment by CoderThomasB** [comment]
You can use this to try it out in the terminal but the checking for the `org.gnome.Shell.Extensions` string should probably be done in code.
```
gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/DBus --method  org.freedesktop.DBus.ListActivatableNames | grep -q org.gnome.Shell.Extensions && echo Yes
```

**Comment by r-darwish** [comment]
@AdallomRoy can you paste me the output of
```shell
gdbus call --session --dest org.freedesktop.DBus --object-path /org/freedesktop/DBus --method  org.freedesktop.DBus.ListActivatableNames
```
On your laptop?
