### ISSUE TITLE
8.2.0 broke conda's `auto_activate_base: false`

### ISSUE THREAD

**Issue by bdaase** [r-darwish/topgrade#840]
I have the following line in my `.condarc` to not have an active base by default

```
auto_activate_base: false
```

**What did you expect to happen?**

When running topgrade I expect that it can either deal with it or does nothing.

**What actually happened?**

Instead topgrade shows

```
―― 14:33:32 - Conda ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

NoBaseEnvironmentError: This conda installation has no default base environment. Use
'conda create' to create new environments and 'conda activate' to
activate environments.



Retry? (y)es/(N)o/(s)hell
```

**Additional details:**
- Fedora 35
- cargo

**Comment by r-darwish** [comment]
Is there any Conda command that Topgrade can run to check this? I rather not start parsing Conda's config by myself.

**Comment by bdaase** [comment]
I have no idea tbh.

**Comment by bdaase** [comment]
Checking for `echo $CONDA_PREFIX` should work. When the result is empty, no environment is active.

**Comment by r-darwish** [comment]
What's the outpost of `conda config --show auto_activate_base`?

**Comment by bdaase** [comment]
```
aucto_activate_base: False
```
