### ISSUE TITLE
Do not fail parsing config when a disabled step was not found

### ISSUE THREAD

**Issue by xeruf** [r-darwish/topgrade#847]
As steps are added and changed, the ones one might to disable by default change, too.
But when topgrade recognizes an unknown step to be disabled in the config-file, it not only warns, it stops parsing it altogether.
This poses multiple issues, especially for setups where different topgrade versions are used across different systems with the same config file.

**What did you expect to happen?**
topgrade may warn when there is an invalid step to be disabled from the config,
but it should still disable all the other ones.

**What actually happened?**
If a step is changed (such as `pacdiff`) or I disable a newly added step and run an older version of topgrade on another device with the same config, it resorts to running *all* steps.

**Additional details:**
- Which operating system or Linux distribution are you using? Multiple (Arch, Debian, ...)
- How did you install Topgrade? Package manager

**Comment by r-darwish** [comment]
Sorry, but I'm against this one. It's very rare to change a step's name.

**Comment by xeruf** [comment]
That may be true, but steps being added is not uncommon, and running software with the same config on both Debian stable and latest Arch is not uncommon.
Is there any counterargument other than it not being a common usecase?
