### ISSUE TITLE
configure the option to skip new files found by default

### ISSUE THREAD

**Issue by henrydenhengst** [r-darwish/topgrade#854]
## I want to suggest some general feature
Topgrade should let me configure the option to skip new files found by default.

―― 19:50:48 - Configuration update ―――――――――――――――――――――――――――――――――――――――――――――
==> pacnew file found for /etc/bluetooth/main.conf
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] s
==> pacnew file found for /etc/nsswitch.conf
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] s
==> pacnew file found for /etc/default/grub
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] s
==> pacnew file found for /etc/pacman.d/mirrorlist
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] s
==> pacnew file found for /etc/systemd/logind.conf
:: (V)iew, (S)kip, (R)emove pacnew, (O)verwrite with pacnew, (Q)uit: [v/s/r/o/q] s

YES, I am willing to TEST !

**Comment by MCOfficer** [comment]
If i'm reading the code correctly, you should be able to skip this step by adding it to the "yes"-list in the config:

```toml
yes = ["config_update"]
```

or just to the list of disabled step.

If that's not what you want, i misunderstood.

**Comment by henrydenhengst** [comment]
When I put 
`yes = ["config_update"]`
in my config file topgrade.toml and I run topgrade I get a messive amount of errors.
Maybe I am doing something wrong?
I am trying to run my topgrade so that I do not have to choose anything and everything is preset according to my preference.

**Comment by r-darwish** [comment]
I'll release a new version this week.

**Comment by henrydenhengst** [comment]
Which version is the new version? I am now running: Topgrade 8.2.0
