### ISSUE TITLE
"Ultimate vimrc" support

### ISSUE THREAD

**Issue by Samisafool** [r-darwish/topgrade#856]
### Which tool is this about? Where is its repository?

This is about the "Ultimate vimrc": https://github.com/amix/vimrc

### Which operating systems are supported by this tool?

All

### What should Topgrade do to figure out if the tool needs to be invoked?

Check if ~/.vim_runtime exists `[[ -d ~/.vim_runtime ]]`. Technically it can be installed anywhere but this is the default one.

### Which exact commands should Topgrade run?

```bash
cd ~/.vim_runtime
git reset --hard
git clean -d --force
git pull --rebase
python update_plugins.py  # use python3 if python is unavailable
```

## More information

Instead of this, an alternative would be custom steps. I don't see docs on that though.

**Comment by p00f** [comment]
For custom steps you can add an entry in the `[commands]` section like so:
```toml
[commands]
"Neovim" = "paru -S aur/neovim-git"
```

**Comment by r-darwish** [comment]
This seems highly popular, so it makes sense Topgrade will support it.

**Comment by Samisafool** [comment]
> For custom steps you can add an entry in the `[commands]` section like so:
> 
> ```toml
> [commands]
> "Neovim" = "paru -S aur/neovim-git"
> ```
> 
> so you can wrap your commands in a script and add that script to topgrade

Why isn't that in the wiki, man...

**Comment by sankalp-khare** [comment]
@Samisafool custom steps are in the example config file provided though https://github.com/r-darwish/topgrade/blob/master/config.example.toml#L58
