### ISSUE TITLE
can't find topgrade on rpi

### ISSUE THREAD

**Issue by thob** [r-darwish/topgrade#861]
I'm running the latest Raspberry OS (64bit) on an RPI 400. I put topgrade into 

```
pi@pi:~ $ which topgrade
/usr/local/bin/topgrade
```

but running topgrade can't find it  

```
pi@pi:~ $ topgrade
bash: /usr/local/bin/topgrade: No such file or directory

**Comment by MCOfficer** [comment]
Did you make it executable?

It could also mean that some dynamic library (specifically libc) couldnt be found, so also try the "musl" version of topgrade.

**Comment by thob** [comment]
it says it's executable by anyone. I did not make it executable explictly, I forgot to mention that I installed the arm7 version, Is "musl" preferred?

**Comment by r-darwish** [comment]
1. What's the output of `file /usr/local/bin/topgrade`?
2. What happens if you run `/usr/local/bin/topgrade`?

**Comment by thob** [comment]
getting this for `file`
`/usr/local/bin/topgrade: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=bb9a8a215870de56c936f06969034e92eac59fe9, with debug_info, not stripped`

**Comment by MCOfficer** [comment]
> it says it's executable by anyone. I did not make it executable explictly, I forgot to mention that I installed the arm7 version, Is "musl" preferred?

The musl version is the more portable version since it requires no libc - but only for x64_86, not arm. My bad.
