### ISSUE TITLE
Update composer itself

### ISSUE THREAD

**Issue by openjck** [r-darwish/topgrade#871]
Composer ships with a command for updating itself. Considering that [manual installation of Composer](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-composer-on-ubuntu-20-04) is recommended on Ubuntu, I think that automatically updating Composer with topgrade would be a good idea.

### Which tool is this about? Where is its repository?

composer

https://github.com/composer/composer

### Which operating systems are supported by this tool?

*nix, macOS, Windows

### What should Topgrade do to figure out if the tool needs to be invoked?

I'm afraid I'm not sure. It seems that running `composer self-update` is safe when Composer is already updated to the latest version, however.

### Which exact commands should Topgrade run?

`composer self-update`

## More information

> Assuming that someone else implements the feature, please state if you know how to test it from a side branch of Topgrade.

Yes, I can help test this change.

**Comment by r-darwish** [comment]
You  can set
```toml
[composer]
self_update = true
```
In your configuration, which will cause Topgrade to do that.
