### ISSUE TITLE
now it's - may be - silnite which applies macOS updates without asking re:fixed in #433

### ISSUE THREAD

**Issue by AWHubGit** [r-darwish/topgrade#873]
fixed in #433

_Originally posted by @r-darwish in https://github.com/r-darwish/topgrade/issues/419#issuecomment-644112776_

**Comment by AWHubGit** [comment]
now it's - may be - silnite which applies macOS updates without asking.

I am on macOS 12.3 now without my consent. Running topgrade silnite applied update to macOS 12.3 without asking. Topgrade stopped working for a long time without any message, but silnite downloaded and applied update to 12.3 in the background. This may be dangerous if user makes a hard reset, cuts power.

May be silnite is wrong/unreliable as only running "silnite" === "silnite bmx" (silnite to run minimal check, no update check, returning a plist) as per "silnite h".

Awaiting update to 12.3 I uncommented "disable =" and put "["system", "mas"] in topgrade's config file to prevent update to 12.3, but wasn't aware of silnite's update check.

**Comment by r-darwish** [comment]
@benmontour can you advise on this? I don't use silnite myself.

**Comment by benmontour** [comment]
You are correct. I was not aware that running `silnite au` would apply macOS updates in addition to things like MRT and XProtect, but it seems it does do that using the built in softwareupdate mechanism in macOS. I will request some clarification from the developer on the differences between the au and bu option flags and advise.

**Comment by benmontour** [comment]
So after a brief chat with the developer it seems that there’s no way around the macOS update while also updating XProtect and MRT. With that in mind I think the best option would be to either remove silnite from topgrade or move it to use only `a` and have it just report info and not actually download any updates.
