### ISSUE TITLE
Disable oh-my-zsh update check on MacOS

### ISSUE THREAD

**Issue by nivaca** [r-darwish/topgrade#888]
## I want to suggest some general feature
Topgrade should be able to skip update check for oh-my-zsh on MacOS. There should be a config option for that.

## More information

Installed topgrade from brew on MacOS.

**Comment by MCOfficer** [comment]
FWIW you can disable the `shell` step, however this may disable other things you might need as well.

**Comment by r-darwish** [comment]
Is there any way to detect if oh-my-zsh was installed from brew without running a brew command?

**Comment by MCOfficer** [comment]
> Is there any way to detect if oh-my-zsh was installed from brew without running a brew command?

I can't find a formula for oh-my-zsh. Are you sure you didn't misread OP's last line?

**Comment by fragolinux** [comment]
Hi, any way to disable this step? Didn't find it yet... thanks
