### ISSUE TITLE
Does the 'Emacs Snapshot' sample work?

### ISSUE THREAD

**Issue by bbigras** [r-darwish/topgrade#89]
In the command from the README:
```sh
rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak
```

I might be wrong but `cp` uses `-l` which make links instead of copying. Doesn't that make `~/.emacs.d/elpa.bak` useless? It will always be the same as `~/.emacs.d/elpa`.

**Comment by r-darwish** [comment]
It's impossible to hard-link directories, you only link files. `cp -rl` from one directory to another creates the same directory structure, but links only the files. It means that if the content of a specific file is changed on one directory, the change will also be reflected to the second directory. However, directory changes, such as deleting or adding files should not be reflected in the destination.

Try the following commands and look at the results:

```bash
mkdir src
echo 1 > src/a
echo 1 > src/b
cp -rl src dest
rm src/a
echo 2 >> src/b
```

As far as I understand, Emacs doesn't change the content of files. It just downloads new packages.

Having said that, I never actually recovered ELPA directory with that method
