### ISSUE TITLE
Replace apt with apt-fast 

### ISSUE THREAD

**Issue by PrudhviBoggavarapu** [r-darwish/topgrade#891]
## I want to suggest a new step

Use apt-fast instead of apt-get 
### Which tool is this about? Where is its repository?
This will speed up the apt download speed 

https://github.com/ilikenwf/apt-fast

### Which operating systems are supported by this tool?
Any linux distro that uses apt

### What should Topgrade do to figure out if the tool needs to be invoked?
It is a drop in replacement 
### Which exact commands should Topgrade run?
Replace apt with apt-fast everytime apt is used
## I want to suggest some general feature
Topgrade should...
Replace apt with apt-fast everytime apt is used

**Comment by MCOfficer** [comment]
> ### What should Topgrade do to figure out if the tool needs to be invoked?
> 
> It is a drop in replacement

Checking if the `apt-fast` command is in PATH should be sufficient. It's user-installed and a bit rare to see these days, so there are absolutely cases where it won't be installed.

**Comment by r-darwish** [comment]
https://github.com/r-darwish/topgrade/blob/547df8d346e8a7689213299f6fbb1d5807988b44/src/steps/os/linux.rs#L286

There's already support for apt-fast. Do you have `apt-fast` in your PATH?
