### ISSUE TITLE
Upgrade IDEs installed with Jetbrains toolbox

### ISSUE THREAD

**Issue by cmalvi** [r-darwish/topgrade#899]
### Which tool is this about? Where is its repository?
The tool from Jetbrains used to install their IDEs
### Which operating systems are supported by this tool?
Linux, Windows, macOS
### What should Topgrade do to figure out if the tool needs to be invoked?
Use it to checks for IDEs upgrade avaiability
### Which exact commands should Topgrade run?
Seems there isn't a command line interface, here the issue https://youtrack.jetbrains.com/issue/TBX-653

## I want to suggest some general feature
Topgrade should check for avaiable update

## More information

I know that, due to missing cli for Jetbrains, this won't be easy.
Toolbox isn't a "light" application so, let Topgrade do those update, will be very useful for those people with less capable machines to keep programs run in background.

**Comment by r-darwish** [comment]
Since there's no command line option to control the toolbox, how do you suggest to implement this feature?

**Comment by cmalvi** [comment]
do you think will be a good workaround to check installed IDEs and then download directly from jetbrains site?

**Comment by r-darwish** [comment]
I think this is a bit out of scope for Topgrade. The purpose of Topgrade is to run existing upgrading mechanisms, not to implement its own. The best I can offer is that you try to install JetBrains products through some kind of package manager such as Chocolatey or Brew

**Comment by cmalvi** [comment]
I'm on Linux but i understood, you're right. Thank you
