### ISSUE TITLE
Add flag for automatic reboot

### ISSUE THREAD

**Issue by r-darwish** [r-darwish/topgrade#9]

**Comment by r-darwish** [comment]
I decided not to do that for the moment, as it will not allow the user to see the output of the commands.

**Comment by PolpOnline** [comment]
This should be definitely reconsidered, automatic shutdown/reboot would be very useful for people like me who update there PCs when they finished working on them.
Saving log output shouldn't be a problem, another flag could be introduced to choose a log file to save everything (just piping would be fine).
