### ISSUE TITLE
No 'failed step' notification

### ISSUE THREAD

**Issue by JacobTravers** [r-darwish/topgrade#903]
notifications for the beginning of a step work, but notifications for a failed step do not appear to be working on my machine
![no-fail](https://user-images.githubusercontent.com/46337843/165397061-1652c031-811f-4aa1-be8f-f34b2d2d8bfc.gif)

**Comment by r-darwish** [comment]
The first two sound like a good idea. I have no idea how to implement the third.

**Comment by r-darwish** [comment]
https://github.com/r-darwish/topgrade/blob/336f529410a0c9c0fa884ea07f6fa3fa11428c0c/src/terminal.rs#L222

There's already a desktop notification when a step fails. Adding a notification when one succeeds seems redundant as you see the notification of the next step beginning. Aren't failure notifications displayed on your computer?

Notification for input would be awesome but I cannot think of any way to implement it.

**Comment by JacobTravers** [comment]
> There's already a desktop notification when a step fails ... Aren't failure notifications displayed on your computer?

I do not get notifications when a step fails, only when a step starts. I didn't realize this was the intended default behavior, I will update the issue.

> Notification for input would be awesome but I cannot think of any way to implement it.

Same, I'm not sure if it's possible but I mentioned it just in case someone else knows better.

**Comment by JacobTravers** [comment]
I've updated the issue and also attached a Gif to show the current behavior.
