### ISSUE TITLE
topgrade: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory (fedora 36 beta)

### ISSUE THREAD

**Issue by OldWorldOrdr** [r-darwish/topgrade#906]
## What did you expect to happen?
topgrade to run normally

## What actually happened?
error: `topgrade: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

## Additional details
- Which operating system or Linux distribution are you using? fedora 36 beta
- How did you install Topgrade? github release

<details><pre>
Paste the output of `topgrade -v` topgrade: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory (I'm using the latest github release as of writing this)
</pre></details>

**Comment by MCOfficer** [comment]
You should be able to fix this by installing the `openssl1.1` package.

A more general fix on our end would be to f.e. switch to rustls for TLS support.

**Comment by helkaluin** [comment]
I'm afraid the `libssl1.1` package is no longer in the Ubuntu repos as of 22.04 Jammy. The last release that has it is 21.10 Impish. See: https://packages.ubuntu.com/search?keywords=libssl1.1

**Comment by MCOfficer** [comment]
I wonder, can you give the musl release a try?

https://github.com/r-darwish/topgrade/releases/download/v8.3.1/topgrade-v8.3.1-x86_64-unknown-linux-musl.tar.gz

**Comment by helkaluin** [comment]
Yup, the musl one works. It's a static build isn't it.

**Comment by r-darwish** [comment]
I'll look into it

**Comment by OldWorldOrdr** [comment]
> It seems it's still trying to load libssl.so.1.1 with the 9.0.0 release.

yep.  musl still works tho
