### ISSUE TITLE
pip should be executed via the regular python executable

### ISSUE THREAD

**Issue by hacker1024** [r-darwish/topgrade#910]
The `pip` executable now displays the following message:

> WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.

It should now be invoked with `python -m pip` to avoid issues.

**Comment by r-darwish** [comment]
Which operating system are you using?

**Comment by hacker1024** [comment]
macOS Catalina with Python via brew
