### ISSUE TITLE
Improve winget support on by default skip unknown versions

### ISSUE THREAD

**Issue by MANICX100** [r-darwish/topgrade#928]
## I want to suggest some general feature
Topgrade should have winget enabled by default for windows hosts BUT skip packages of unknown version to avoid constantly redownloading existing versions.

## More information
A script implementing this behavior is available here:
[https://gist.github.com/Nejat/6cb42f098320cb2fcb57a4e1728ca29e](https://gist.github.com/Nejat/6cb42f098320cb2fcb57a4e1728ca29e)

Thanks @najat

**Comment by r-darwish** [comment]
Seems like a lot of logic to implement in Topgrade so I'm debating whether the best thing to do is to embed this script inside it.
@Najat since this script has no license attached, may I have your permission to embed it inside Topgrade?
