### ISSUE TITLE
tmux plugins upgrade fails unless TMUX_PLUGIN_MANAGER_PATH is set

### ISSUE THREAD

**Issue by npadgen** [r-darwish/topgrade#93]
It's possible to install tpm (the tmux plugins manager) and have it fully working without setting TMUX_PLUGIN_MANAGER.  The default location is `$HOME/.tmux/plugins/tpm`.  However, topgrade fails in this case.

```
$ topgrade

―― Brew ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Already up-to-date.
Updating Homebrew...

―― tmux plugins ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
unknown variable: TMUX_PLUGIN_MANAGER_PATH
FATAL: Tmux Plugin Manager not configured in tmux.conf
Aborting.

Retry? [y/N]

[...]
```

```
$ TMUX_PLUGIN_MANAGER_PATH=$HOME/.tmux/plugins/tpm topgrade

―― Brew ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Already up-to-date.
Updating Homebrew...

―― tmux plugins ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Updating all plugins!

[...]
```

**Comment by r-darwish** [comment]
How do you activate TPM in your tmux configuration? What I do is put `run -b '~/.tmux/plugins/tpm/tpm'` at the end of my tmux configuration, as suggested by the TPM readme.

**Comment by npadgen** [comment]
Exactly the same!

**Comment by r-darwish** [comment]
I use my tmux configuration in macOS, FreeBSD and Linux, and I did not encounter this problem. Can you show me your exact configuration?

**Comment by npadgen** [comment]
```

set -g status-right '#{prefix_highlight} | #[fg=green,bg=black]#(tmux-mem-cpu-load --colors --interval 2)#[default]'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'

set -g status-interval 2
set -g status-left "#S "
set -g status-right-length 60

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
```

**Comment by r-darwish** [comment]
Ok, so it appears that they recently [changed](https://github.com/tmux-plugins/tpm/commit/a403ca3b67f880fc3ef3f585bae2779932570cf5) their recommended installation method by adding the `-b` flag, which I did not have in my configuration. Since TPM is loaded in the background it seems to cause a race condition.

Thanks for reporting.

**Comment by r-darwish** [comment]
I changed to code to set `TMUX_PLUGIN_MANAGER_PATH` and commented out the line starting with `run` to make sure I don't succeed by accident. TPM works, but it shows no plugins.

```
―― tmux plugins ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Updating all plugins!


```

I'll look into this a bit further but I think that there's no way for Topgrade to overcome this if you use the `-b` flag. The proper solution is probably to remove it.
