### ISSUE TITLE
ZSH zi step runs when zoxide is installed due to alias name collision

### ISSUE THREAD

**Issue by trmckay** [r-darwish/topgrade#935]
## What did you expect to happen?

ZSH "zi" step should only run if [zi](https://github.com/z-shell/zsh) is installed, not if the alias [`zi` from zoxide](https://github.com/ajeetdsouza/zoxide) is available.

## What actually happened?

`zi` is run, but it fails because it is not the command that the step expects.

## Additional details

The error occurs [here](https://github.com/r-darwish/topgrade/blob/29644d6ffadd98f785352c289b10f167aee32a48/src/steps/zsh.rs#L108) since it is executing the command after sourcing the user's zshrc.

This is tough because for many of the steps, the zshrc needs to be sourced to pick up plugins, but this increases the likelihood of name collisions like this.

**Comment by MCOfficer** [comment]
Can we just check for the existance of `~/.zi` instead?

**Comment by trmckay** [comment]
That could work. I'd be happy to draft a PR if this is wanted.

**Comment by r-darwish** [comment]
@trmckay please go ahead

**Comment by r-darwish** [comment]
https://github.com/r-darwish/topgrade/blob/08e8b56b75fd273b0bad17dcec5bb7f1a9b289f5/src/steps/zsh.rs#L101-L105

We don't check the existance of `zi`, but `ZPFX` instead. @t4i5uKE can you explain the role of this environment variable?

**Comment by trmckay** [comment]
After looking at [zinit](https://github.com/zdharma-continuum/zinit/search?q=ZPFX), it looks like the `ZPFX` variable is the prefix for the installation directory. Also, it appears [zi](https://github.com/z-shell/zi/search?q=ZPFX) also uses this variable for a similar purpose.

**Comment by trmckay** [comment]
Maybe my usage of `zinit` over `zi` is the real issue here.

**Comment by r-darwish** [comment]
So, if ZPFX is set, there supposed to be a `zi` or `.zi` directory inside the ZPFX directory?

**Comment by ss-o** [comment]
Hi :wave: 

I just noticed this issue. Due to similar issues, I wrapped `zi` in a function:

```zsh
❮▼❯() { zi "$@"; }
```

which makes `zi` available as `❮▼❯`.

---

Also noticed some confusion, feel free, and also I would appreciate it if mention me to help with `zi / zsh` related issues in the future as I am the maintainer of `zi` and a user of `topgrade`. :octocat:

Thanks,
