### ISSUE TITLE
why topgrade 9.0.0 on osx, but 8.3.0 on ubuntu 22.04 LTS via rustup?

### ISSUE THREAD

**Issue by comatosejones** [r-darwish/topgrade#945]
On my iMacs, topgrade via homebrew is at v 9.0.0, but on my work servers (Ubuntu 22.04, installed via rustup), it's still 8.3.0.

**Comment by MCOfficer** [comment]
Can you post the output of `topgrade -v` on your work servers?

**Comment by r-darwish** [comment]
Forgot to publish 9.0.0 on crates.io. Fixed

**Comment by comatosejones** [comment]
ty
