### ISSUE TITLE
 --yes command no longer matches man file

### ISSUE THREAD

**Issue by duckunix** [r-darwish/topgrade#947]
## What did you expect to happen?
`topgrade --yes` use to run with any prompts, and that is what the man page still says (see https://github.com/r-darwish/topgrade/blob/master/topgrade.8#L70)

## What actually happened?
`topgrade --yes` returns error:
```
$ topgrade --yes
error: The argument '--yes <YES>' requires a value but none was supplied
        [possible values: asdf, atom, brew_cask, brew_formula, bin, cargo, chezmoi, chocolatey, choosenim, composer, conda, config_update, containers, custom_commands, deb_get, deno, dotnet, emacs, firmware, flatpak, flutter, fossil, gcloud, gem, github_cli_extensions, git_repos, go, haxelib, gnome_shell_extensions, home_manager, jetpack, kakoune, krew, macports, mas, micro, myrepos, nix, node, opam, pacstall, pearl, pipx, pip3, pkg, pkgin, pnpm, powershell, raco, remotes, restarts, rtcl, rustup, scoop, sdkman, sheldon, shell, snap, spicetify, stack, system, tldr, tlmgr, tmux, toolbx, vagrant, vcpkg, vim, winget, wsl, yadm]

USAGE:
    topgrade [OPTIONS]

For more information try --help
```
Please either revert the behavior to match the man page, or add an `all` flag to restore the old behavior.

## Additional details
- Which operating system or Linux distribution are you using?
  - EndeavourOS
- How did you install Topgrade?
  - pacman -S topgrade

<details><pre>
$ topgrade -V
Topgrade 9.0.0
</pre></details>

**Comment by r-darwish** [comment]
Already fixed in 9.0.1 which will be released soon (#993)
