### ISSUE TITLE
update valet

### ISSUE THREAD

**Issue by bingalls** [r-darwish/topgrade#99]
[Valet](https://laravel.com/docs/5.7/valet) is a developer-friendly tool for managing virtual hosts on nginx, generally with PHP.
The problem is that `composer global update` or php update can break valet. The solution is easy: check if `~/composer/vendor/bin/valet` is in the path, or if ~/.config/valet/ exist.
After every `composer global update` (and/or php upgrade), run `valet install`.
Note that valet is not available on MS Windows.

**Comment by r-darwish** [comment]
I pushed the change to a side branch called `valet`. Can you please confirm that it's working?

**Comment by bingalls** [comment]
It looks like it is working! Closing...
